### ISSUE TITLE
Button Color Blue=Cyan

### ISSUE THREAD

**Issue by MateoWartelle** [themesberg/flowbite-react#1010]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

https://github.com/themesberg/flowbite-react/blob/main/src/components/Button/theme.ts#L21

## Current behavior

Describe what is currently happening and why it's a problem.

`<Button color="blue">
       Publish post
   </Button>`

<img width="197" alt="button-color-blue" src="https://github.com/themesberg/flowbite-react/assets/27743176/6b77afeb-bc16-432f-a098-1fd50ab31d90">

## Expected behavior

Describe what you expected to happen.

<img width="171" alt="flowbite-button-color-blue" src="https://github.com/themesberg/flowbite-react/assets/27743176/b3ce0733-bf9a-4f87-ad65-35e1d021698c">

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by JDouven** [comment]
Hi, the other colors are also broken in dark mode. The `bg-color-xxx` are missing the `dark:` attribute.

**Comment by MateoWartelle** [comment]
> Hi, the other colors are also broken in dark mode. The `bg-color-xxx` are missing the `dark:` attribute.

Ok I will take a look. Separate issue.

**Comment by JDouven** [comment]
@MateoWartelle I've created an issue https://github.com/themesberg/flowbite-react/issues/1045
