### ISSUE TITLE
Floating Label theme import

### ISSUE THREAD

**Issue by nitishkr72** [themesberg/flowbite-react#1022]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version [0.6.2]

## Steps to reproduce

1. While using flowbite-react library
## Current behavior

Not able to use library,  getting error 
ERROR in ./node_modules/flowbite-react/lib/esm/theme.js 1:0-74
Module not found: Error: Can't resolve '~/src/components/FloatingLabel/theme' 

## Expected behavior

problem in \node_modules\flowbite-react\lib\esm\theme.js

## Context

It happen when you import flowbite-react library
![Capture2](https://github.com/themesberg/flowbite-react/assets/43314706/d625e1dc-fdc4-4a86-b95b-7a83b18763ed)

**Comment by micduffy** [comment]
suddenly, this morning, I am also getting this just FYI. Using flowbite 0.6.2

**Comment by nitishkr72** [comment]
> suddenly, this morning, I am also getting this just FYI. Using flowbite 0.6.2

This is probably because wrong import in flowbite-react\src\theme.ts
![Capture2](https://github.com/themesberg/flowbite-react/assets/43314706/0c5d3bf2-743e-4575-847b-b40da8f935ef)

**Comment by itaysarfaty** [comment]
Facing the same issue :/

**Comment by micduffy** [comment]
I just pinned to 0.6.1 in package.json and works again

**Comment by zschapel** [comment]
+1 on 0.6.2. Revert back to 0.6.1 resolves for now.

**Comment by rluders** [comment]
Should be fixed at `0.6.2`

**Comment by micduffy** [comment]
thank u
