### ISSUE TITLE
Datepicker wrong days display

### ISSUE THREAD

**Issue by xSyki** [themesberg/flowbite-react#1038]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Create default datepicker on latest version

## Current behavior

Wrong display of days in the monthly view. As in example bellow, in october 2023, we see thu as 3/10/2023, but actually is tue.

## Context

<img width="286" alt="Zrzut ekranu 2023-10-3 o 18 26 30" src="https://github.com/themesberg/flowbite-react/assets/86367246/1f0cbe71-9c05-4cb1-868a-34e55ec57534">

**Comment by rluders** [comment]
Version?

**Comment by xSyki** [comment]
@rluders Current main, as well as 0.6.3 and current latest beta.

**Comment by xSyki** [comment]
@rluders I found a bug, it's in getWeekDays function. We stick with Saturday = 0, Sunday = 1, Monday = 2. So function should look like this:

```diff
export const getWeekDays = (lang: string, weekStart: WeekStart): string[] => {
  const weekdays: string[] = [];
  const date = new Date();

  const formatter = new Intl.DateTimeFormat(lang, { weekday: 'short' });

  for (let i = 0; i < 7; i++) {
-  const dayIndex = (i + weekStart + 1) % 7; // Calculate the correct day index based on weekStart
+  const dayIndex = (i + weekStart - 1) % 7; // Calculate the correct day index based on weekStart
    date.setDate(dayIndex + 1);
    const formattedWeekday = formatter.format(date);
    weekdays.push(formattedWeekday.slice(0, 2).charAt(0).toUpperCase() + formattedWeekday.slice(1, 3));
  }

  return weekdays;
};
```

I will submit pull request in a minut, after more testing.

**Comment by xSyki** [comment]
@rluders Pull request submitted https://github.com/themesberg/flowbite-react/pull/1040
