### ISSUE TITLE
TypeError: document.getElementsByTagName in dependency node_modules/react-indiana-drag-scroll/

### ISSUE THREAD

**Issue by dan-valang** [themesberg/flowbite-react#1046]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

Describe the bug
Getting an error in nextjs when importing components

Server Error
TypeError: document.getElementsByTagName is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack

file: /node_modules/react-indiana-drag-scroll/dist/index.js (21:928)

To Reproduce

    import {Button, Label, Modal, Radio, TextInput} from 'flowbite-react'
    When building will give that error, my guess is that is trying to build that as SSR

Expected behavior
Component can be rendered server side without dynamic imports on nextjs

Desktop (please complete the following information):

    OS: Linux, Ubuntu
    Browser Chrome
    "flowbite": "^1.8.1",
    "flowbite-react": "0.6.4"

Using page router

Adding 'use client'
And a dynamic import is the only way I have found for it to work
```
const AssignNewContentModal = dynamic( 
	() =>
		import(
// Custom file with 'use cliient' that exports * from flowbyte react
			'../flowByteReact'
		).then(mod => mod.default),
	{
		ssr: false,
	},
)
```

**Comment by rluders** [comment]
You may be trying to use Server Components. The library doesn't currently support it. See #994

**Comment by rluders** [comment]
@dan-valang did you try to look at the `react-indiana-drag-scroll` repository to see if there is any issue similar to this? Since the error is inside the library it is possible that the solution would be there.
