### ISSUE TITLE
Blockquote Component Link Leads to 404 Error

### ISSUE THREAD

**Issue by anjankarmakar10** [themesberg/flowbite-react#1049]
Description:
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to the [Flowbite-React Documentation](https://www.flowbite-react.com/docs/components/blockquote).
2. Click on the 'Blockquote' component link.

## Current behavior

Clicking on the 'Blockquote' component link on the Flowbite-React documentation website results in a 404 error, indicating that the page does not exist. This issue prevents users from accessing documentation related to the 'Blockquote' component, making it difficult to understand and utilize this feature.

## Expected behavior

Clicking on the 'Blockquote' component link should lead to the appropriate documentation page for the 'Blockquote' component. Users should be able to access information and examples related to this component without encountering a 404 error.

## Context

I am trying to access the documentation for the 'Blockquote' component in Flowbite-React to understand its usage and implementation. This issue occurs regardless of the browser, screen size, or operating system used. It is a problem that affects all users trying to access this specific documentation page.

For reference, here is the link that currently leads to the 404 error: [Blockquote Component Documentation](https://www.flowbite-react.com/docs/components/blockquote).

![Screenshot 2023-10-07 145405](https://github.com/themesberg/flowbite-react/assets/77603380/67842bcc-ea1f-45b2-9ff7-95045783b505)

![Screenshot 2023-10-07 144209](https://github.com/themesberg/flowbite-react/assets/77603380/d46dfad3-e483-43f7-a394-7ac91b47c706)

Please let me know if you need any additional information or if you require a minimal reproduction of the issue.

**Comment by rluders** [comment]
Oh, it was moved to the typography section, we need to remove the old link.

**Comment by MateoWartelle** [comment]
> Oh, it was moved to the typography section, we need to remove the old link.

sorry, my fault.
