### ISSUE TITLE
TypeError: contributors.map is not a function

### ISSUE THREAD

**Issue by paghar** [themesberg/flowbite-react#1052]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1) Use cloudflare warp VPN
2) Run the project
3) Open [http://localhost:3000/](http://localhost:3000/)

## Current behavior

![image](https://github.com/themesberg/flowbite-react/assets/66066475/5a84a9d8-535a-4bc9-ae3d-ba9ad1b811cc)
This is the error that we get if the Github API does not return the value we expected!
Here is the response of the Github API:
![image](https://github.com/themesberg/flowbite-react/assets/66066475/a51d22de-d657-4c51-a39c-3750979fda43)

## Expected behavior

It should run with no error dialogs in the page If there is an error in the Github API request.

**Comment by SutuSebastian** [comment]
Took a look at this locally and it works just fine 🤔

**Comment by SutuSebastian** [comment]
That makes sense now. Well then I guess we should make sure that we only set the state only if the response is a valid one and it actually contains the contributors schema.
