### ISSUE TITLE
Datepicker component

### ISSUE THREAD

**Issue by matheusalxds** [themesberg/flowbite-react#1055]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Current behavior

Describe what is currently happening and why it's a problem.

I'm trying to customize the datepicker in my own Storybook, I have imported it inside the Storybook, but I recieved the following error:

<img width="1142" alt="Screen Shot 2023-10-10 at 17 16 09" src="https://github.com/themesberg/flowbite-react/assets/22510183/06a2aae4-a580-436f-abfd-daa93a5dc6d2">

If `minDate` or `maxDate` are `null`, the component throws an error.

## Expected behavior

Describe what you expected to happen.

If the component receives `null/undefined`, it should do nothing instead of throw error.

**Comment by matheusalxds** [comment]
Currently, the story of Datepicker is not working.
https://storybook.flowbite-react.com/?path=/story/components-datepicker--default

**Comment by rluders** [comment]
Probably connected to #1039

**Comment by matheusalxds** [comment]
The component is also rendering current date + 1, @rluders do you know if it also related to the [#1009](https://github.com/themesberg/flowbite-react/issues/1039?)?

**Comment by matheusalxds** [comment]
Any update?

**Comment by rluders** [comment]
@matheusalxds nope. If someone is interested in fixing it, go ahead.

**Comment by tulup-conner** [comment]
I can't reproduce either of these issues, but we do still have the problem with Storybook where the Datepicker errs once clicked, which is tracked at #1167
