### ISSUE TITLE
Complex selectors in '.peer:focus ~ :is(.dark .peer-focus\:dark\:text-blue-500)' can not be transformed to an equivalent selector without ':is()'.

### ISSUE THREAD

**Issue by dimaslanjaka** [themesberg/flowbite-react#1065]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

https://github.com/dimaslanjaka/webpack-boilerplate/tree/b03ccaf

stylesheet just

```scss
@tailwind base;
@tailwind components;
@tailwind utilities;
```

## Current behavior

Just start dev server after `yarn add flowbite-react` and got errors:

```log
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
(1:1) from "postcss-is-pseudo-class" plugin: Complex selectors in '.peer:focus ~ :is(.dark .peer-focus\:dark\:text-blue-500)' can not be transformed to an equivalent selector without ':is()'.

Code:
  .peer:focus ~ :is(.dark .peer-focus\:dark\:text-blue-500){--tw-text-opacity:1;color:rgba(63, 131, 248, 1);color:rgba(63, 131, 248, var(--tw-text-opacity))}
```

## Expected behavior

webpack server started when using `"flowbite-react": "^0.4.9"` but not when using `"flowbite-react": "^0.6.4"`

## Context

- all webpack config https://github.com/dimaslanjaka/webpack-boilerplate/tree/b03ccaf/config
- dev webpack config https://github.com/dimaslanjaka/webpack-boilerplate/blob/b03ccaf/config/webpack.dev.js

![console output](https://github.com/themesberg/flowbite-react/assets/12471057/00fbabdb-4ef6-4e65-9c05-f95dcfdab5e4)
![web output](https://github.com/themesberg/flowbite-react/assets/12471057/209ba092-4486-47bd-a7de-2e9859c5ac64)

**Comment by rluders** [comment]
@dimaslanjaka what happens if you update the `flowbite` package to `"flowbite": "^1.6.6"`?

**Comment by dimaslanjaka** [comment]
> @dimaslanjaka what happens if you update the `flowbite` package to `"flowbite": "^1.6.6"`?

same

![image](https://github.com/themesberg/flowbite-react/assets/12471057/28c53c7b-cd5a-4f3f-8c0e-7c1e478f92c9)

**Comment by dimaslanjaka** [comment]
when using 

```json
{
    "flowbite": "^1.6.6",
    "flowbite-react": "^0.5.0"
}
```

works

![image](https://github.com/themesberg/flowbite-react/assets/12471057/35310678-6879-41f5-9d5f-2ccc619a3684)

**Comment by ishigami** [comment]
Hi guys,

I'm experiencing the same issue.

I'm using:

```
{
   "flowbite": "^2.0.0",
    "flowbite-react": "^0.6.4",
}
```

**Comment by rluders** [comment]
@ishigami @dimaslanjaka I have no idea what happens here, but... try to update to `@beta` and check if it still happening.

**Comment by tulup-conner** [comment]
This seems like it's out of scope for the project, but feel free to correct me if I'm wrong

**Comment by thomasrea0113** [comment]
> This seems like it's out of scope for the project, but feel free to correct me if I'm wrong

how would this be outside the scope of the project? Admittedly I know very little about the implementation, but the error indicates that the selector cannot be transformed to not use the :is() selector. seems pretty clear that it's an issue with one of the component classes. I'm wondering how this doesn't affect every build? I thought maybe specifying a browserlist that requires the latest version would resolve it, but it doesn't. Is there a way to disable the postcss-is-pseudo-class plugin altogether? I don't plan to support older browsers anyway.

**Comment by dimaslanjaka** [comment]
ahhhhhhh still not work after update

![image](https://github.com/themesberg/flowbite-react/assets/12471057/2b44a5b7-1aca-4dae-b1c6-76acafb49597)

**Comment by dimaslanjaka** [comment]
please correct my config project https://github.com/dimaslanjaka/webpack-boilerplate/tree/spring-fe

why this error still occurs!!!!!!

**Comment by dimaslanjaka** [comment]
when using below version, is working.

```json
{
    "flowbite": "^2.2.1",
    "flowbite-react": "^0.5.0"
}
```

![image](https://github.com/themesberg/flowbite-react/assets/12471057/5fecef47-b1c4-4b86-a424-6ef87f56e0f2)
![image](https://github.com/themesberg/flowbite-react/assets/12471057/15b94f79-8f69-49b7-a6fe-8ab141c40a60)

**Comment by dimaslanjaka** [comment]
so i just update other dependencies except `flowbite-react` to get the project working https://github.com/dimaslanjaka/webpack-boilerplate/commit/9c7aedc261940ec28c81eabbd868bcc28fc9aaf3

help wanted

**Comment by dimaslanjaka** [comment]
> @ishigami @dimaslanjaka I have no idea what happens here, but... try to update to `@beta` and check if it still happening.

not work

![image](https://github.com/themesberg/flowbite-react/assets/12471057/d0ec2938-9ca9-4670-bf38-867782c14631)
