### ISSUE TITLE
how to pass classNames in TextInput component to the input element rather than wrapping div

### ISSUE THREAD

**Issue by git-hubber** [themesberg/flowbite-react#1082]
Is it possible to pass className props to the actual input that is within TextInput?

It would be easy if I was using css, then could target the input such as:
`
input {
    color: red;
}
`

but using Tailwind this approach isn't possible (that I know of).

thanks

**Comment by geekyarjun** [comment]
@git-hubber is asking a way to pass className directly to the input component in <TextInput /> component. Right now if we pass className to TextInput it goes to a wrapper div of input element. I know we can query input element by [&_input]. But there are some scenarios where class precedence is an hinderance. Hope you understand.

**Comment by geekyarjun** [comment]
Thanks @SutuSebastian 
This worked for me when I put ! mark infront of text-red-700.
