### ISSUE TITLE
Datepicker not respecting custom input theme

### ISSUE THREAD

**Issue by tobysimone** [themesberg/flowbite-react#1087]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Use this custom datepicker theme:
```
const theme = {
  root: {
    input: {
      field: {
        input: {
          base: 'bg-inherit'
        }
      }
    }
  }
}

```

2. Pass the theme to a `Datepicker` component:
```<Datepicker theme={theme} />```
3. See that the background color of the input has not changed

## Current behavior

The Datepicker component does not seem to be handling values for the "base input" custom theme properly. I can change other parts of the Datepicker theme, just not the input.

## Expected behavior

The Datepicker input should be theme-able.

## Context

I'm trying to change the Datepicker's input background color to "inherit" to make the input transparent. It seems like creating a custom theme object for the Datepicker is the only way to change the background color.

**Comment by akmalnatha** [comment]
What did you do to solve this issue, I'm currently facing a challenge to apply "rounded-full" to the input base
