### ISSUE TITLE
`Carousel` scroll snap does not change slides on Firefox

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#110]
**Describe the bug**
On Firefox, dragging a `Carousel` left or right does not "snap" the `Carousel` to the next (dragging left) or previous (dragging right) slide. Instead, you partially scroll however far you dragged.

**To Reproduce**
1. Create a `Carousel` with at least two images
2. Attempt to drag horizontally to change slides on Firefox

**Expected behavior**
`Carousel`s should "snap" when dragged to ease user experience, which is implemented correctly in Chromium-based browsers.

**Screenshots**
![Screenshot 2022-05-12 at 08-43-26 Webpack App](https://user-images.githubusercontent.com/96850726/168031678-463de74e-d837-4cb0-819a-c3e782b4f45d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 100

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by tulup-conner** [comment]
I've also noticed that Carousels move vertically when you drag on mobile, if your drag isn't perfectly horizontal, which is a weird user experience. Movement in the Y plane should be ignored.

**Comment by julianYaman** [comment]
I also encountered this bug on Safari. Cannot use the control buttons, but dragging to left and right worked. Using next.js as my web framework.

**Comment by rluders** [comment]
@julianYaman I guess that we can keep in the same one. I don't have Safari to test it, so... probably someone else will have to test it.

**Comment by julianYaman** [comment]
@rluders Alright. Also noticed that the slideInterval didn't work as well. Only dragging atm.

**Comment by tulup-conner** [comment]
Ill test that and update this

**Comment by tulup-conner** [comment]
Hmm... For me, macOS Safari only has one bug, which is that transitions are instant. I can operate the carousels using any of the controls, including scroll snapping.

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
