### ISSUE TITLE
Button color not change in hover state

### ISSUE THREAD

**Issue by anggaratriputra** [themesberg/flowbite-react#1105]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Create button component, and add a bg color and hover : bg color using className of tailwind CSS
`  <Button className="w-full bg-[#40403F] hover:bg-red-600" size="lg" type="submit">
                  Login
  </Button>`
  
  
## Current behavior
When hovered, color change to default hover color of Button components

## Expected behavior
When hovered, color change to defined color in hover: state (bg-red-600)

Normal state :
![image](https://github.com/themesberg/flowbite-react/assets/139851266/e5b5c237-7f0a-43ea-aca2-fd6fd3c044c9)

Hover state :
![image](https://github.com/themesberg/flowbite-react/assets/139851266/61fd44e2-d6ee-43f7-ae1e-eb1faa9076cf)

**Comment by paghar** [comment]
You need to use `enabled:hover:bg-red-600`
