### ISSUE TITLE
Arrow isn't being changed between dark/light modes

### ISSUE THREAD

**Issue by PadowYT2** [themesberg/flowbite-react#1106]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Use the Select Input element
2. Use a darkmode switcher
3. See result

## Current behavior

The arrow is dark between dark/light modes
![https://cdn.padow.ru/xsgoG](https://cdn.padow.ru/xsgoG)
![https://cdn.padow.ru/ZLkWf](https://cdn.padow.ru/ZLkWf)

![https://cdn.padow.ru/ifY2I](https://cdn.padow.ru/ifY2I)

## Expected behavior

Probably the arrow should be probably changed between modes?

**Comment by paghar** [comment]
@PadowYT2 It seems to work fine here, [select-input](https://www.flowbite-react.com/docs/components/forms#select-input)
could you provide more details on how did you call this component?
