### ISSUE TITLE
Why Cannot add Chart as am as in flowbite chart

### ISSUE THREAD

**Issue by aazzizzz1** [themesberg/flowbite-react#1114]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Summary

Describe how it should work, and provide examples of the solution, which might include screenshots or code snippets.

## Context

What are you trying to accomplish? How is your use case affected by not having this feature?

**Comment by MateoWartelle** [comment]
Can you share a minimal example of what is not working?

**Comment by rluders** [comment]
I'm pretty sure that using [Flowbite Charts](https://flowbite.com/docs/plugins/charts/) with React isn't possible, and we don't have any alternative/implementation at the library right now.

Closing, this is not related to this repository.
