### ISSUE TITLE
Accordion.js:24 Uncaught TypeError: Cannot set properties of undefined (setting 'displayName')     at Accordion.js:24:16

### ISSUE THREAD

**Issue by djdicesare** [themesberg/flowbite-react#1119]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

Just start lol.

## Current behavior

Completely breaks code. I tried to us Accordion then got this error. Removed from code and now won't go away.

## Context

Use the Accordion

**Comment by SutuSebastian** [comment]
What version of `flowbite-react` are u using?

**Comment by SutuSebastian** [comment]
Also, whats the environment u're running? eg: Vite/CRA/Next.js page router/Next.js app router (client or server component) 🤔

**Comment by SutuSebastian** [comment]
Note: Next.js 13 with RSC (React Server Components) support is present in [0.7.0-beta.5](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.5) beta version.

**Comment by rluders** [comment]
@djdicesare friendly ping to ask you to help us to help you. :)
