### ISSUE TITLE
v0.7.0-beta.5 accidently include sharp as dependency.

### ISSUE THREAD

**Issue by BanDroid** [themesberg/flowbite-react#1139]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. install 0.7.0-beta.5

## Current behavior

sharp is not working in termux without using proot or root privileges.

## Expected behavior

install flowbite-react just fine.

## Context

[this](https://github.com/themesberg/flowbite-react/commit/5bea2105d23fa5be378160a0783ff036fbb00315#r133029076) is the context.

**Comment by rluders** [comment]
The suggestion here is to remove it as a dependency and add it during the vercel deployment since it is only used to optimize the documentation.

**Comment by SutuSebastian** [comment]
> The suggestion here is to remove it as a dependency and add it during the vercel deployment since it is only used to optimize the documentation.

I agree that we need to fix this, but could be a bit tedious to do and maintain, I think we should consider splitting the website and the library into separate packages

**Comment by BanDroid** [comment]
found a temporary solution, only work using pnpm, i dont know if other package manager support this settings in package.json.

```json
"pnpm": {
 "neverBuiltDependencies": ["sharp"]
},
```

this will ignore running postinstall and build for sharp, because sharp is not needed in the dependency itself.

i will not close this issue yet because the temporary solution is not a full fix for this.

**Comment by SutuSebastian** [comment]
Fixed in #1264
