### ISSUE TITLE
DarkThemeToggle component don’t support custom component icon

### ISSUE THREAD

**Issue by oscles** [themesberg/flowbite-react#1143]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary

It would be nice if the ***DarkThemeToggle*** component could receive custom icon components and not just a string for the icon since when using typescript the linter throws an error because the props don't satisfy the interface.

![image](https://github.com/themesberg/flowbite-react/assets/32989503/258e9c8a-fa4a-4ef6-b88e-9e8e155a2a96)

![image](https://github.com/themesberg/flowbite-react/assets/32989503/67f0b076-4c65-4478-a162-bad6d959a5d6)

## Solution

A possible solution could be the following:
![image](https://github.com/themesberg/flowbite-react/assets/32989503/9265015c-f492-4f0e-9134-741658a30c4a)

**Comment by SutuSebastian** [comment]
It seems like the `string` type was wrong in the first place.

This needs fixing, thanks for reporting it! 🔥

**Comment by SutuSebastian** [comment]
Also, u can create ur own dark theme component using the exposed `useThemeMode()` function, which `DarkThemeToggle` component uses under the hood.

**Comment by oscles** [comment]
Did they release a new version of the library to fix the bug?

**Comment by SutuSebastian** [comment]
V0.7.0 is coming soon, containing this fix as well.
