### ISSUE TITLE
Module '"flowbite-react"' has no exported member 'ThemeModeScript'.ts

### ISSUE THREAD

**Issue by oscles** [themesberg/flowbite-react#1149]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Current behavior

![image](https://github.com/themesberg/flowbite-react/assets/32989503/1d0a115c-52f6-4f2d-ac7f-e7a5c0d5f9dc)

## Expected behavior
Go to https://www.flowbite-react.com/docs/customize/dark-mode#nextjs

![image](https://github.com/themesberg/flowbite-react/assets/32989503/19e6cdea-eb8f-4515-9dc9-2a00235f770a)

**Comment by rluders** [comment]
@oscles are you using the `0.7.0`?
