### ISSUE TITLE
Docs: pagination component issue on documentation page

### ISSUE THREAD

**Issue by jonnyruffles** [themesberg/flowbite-react#1150]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to [this page](https://www.flowbite-react.com/docs/components/pagination#table-data-navigation).
2. Click on the 'Next' button
3. Notice how the page ranges stay the same

## Current behavior

https://github.com/themesberg/flowbite-react/assets/136707592/d00c55d4-a5ac-48ba-8efc-15756ae1a2d2

## Expected behavior

It should go to the next page range (2 to 6)

## Context
Video is recorded using Microsoft Edge, but assuming it wont matter

**Comment by rajatpandey441** [comment]
Hey. Can I work on this issue?

**Comment by rluders** [comment]
@rajatpandey441 don't need to ask, just go ahead and create the PR. :)

**Comment by rajatpandey441** [comment]
https://github.com/themesberg/flowbite-react/assets/20161529/06dcc018-52df-4e45-823d-3dce27f2411d

Please note that functionality is working correctly
