### ISSUE TITLE
Wrong tailwind.config.ts On Instruction for NextJS!

### ISSUE THREAD

**Issue by alvindera97** [themesberg/flowbite-react#1158]
https://github.com/themesberg/flowbite-react/blob/c51552a2e63e3f2709b0ee8aef5f7cedc3234941/content/docs/getting-started/nextjs.mdx#L37C16-L37C16

Please update to:
  `content: ['./node_modules/flowbite-react/lib/**/*.js', './pages/**/*.{ts,tsx}', './public/**/*.html'],`
  
  as that's the only thing that worked and made my nextjs project compile (nextjs 14.0.03).
  
 
I noticed that the starter project had a different value for content:

https://github.com/tulupinc/flowbite-next-starter/blob/7ce8ac533bc2910512d6a9dbefc30701c93ea43b/tailwind.config.ts#L5

**Comment by tulup-conner** [comment]
Thanks for catching this - do you have the time to make a PR for this? Would be very helpful. Thank you!

**Comment by chocoscoding** [comment]
I could do one, just assign me to it.🙇‍♂️

**Comment by tulup-conner** [comment]
@chocoscoding I'm not sure why people assume otherwise, but you are always welcome to work on any issue without needing to be assigned. PRs are always welcome

**Comment by chocoscoding** [comment]
> @chocoscoding I'm not sure why people assume otherwise, but you are always welcome to work on any issue without needing to be assigned. PRs are always welcome

thanks for the clarification

**Comment by chocoscoding** [comment]
Its the main tailwind config that needs to be updated and not the docs right?

Also, can content be :
`content: ['./node_modules/flowbite-react/lib/**/*.js', './pages/**/*.{ts,tsx}', './public/**/*.html', "./app/**/*.{ts,tsx}"],`

so it works for both app and src directory

**Comment by chocoscoding** [comment]
@tulup-conner i would like a response
