### ISSUE TITLE
`<Checkbox>` doesn't have outline in dark mode

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#1159]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Create any `<Checkbox />`
2. Switch to dark mode
3. Click on it

## Current behavior

The checkbox is surrounded by a thick layer of blue.

## Expected behavior

There should be a small (~2px) gap between the edge of the checkbox itself and the blue border around it. I believe the box model term for this space is the outline.

## Context

Reproducible in the live docs: https://www.flowbite-react.com/docs/components/forms#checkbox
Correct behavior: https://flowbite.com/docs/forms/checkbox/#checkbox-example

**Comment by gramzanali-scottlogic** [comment]
Hi, I'm looking to make a first contribution to an open source project. Can I have a go at fixing this issue?

**Comment by mud1tx** [comment]
@tulup-conner I can give this issue a try. Can you please assign it to me.

**Comment by mud1tx** [comment]
@tulup-conner earlier it looks like this
![Screenshot from 2023-12-01 11-34-25](https://github.com/themesberg/flowbite-react/assets/89539376/80008a61-e42f-403d-bd05-508ec220473e)

now it is looking like this
![Screenshot from 2023-12-01 11-32-57](https://github.com/themesberg/flowbite-react/assets/89539376/c2ceab4c-8d10-402e-8048-f52d28eae018)

is this works or I have to do some changes?

**Comment by tulup-conner** [comment]
That looks right at first glance! You should check out the official vanilla Flowbite library docs to check that anything you're working on. For Checkboxes, that's https://flowbite.com/docs/forms/checkbox/#checkbox-example
