### ISSUE TITLE
Add `Edit` and `Delete` buttons to Avatar component

### ISSUE THREAD

**Issue by Gauravdarkslayer** [themesberg/flowbite-react#1175]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary
Currently we have avatar component which does the great job but implementing an `edit` & `delete` button along with it would be better.
Example screenshot:
![image](https://github.com/themesberg/flowbite-react/assets/18503497/7692445f-e0ce-4d8a-9222-24fd5927baec)

## Context
Most of the times people add profile avatars while editing their user's profile, so we can extend the use of this component further to provide `edit` & `delete` icons with buttons so that user can trigger their method accordingly.

**Comment by rluders** [comment]
@Gauravdarkslayer do you mind to point where in standard flowbite library this component is present?

**Comment by Gauravdarkslayer** [comment]
Sure @rluders , here it is

General version:
https://flowbite.com/docs/components/avatar/

React version: https://www.flowbite-react.com/docs/components/avatar

**Comment by rluders** [comment]
I would say that this is a no. The standard library doesn't support the requested behavior by default, you can use the `Avatar` component to build a second component that fits your needs.
