### ISSUE TITLE
sidebar  bgcolor not change with class name 

### ISSUE THREAD

**Issue by nishant-vagh** [themesberg/flowbite-react#1179]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported)
- [x] I have tested the latest version

```jsx
<Sidebar collapsed={isCollapsed} className="bg-gray-400" >
    <Sidebar.Items className="bg-gray-400">
        <Sidebar.ItemGroup>
            <Sidebar.Item className="" href="#" icon={HiChartPie}  onClick={() => {toggleCollapse()}}>
                 Dashboard
            </Sidebar.Item>
            <Sidebar.Item href="#" icon={HiViewBoards} >
                Kanban
            </Sidebar.Item>
            <Sidebar.Item href="#" icon={HiInbox} >
                Inbox
            </Sidebar.Item>
            <Sidebar.Item href="#" icon={HiUser}>
                Users
            </Sidebar.Item>
            <Sidebar.Item href="#" icon={HiShoppingBag}>
                Products
            </Sidebar.Item>
            <Sidebar.Item href="#" icon={HiArrowSmRight}>
                Sign In
            </Sidebar.Item>
            <Sidebar.Item href="#" icon={HiTable}>
                Sign Up
            </Sidebar.Item>
        </Sidebar.ItemGroup>
    </Sidebar.Items>
</Sidebar>
```

## Current behavior
![Screenshot (205)](https://github.com/themesberg/flowbite-react/assets/145543380/8a908d7b-ecda-438e-bc24-19bc2ea2be37)

Describe what is currently happening and why it's a problem.

## Expected behavior
color set in side bar
![Screenshot (206)](https://github.com/themesberg/flowbite-react/assets/145543380/f499221c-9625-49ee-8f60-a56ec18a94a9)
expected

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by tulup-conner** [comment]
Have you checked whether the CSS `bg-gray-400` is applied using developer tools? Share your `tailwind.config.js` - my guess is you are missing step 2 of the install guide https://github.com/themesberg/flowbite-react#install-flowbite-react

**Comment by nishant-vagh** [comment]
> Have you checked whether the CSS `bg-gray-400` is applied using developer tools? Share your `tailwind.config.js` - my guess is you are missing step 2 of the install guide https://github.com/themesberg/flowbite-react#install-flowbite-react

 install properly   apply but not chage background color becuase defult color not remove

**Comment by rluders** [comment]
@nishant-vagh The best approach to customize complex elements such as `Sidebar` is to use the theme system. Some of the classes/styles that you are trying to change are part of the inner component's objects.

**Comment by nishant-vagh** [comment]
> @nishant-vagh The best approach to customize complex elements such as `Sidebar` is to use the theme system. Some of the classes/styles that you are trying to change are part of the inner component's objects.

![Screenshot (211)](https://github.com/themesberg/flowbite-react/assets/145543380/22434ac9-0c91-4be3-9efe-07ef66c5ed54)
![image](https://github.com/themesberg/flowbite-react/assets/145543380/8d3c020e-e7a6-4650-807c-af0323871668)
<Sidebar color="blue" collapsed={isCollapsed} className="bg-blue-500 h-[91.8vh]"  >
                    <Sidebar.Items className="bg-blue-500">
                        <Sidebar.ItemGroup className="bg-blue-500" >
                            <Sidebar.Item className="bg-blue-500" href="#" icon={HiChartPie}  onClick={() => {toggleCollapse()}}>
                                 Dashboard
                            </Sidebar.Item>
                            <Sidebar.Item href="#" icon={HiViewBoards} >
                                Kanban
                            </Sidebar.Item>
                            <Sidebar.Item href="#" icon={HiInbox} >
                                Inbox
                            </Sidebar.Item>
                            <Sidebar.Item href="#" icon={HiUser}>
                                Users
                            </Sidebar.Item>
                            <Sidebar.Item href="#" icon={HiShoppingBag}>
                                Products
                            </Sidebar.Item>
                            <Sidebar.Item href="#" icon={HiArrowSmRight}>
                                Sign In
                            </Sidebar.Item>
                            <Sidebar.Item href="#" icon={HiTable}>
                                Sign Up
                            </Sidebar.Item>
                        </Sidebar.ItemGroup>
                    </Sidebar.Items>
                </Sidebar>

**Comment by nishant-vagh** [comment]
> @nishant-vagh The best approach to customize complex elements such as `Sidebar` is to use the theme system. Some of the classes/styles that you are trying to change are part of the inner component's objects.

i have also try but

> @nishant-vagh The best approach to customize complex elements such as `Sidebar` is to use the theme system. Some of the classes/styles that you are trying to change are part of the inner component's objects.

![Screenshot (211)](https://github.com/themesberg/flowbite-react/assets/145543380/d4f1e2e0-25eb-4b67-a61e-e78b88d733fe)
![Screenshot (212)](https://github.com/themesberg/flowbite-react/assets/145543380/3feb8a98-1a67-4687-b195-5de708ec3874)

**Comment by rluders** [comment]
Have you tried to use this approach? https://www.flowbite-react.com/docs/customize/theme

**Comment by nishant-vagh** [comment]
> Have you tried to use this approach? https://www.flowbite-react.com/docs/customize/theme#option-3-create-a-reusable-component-with-a-custom-theme

yes i have try it 
but  still not  work

**Comment by rluders** [comment]
@nishant-vagh could you please create an example at codesandbox so someone can investigate the issue?

**Comment by nishant-vagh** [comment]
> @nishant-vagh could you please create an example at codesandbox so someone can investigate the issue?

`https://github.com/niks200/sandbox.git`

**Comment by tulup-conner** [comment]
Your sandbox isn't accessible. Let me know if you can still reproduce this.

**Comment by nishant-vagh** [comment]
> Your sandbox isn't accessible. Let me know if you can still reproduce this.
https://codesandbox.io/p/github/niks200/sandbox/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq3mq1yf0008356irzjfqcu5%2522%252C%2522sizes%2522%253A%255B70.63979525302304%252C29.36020474697696%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq3mq1yf0002356igfb08ozs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq3mq1yf0005356ivg6vf1w5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq3mq1yf0007356ifd1eg1wx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq3mq1yf0002356igfb08ozs%2522%253A%257B%2522id%2522%253A%2522clq3mq1yf0002356igfb08ozs%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq3mq1yf0007356ifd1eg1wx%2522%253A%257B%2522id%2522%253A%2522clq3mq1yf0007356ifd1eg1wx%2522%252C%2522activeTabId%2522%253A%2522clqw6wi89004e356i54rpzd35%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3mq1yf0006356ix3898s3s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clqw6wi89004e356i54rpzd35%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clq3mq1yf0005356ivg6vf1w5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3mq1yf0003356ijb7ngadz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clq3mq1yf0004356iwn5nm0ee%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq3lnf7o0012egfuhdjp3epd%2522%257D%255D%252C%2522id%2522%253A%2522clq3mq1yf0005356ivg6vf1w5%2522%252C%2522activeTabId%2522%253A%2522clq3mq1yf0003356ijb7ngadz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by tulup-conner** [comment]
It looks like all you need to do is apply the color to the `root.inner` theme specifically, since a `bg-gray-50` is currently supplied there.

That looks like:

```js
import { Sidebar, theme } from 'flowbite-react';
import { twMerge } from 'tailwind-merge';

<Sidebar theme={{
  inner: twMerge(theme.sidebar.root.inner, "bg-pink-800")
}}>
 ..
</Sidebar>
```

This obviously isn't optimal - we should definitely consider moving all or most of the styling out of this `inner` key to make it more intuitive. E.g., you should be able to just do this with `className` without hacks. You can actually do it with `className` as well by specifying the inner `<div>` as the target - e.g., `<Sidebar className="[&>div]:bg-pink-800">`

I tested on your Code Sandbox and each of those works just fine.
