### ISSUE TITLE
Tooltip not works with Tabs

### ISSUE THREAD

**Issue by vitorLostadaC** [themesberg/flowbite-react#1186]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

![image](https://github.com/themesberg/flowbite-react/assets/69974844/48417cb5-2f4c-4400-856b-8300ae3d4288)

## Current behavior

when I added the tooltipe on over the Tab.Item all content inside button disappear

![image](https://github.com/themesberg/flowbite-react/assets/69974844/762cea84-19e7-4232-9e71-d884438f128f)
![image](https://github.com/themesberg/flowbite-react/assets/69974844/811c8018-48bb-4413-88f1-c9467320fcdc)

## Expected behavior

Show Tooptip

**Comment by tulup-conner** [comment]
Hi there, `<Tabs.Item title={..}>` accepts any `ReactNode`, which means you can insert a `<Tooltip>` component and use the theme to adjust its target style so that it looks like a normal tab button, but has tooltip behavior.
