### ISSUE TITLE
Datepicker only changes on manual click.

### ISSUE THREAD

**Issue by ddiasfront** [themesberg/flowbite-react#1187]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary
Datepicker can't be updated without a click function.

## Context
This issue was found in a scenario where I needed to update the selectedDate without clicking into the component, just by passing a value to the Datepicker, and actually it just accepts changes by clicking which I don't believe covers the use cases.

**Comment by ddiasfront** [comment]
@rluders I'm submitting a PR for that.

**Comment by rluders** [comment]
@ddiasfront thanks. I'll check it ASAP (valeu, jovem)
