### ISSUE TITLE
TimelineContent is not taking theme styles when being in vertical mode

### ISSUE THREAD

**Issue by trocoli96** [themesberg/flowbite-react#1196]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Use the Timeline.Content component and configuring the theme to change the styling
2. The style is applied only when horizontal prop is "true"

## Current behavior

Currently, the Timeline.Content component, when passing the styles from the theme, is not taking properly the styles because they are only applied in horizontal.
<img width="883" alt="image" src="https://github.com/themesberg/flowbite-react/assets/28953515/d3cd59f3-ead8-499f-b4ba-c576aa365c40">

Example: 
This is an example of the same theme used on horizontal and in vertical

This is my theme object
<img width="1293" alt="image" src="https://github.com/themesberg/flowbite-react/assets/28953515/fda7f5fe-44df-4c88-901f-4a74361c5466">

Horizontal:
<img width="493" alt="image" src="https://github.com/themesberg/flowbite-react/assets/28953515/8369ab69-a9c3-4cc1-bd93-e73cbff8d03e">

Vertical:
<img width="250" alt="Captura de pantalla 2023-12-21 a las 17 09 45" src="https://github.com/themesberg/flowbite-react/assets/28953515/000e7e76-84a9-43b6-8896-f286ce12a9b1">

As you can see, the border from the box is only applied when horizontal prop is true

## Expected behavior

Both horizontal and vertical options apply the root base from content

## Context

Right now, when using the Timeline component, you can add a child which is Timeline.Content which is basically the content inside each item, but this is only letting change the style when using it in horizontal.

**Comment by victorfunes** [comment]
Just to add information: we are using the <Flowbite theme={}> and not setting the theme in the component itself.

**Comment by tulup-conner** [comment]
Thank you, that makes sense. 

If anyone has time, we need to always include `base` theme in `<Timeline>` and add new props to the theme outside base called `horizontal->on/off`, or maybe just `horizontal/vertical`. Pull out the CSS from `base` that changes the orientation between the two.

**Comment by SutuSebastian** [comment]
Fixed in [flowbite-react@0.10.0](https://github.com/themesberg/flowbite-react/releases/tag/flowbite-react%400.10.0) release.
