### ISSUE TITLE
Build Timeline component

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#12]
Reference: https://flowbite.com/docs/components/timeline/

**Comment by joeychrys** [comment]
I can start this.
I'll structure it like:
`<Timeline>
	<Timeline.item>
		{content}
	<Timeline.Item>
</Timeline>`

**Comment by rluders** [comment]
@joeychrys do you still interested in working on this one?

**Comment by joeychrys** [comment]
> @joeychrys do you still interested in working on this one?

Hey, sorry. I probably can't get to it until Thursday next week. If this is holding you guys back, then by all means go ahead without me. I will have all the time in the world in like a week because I'll be done with school.

**Comment by tulup-conner** [comment]
This can be closed now
