### ISSUE TITLE
Navbar.Brand does not exist 

### ISSUE THREAD

**Issue by mkbctrl** [themesberg/flowbite-react#1208]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

```
Error: Could not find the module "node_modules/flowbite-react/lib/esm/components/Navbar/Navbar.js#Navbar#Brand" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```

## Steps to reproduce

```
import { Navbar } from 'flowbite-react'
import { useTranslations } from 'next-intl'
import { Path } from 'src/constants/path'
import { Logo } from 'src/ui/logo/logo'

export const PublicHeader = () => {
  const t = useTranslations('PublicLayout.nav')
  return (
    <Navbar>
      <Navbar.Brand>
        <Logo />
      </Navbar.Brand>
      <Navbar.Toggle />
      <Navbar.Collapse>
        <Navbar.Link href={Path.AuthRegister}>{t('create-account')}</Navbar.Link>
        <Navbar.Link href={Path.AuthLogin}>{t('access-account')}</Navbar.Link>
      </Navbar.Collapse>
    </Navbar>
  )
}

```

## Current behavior

Imported docs navbar example and it fails to work

## Expected behavior

To work

## Context
Next.js 14

**Comment by mkbctrl** [comment]
Actually all elements are behaving like that.
Importing directly: `import { Navbar, NavbarBrand, NavbarCollapse, NavbarLink, NavbarToggle } from 'flowbite-react'` solves the issue

**Comment by tulup-conner** [comment]
This is a documented factor of Next.js RSC compatibility. See the `server.tsx` variant of the code example: https://www.flowbite-react.com/docs/components/navbar#default-navbar
