### ISSUE TITLE
Datepicker onChange not working

### ISSUE THREAD

**Issue by yzidanNqood** [themesberg/flowbite-react#1209]
After following this docs:https://www.flowbite-react.com/docs/components/datepicker

the `onChange` is not working at all.

```jsx
import { Datepicker } from 'flowbite-react';

<Datepicker
        onChange={(val) => {
          console.log(val);
        }}
/>
```

**Comment by tulup-conner** [comment]
Hey there! You need to use `<Datepicker onSelectedDateChange>` instead. That's not your fault - it isn't documented there right now, and we have already recognized that this is a common point of confusion for users. It will more than likely be possible to use `onChange` soon.

**Comment by markieboy223** [comment]
hey there, i'm using version 0.10.1 of flowbite-react, has this been updated yet? i cannot use onSelectedDateChange either.

**Comment by SutuSebastian** [comment]
> hey there, i'm using version 0.10.1 of flowbite-react, has this been updated yet? i cannot use onSelectedDateChange either.

Try `onSelectedDateChanged`
