### ISSUE TITLE
Bug in decade date option

### ISSUE THREAD

**Issue by drokbers** [themesberg/flowbite-react#1211]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## ScreenShot

<img width="377" alt="image" src="https://github.com/themesberg/flowbite-react/assets/6474580/7d31c3e7-92e2-4790-be3d-7b5bd06b2dcf">

## Context

There is a bug in the UI when selecting the 10 years option when selecting the date

## package.json
    "flowbite": "^1.8.1",
    "flowbite-react": "^0.6.4",

**Comment by kharbandaashu** [comment]
@drokbers could you please add more info ?

**Comment by drokbers** [comment]
> @drokbers could you please add more info ?

I added package versions. Idk what to add more. Bug looks clear I believe

**Comment by teddythinh** [comment]
Hi guys, I also get a bug with decades option. After clicking on the decades' option, all of the options are disabled, even the buttons are disabled.

![image](https://github.com/themesberg/flowbite-react/assets/85171754/4e29cc66-b0ec-4414-8773-1daca9f5d6e9)

I tested it out on the React documentation page: https://flowbite-react.com/docs/components/datepicker#default-datepicker

![image](https://github.com/themesberg/flowbite-react/assets/85171754/94d9c4e6-db34-418a-bd9a-ce7d3286acf7)

When I tested it on the HTML documentation page, it worked: https://flowbite.com/docs/components/datepicker/#datepicker-example

# `package.json`

```json
"flowbite": "^2.4.1",
"flowbite-react": "^0.7.2",
```

**Comment by teddythinh** [comment]
Hi, I figured out this repository works on the Datepicker component: https://github.com/OMikkel/tailwind-datepicker-react

**Comment by Maraket** [comment]
I have just tested https://flowbite-react.com/docs/components/datepicker#default-datepicker with Chrome 126.0.6478.182 (Official Build) (arm64) and I can confirm when navigating to the DatePickers decade select:
- you can still use the left and right page navigation buttons
- When navigating to the other pages, it keeps the top right decade highlighted as if it's selected
- You cannot select any decade, though the hover behaviour appears to work
- Clicking `Clear` or `Today` shows a border around the button, but the popout doesn't change.

**Comment by Maraket** [comment]
The problem was pretty minor, and hopefully someone reviews and accepts my PR to fix this

**Comment by Maraket** [comment]
Full transparency, noticed a small bug where this bug still exists, this being if the date range is restricted to maxDate and minDate are within a decade (sort of). Missed this in my unit test :( but still relevant to this issue

**Comment by SutuSebastian** [comment]
> Full transparency, noticed a small bug where this bug still exists, this being if the date range is restricted to maxDate and minDate are within a decade (sort of). Missed this in my unit test :( but still relevant to this issue

Feel free to put up a fix for it
