### ISSUE TITLE
Issues with peer dependencies with NextJS 14.0.4

### ISSUE THREAD

**Issue by walterradduso** [themesberg/flowbite-react#1216]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Install `flowbite-react` (0.7.2) and `nextjs` (14.0.4).
2. The warning `Issues with peer dependencies found` appears.

## Current behavior

This Is not a problem, but it would be good if someone could update the `flowbite-react` dependencies to avoid the `unmet peer` dependency warning.

## Expected behavior

To not get the `unmet peer` dependency warning.

## Context

This is the terminal warning:
![unmet peer dependencies - flowbite-react](https://github.com/themesberg/flowbite-react/assets/4683824/d101b9d6-ccf6-4ff3-a94e-1daa50a99b10)

**Comment by tulup-conner** [comment]
We're aware of this but it isn't really pertinent to the library
