### ISSUE TITLE
Button text selectable

### ISSUE THREAD

**Issue by victorfunes** [themesberg/flowbite-react#1228]
- [ x ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ x ] I have tested the latest version

## Steps to reproduce

1. Create any button with text inside

## Current behavior

The text can be selected, but by default it shouldn't
<img width="189" alt="image" src="https://github.com/themesberg/flowbite-react/assets/108006690/d6eec8c7-fdab-4239-aa4a-2376da11d6fb">

## Expected behavior

By default the text should not be selectable in a button

**Comment by tulup-conner** [comment]
I don't experience this on https://www.flowbite-react.com/docs/components/button, can you provide an example?

**Comment by victorfunes** [comment]
In my case yes, it does the same:

<img width="1296" alt="image" src="https://github.com/themesberg/flowbite-react/assets/108006690/74b297e7-837d-4fa1-9834-dfa9d31282e8">

You need to click ouside of the button and drag the cursor over the button like if you wanted to select several buttons at the same time.

I think it would be solved if in the theme base you added select-none, but I haven't looked at it in detail

**Comment by tulup-conner** [comment]
I can't reproduce that on Firefox but I can on Chromium-based browsers. However, that's the current behavior of the vanilla Flowbite library, so I don't think we have any need to take action here. I'm not sure I understand the motivation in the first place. Why shouldn't the text be selectable?
