### ISSUE TITLE
Flowbite js is not working on mobile devices

### ISSUE THREAD

**Issue by UnileadCZ** [themesberg/flowbite-react#1229]
- [y] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [y] I have tested the latest version

## Steps to reproduce

1. download the project on 'https://github.com/UnileadCZ/tenisclub'

## Current behavior

Everything work fine unless on mobile device and safari. Then you are on mobile device carousels don't work and also hamburger navbar don't pop up. I guess the js is not downloading. Exactly the same behaviour is on safari no matter if you are on mobile or pc.

## Expected behavior

Carousels and navbar to work on mobile devices. 

## Context

The project is live on this url https://tenisclub-mokropsy.web.app/ . Components that needs js don't work on safari browser pc/mobile and on mobile devices across all browsers.

**Comment by tulup-conner** [comment]
You aren't using flowbite-react at all... interactive behavior will not work with vanilla JS DOM manipulation in a React environment, which is why this library exists
