### ISSUE TITLE
Theme: Accordion component

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#125]
**Is your feature request related to a problem? Please describe.**

Improve the theme support to the component (and subcomponents).

**Describe the solution you'd like**
- All default styles must be moved to the default theme;

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tulup-conner** [comment]
@rluders Is this done or would you like me to do more? We could move the `flush` on/off classes to the theme as well.

**Comment by rluders** [comment]
@tulup-conner I think that still some things missing to be done. I just started this one as an example, didn't finished at all. The ideal scenario must have all style living on theme.

**Comment by tulup-conner** [comment]
Cool, in that case, I'll wrap it up
