### ISSUE TITLE
Popover listed in documentation but not available in current release (0.7.2)

### ISSUE THREAD

**Issue by cthacker-udel** [themesberg/flowbite-react#1258]
Popover component is listed in documentation : https://www.flowbite-react.com/docs/components/popover#default-popover
but is currently unavailable in current release.

**Comment by rluders** [comment]
Not a bug in the library. The documentation is always reflecting the develop version, we need to fix this release process to avoid this kind of confusion.

**Comment by cthacker-udel** [comment]
No problem! Listed it as a bug cause I didn't see it as a feature request, sorry about that. Thank you!
