### ISSUE TITLE
 The default background color of the modal does not appear

### ISSUE THREAD

**Issue by jotacollantes** [themesberg/flowbite-react#1267]
With version 0.7.2

![Captura de pantalla 2024-02-08 a la(s) 16 20 37](https://github.com/themesberg/flowbite-react/assets/105930339/d954922f-ec99-4187-8887-0198f7ca602d)

This worked until version 0.6.4

![Captura de pantalla 2024-02-08 a la(s) 16 23 21](https://github.com/themesberg/flowbite-react/assets/105930339/ad40bc7f-136b-4841-a101-a7b8c925e9db)

When deploying in vercel the following message appears:
warning "flowbite-react > next-contentlayer@0.3.4" has incorrect peer dependency "next@^12 || ^13".

Regards

**Comment by SutuSebastian** [comment]
Tested on fresh Vite + React project => works.

The issue here might be ur custom theme override in the `<Flowbite theme={{ theme: customTheme }}>` component, because a lot of things changed from version 0.6.x to 0.7.x, including the theme keys of the components.

I suggest u remove the custom theme, and test again.

Here's a functional `flowbite-react + vite` example:

https://stackblitz.com/edit/vitejs-vite-n3kwrs

**Comment by SutuSebastian** [comment]
Sure, here's a Next.js fresh project with latest versions for all packages and a demo with the `flowbite-react` modal component. It works.

https://stackblitz.com/edit/stackblitz-starters-teolxc

**Comment by jotacollantes** [comment]
I already found the error, what happens is that when I sign in I show a modal in a component that does use the custom theme (is the only that use custom theme) because what I want is that only at the time of authentication the modal is shown and spinner  without the background color. But apparently the rest of the modals that are in different components and that are used in other routes (pages) inherit the custom theme.


![Captura de pantalla 2024-02-09 a la(s) 12 00 46](https://github.com/themesberg/flowbite-react/assets/105930339/a244f97f-fff0-472d-8c3b-7906955340cc)

 I share with you the code I use to customize the modal at the time of sign in.
https://gist.github.com/jotacollantes/ee0c892191ea3202ffa99049d1c5def3


Now that I remember between upgrade versions, more than once I have had to modify this custom theme. Apparently the theme keys changes when new versions are released.

Thank you very much for your help

**Comment by SutuSebastian** [comment]
> Tested on fresh Vite + React project => works.
> 
> The issue here might be ur custom theme override in the `<Flowbite theme={{ theme: customTheme }}>` component, because a lot of things changed from version 0.6.x to 0.7.x, including the theme keys of the components.
> 
> I suggest u remove the custom theme, and test again.
> 
> Here's a functional `flowbite-react + vite` example:
> 
> https://stackblitz.com/edit/vitejs-vite-n3kwrs

Glad u found the problem, just like I suggested here 😄
