### ISSUE TITLE
Flowbite styles in storybook

### ISSUE THREAD

**Issue by getblad** [themesberg/flowbite-react#1293]
I have nx/next application with storybook in shared library. How can I configure flowbite, so that I could see it's styles in my storybook? Right now styles are not applied to the component.

**Comment by getblad** [comment]
Nextjs application in ./apps/app_name folder. React shared library in ./libs/library_name folder, in the same folder I Installed storybook, so that I run storybook only for this specific library

**Comment by getblad** [comment]
storybook was installed using nx generate nx/next:storybook-configuration command. I assume that it uses vite as this is .storybook/main.ts
`
import type { StorybookConfig } from '@storybook/react-vite';

import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { mergeConfig } from 'vite';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: ['@storybook/addon-essentials'],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },

  viteFinal: async (config) =>
    mergeConfig(config, {
      plugins: [nxViteTsPaths()],
    }),
};

export default config;
`
I did everything you said, and it still doesnt work properly. styles is not applied to the storybook preview.

**Comment by getblad** [comment]
storybook was installed using nx generate nx/next:storybook-configuration command. I assume that it uses vite as this is .storybook/main.ts
```js
import type { StorybookConfig } from '@storybook/react-vite';

import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { mergeConfig } from 'vite';

const config: StorybookConfig = {
stories: ['../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
addons: ['@storybook/addon-essentials'],
framework: {
name: '@storybook/react-vite',
options: {},
},

viteFinal: async (config) =>
mergeConfig(config, {
plugins: [nxViteTsPaths()],
}),
};

export default config;
```
I did everything you said, and it still doesnt work properly. styles is not applied to the storybook preview.

**Comment by SutuSebastian** [comment]
I'll need to have to reproduce ur setup 1:1 locally in order to give more insights

**Comment by MiroslavPetrik** [comment]
I have one SB + flowbite running here https://github.com/form-atoms/flowbite/tree/main/.storybook
You might notice something off 

just 2 cents

**Comment by getblad** [comment]
I reinstalled storybook again using @nx/next generator and repeated your guide @SutuSebastian and everything seems to work now. Thank you everyone!

**Comment by SutuSebastian** [comment]
Wonderful! 🔥
