### ISSUE TITLE
Docs : Toggle Switch

### ISSUE THREAD

**Issue by MateoWartelle** [themesberg/flowbite-react#1321]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to https://www.flowbite-react.com/docs/components/forms#toggle-switch

## Current behaviour

Describe what is currently happening and why it's a problem.

<img width="1437" alt="toggleSwitch" src="https://github.com/themesberg/flowbite-react/assets/27743176/fb31a66c-ce41-4725-a069-4c3a6c39e733">

## Expected behaviour

Describe what you expected to happen.

<img width="97" alt="toggleSwitch-1" src="https://github.com/themesberg/flowbite-react/assets/27743176/469db6f0-5a15-494f-a081-4f18e7cddeba">

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by alfreddagenais** [comment]
I recently encountered an issue in my application and realized that there has been a change in the Flowbite-react template. To address this issue for now, I added a custom theme. This solution might help others facing similar problems.

```javascript
export const customThemeToggleSwitch: CustomFlowbiteTheme['toggleSwitch'] = {
    toggle: {
      base: "after:rounded-full rounded-full border group-focus:ring-4 group-focus:ring-cyan-500/25",
      checked: {
          on: "after:bg-white after:translate-x-full",
          off: "after:bg-gray-400 dark:after:bg-gray-500 border-gray-200 bg-gray-200 dark:border-gray-600 dark:bg-gray-700",
      },
    },
};
```

Additionally, I noticed that PR #1199 could potentially resolve this issue if integrated.

**Comment by akashMasih** [comment]
Working on this issue Docs : Toggle Switch #1321

**Comment by sarkaburanska** [comment]
HI, I am using the latest version and this bug is still there, same behavior, the fix with styling is not working cus now the thumb running out when on checked
![Screenshot 2024-12-02 at 10 28 30](https://github.com/user-attachments/assets/1b745ff3-4348-4638-ad9d-268f13f09913)

**Comment by SutuSebastian** [comment]
> HI, I am using the latest version and this bug is still there, same behavior, the fix with styling is not working cus now the thumb running out when on checked ![Screenshot 2024-12-02 at 10 28 30](https://private-user-images.githubusercontent.com/6403331/391485657-1b745ff3-4348-4638-ad9d-268f13f09913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzIwODMsIm5iZiI6MTczMzEzMTc4MywicGF0aCI6Ii82NDAzMzMxLzM5MTQ4NTY1Ny0xYjc0NWZmMy00MzQ4LTQ2MzgtYWQ5ZC0yNjhmMTNmMDk5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMDkyOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc4MDc3NzNiOWZkN2I2YzhmZmFmZmQwZDZjNzI5NTA2YjA3YTA2NmE5MDIxODhiMDY5YTY5OWRhOWZhZTg5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2olHFJ1u22YJCQMU9koDwIGq56F8FZUiJMncPeM2HjU)

Hey there, firstly make sure u are not overriding the `theme` in any way, both on global level (using `<Flowbite>` component) or local level by using the `theme` prop.
