### ISSUE TITLE
Remix Dev not running with flowbite-react 0.7.8

### ISSUE THREAD

**Issue by geraldyeo** [themesberg/flowbite-react#1343]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Upgrade from `0.7.5` to `0.7.8`
2. Run remix in dev

## Current behavior

remix dev fails to run, giving the following error

```
SyntaxError: Named export 'Badge' not found. The requested module 'flowbite-react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'flowbite-react';

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at file:///Users/gerald/Code/Jan/fs/apps/webapp/server.js:25:22
Failed running 'server.js'
```

## Expected behavior

remix dev to serve the app

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

Trying to greenkeep the app, but updating to latest `0.7.8` fails the remix dev.

Downgrading back to `0.7.5`, remix dev runs as normal.

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

![CleanShot 2024-04-02 at 14 04 20@2x](https://github.com/themesberg/flowbite-react/assets/73524/1ccbd635-9321-4b0b-b1be-a415d15ba519)

**Comment by SutuSebastian** [comment]
Is ur app using the new `vite` dev server or the classic remix one (`remix.config.js`)?

**Comment by geraldyeo** [comment]
It is the classic one, with an Express server (https://github.com/remix-run/remix/tree/main/templates/classic-remix-compiler/express)

**Comment by SutuSebastian** [comment]
Gotcha, I see where the problem is. Apparently `package.json` `exports` does not work the same as for `main` and `module` fields. `exports` field needs explicit `.cjs` or `.mjs` file extensions for the bundler/package manager to **know** how to import and treat the file, derp, why can't it work just like `main` and `module.

This might have to bring in a breaking change.
