### ISSUE TITLE
Flowbite setup with NX Monorepo

### ISSUE THREAD

**Issue by MuttakinHasib** [themesberg/flowbite-react#1355]
Hey @SutuSebastian 

I am trying to setup Flowbite with NextJs on Nx Monorepo, but it's not working. Can you please take a look?

Here is the codesandbox link: [nx-nextjs-flowbite](https://codesandbox.io/p/github/MuttakinHasib/nx-nextjs-flowbite/main?import=true)

**Comment by SutuSebastian** [comment]
According to version `0.8.0` changelog and breaking changes, u have to do the following:

1. correctly configure `tailwind.config.js` using the `flowbite-react/tailwind` proxy

<img width="2603" alt="Screenshot 2024-04-10 at 17 34 54" src="https://github.com/themesberg/flowbite-react/assets/41998826/fb27ae4d-e1cc-48fc-8938-ca2021ef8c04">

2. `flowbite` package can be removed (optional)

<img width="2603" alt="Screenshot 2024-04-10 at 17 34 52" src="https://github.com/themesberg/flowbite-react/assets/41998826/199879c1-0133-4596-b348-b62984d6f2bc">

**Comment by MuttakinHasib** [comment]
@SutuSebastian Do I need to pass the **base** to the plugin also?

`flowbite.plugin({ base: '../../' })`

**Comment by SutuSebastian** [comment]
> Need TS support here. it's not giving any suggestions.
> 
> btw, Thanks @SutuSebastian ❤️

TS support/ intellisense suggestions is only available within `*.mjs` or `.ts(x)` files, see below in a `tailwind.config.mjs` file:

<img width="743" alt="Screenshot 2024-04-10 at 17 54 21" src="https://github.com/themesberg/flowbite-react/assets/41998826/cbb5bc0f-bfdb-4936-86f6-3136aa3bfb7a">

<img width="530" alt="Screenshot 2024-04-10 at 17 54 35" src="https://github.com/themesberg/flowbite-react/assets/41998826/4dd64be1-c88c-46d3-bed2-9fbf02386da4">

<img width="596" alt="Screenshot 2024-04-10 at 17 54 48" src="https://github.com/themesberg/flowbite-react/assets/41998826/75efa314-9df3-4f0f-aca9-ad7337a5d7f4">

**Comment by MuttakinHasib** [comment]
@SutuSebastian Thanks :heart:
