### ISSUE TITLE
Some component (at least my spinner and button) are broken after upgrade to 0.9.0 and 0.8.0 from 0.7.3

### ISSUE THREAD

**Issue by alfi-dim** [themesberg/flowbite-react#1379]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Use [ncu](https://www.npmjs.com/package/npm-check-updates) to upgrade flowbite-react to latest from 0.7.3, and see my spinner and button is broken
2. Downgrade to 0.8.0 version, still broken
3. Downgrade to 0.7.3, it back to normal

## Current behavior
spinner
![image](https://github.com/themesberg/flowbite-react/assets/74103308/d92eb236-4ed9-451b-996c-9ab62aae28e8)

button
![image](https://github.com/themesberg/flowbite-react/assets/74103308/597a8bfb-27b4-4d6d-ad65-9ea42cbb4407)

## Expected behavior
spinner
![image](https://github.com/themesberg/flowbite-react/assets/74103308/6d6e0e3c-96d9-4c35-abdc-bde22f764da2)

button
![image](https://github.com/themesberg/flowbite-react/assets/74103308/35716d8b-0b33-4e2b-9d78-b5e2b419e248)

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by SutuSebastian** [comment]
Upgrading from `0.7.x` to `0.8/9.x` requires some changes in the tailwind config, please follow the release breaking changes guide:
[flowbite-react@0.8.0](https://github.com/themesberg/flowbite-react/releases/tag/flowbite-react%400.8.0)
