### ISSUE TITLE
Flowbite button does not have attribute download

### ISSUE THREAD

**Issue by Hann1bal** [themesberg/flowbite-react#1387]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Current behavior
```tsx
<Button href={'data:text/json;charset=utf-8,${encodeURIComponent(JSON.stringify(tasss))}'} color="gray" className="w-full mb-2" download={"filename.json"}>
 Download Json
 </Button>
```
I write button for downloading buffered data and it's working but i can't  compile. I got the error:

```
Type '{ children: string; href: string; color: string; className: string; download: string; }' is not assignable to type 'IntrinsicAttributes & { href?: string; color?: keyof FlowbiteColors; fullSized?: boolean; gradientDuoTone?: keyof ButtonGradientDuoToneColors; ... 10 more ...; theme?: { ...; }; } & AsProp<...> & { ...; } & Omit<...> & { ...; }'.
  Property 'download' does not exist on type 'IntrinsicAttributes & { href?: string; color?: keyof FlowbiteColors; fullSized?: boolean; gradientDuoTone?: keyof ButtonGradientDuoToneColors; ... 10 more ...; theme?: { ...; }; } & AsProp<...> & { ...; } & Omit<...> & { ...; }'. Did you mean 'onLoad'?ts(2322)
  ```
## Expected behavior

In default html button exist "download" attribute
.

**Comment by dhavalveera** [comment]
Hey @Hann1bal 

I just checked with default HTML Button with `download` attribute which didn't worked for me.. 

Here is an [Example](https://jsfiddle.net/vm170oyj/) which have the download attribute but when you click on button, it's not working at all.

the `download` attribute works on anchor tag, not on button.

**Comment by Hann1bal** [comment]
> Hey @Hann1bal 
> 
> I just checked with default HTML Button with `download` attribute which didn't worked for me.. 
> 
> Here is an [Example](https://jsfiddle.net/vm170oyj/) which have the download attribute but when you click on button, it's not working at all.
> 
> the `download` attribute works on anchor tag, not on button.

Do u use the blob or something else? In few hour I can share example.

**Comment by SutuSebastian** [comment]
This can be easily solved by casting the `Button` component as `"a"` or as `Link` component if using a framework such as [Next.js](https://nextjs.org/).

Before:
<img width="629" alt="Screenshot 2024-05-28 at 12 57 08" src="https://github.com/themesberg/flowbite-react/assets/41998826/60de5f2b-3724-4c4c-aad3-0e6208bfbe01">

After

`as="a"`
<img width="645" alt="Screenshot 2024-05-28 at 12 57 13" src="https://github.com/themesberg/flowbite-react/assets/41998826/71567ccc-8be0-4243-9a25-4bf0a8bf3801">

`as={Link}`
<img width="645" alt="Screenshot 2024-05-28 at 12 57 58" src="https://github.com/themesberg/flowbite-react/assets/41998826/63250da7-3fb9-43f6-be8e-a073eba23d1a">

**Comment by SutuSebastian** [comment]
Button itself does not have `download` attribute by nature, just like @dhavalveera mentioned earlier.

**Comment by Hann1bal** [comment]
> Button itself does not have `download` attribute by nature, just like @dhavalveera mentioned earlier.

Thank you. It's work.
