### ISSUE TITLE
Date Picker Auto Hide

### ISSUE THREAD

**Issue by dlopesa** [themesberg/flowbite-react#1390]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

```
<Datepicker
            autoHide={true}
            onSelectedDateChanged={(date) => {
              const localDate = new Date(
                date.getTime() - date.getTimezoneOffset() * 60000
              );
              const dateString = localDate.toISOString().split("T")[0];
              console.log(dateString); // Log the date string
              setDate(dateString);
            }}
            className="dark"
          />
```

## Current behavior

The auto hide does not work, even after selecting a date it does not disappear

## Expected behavior

After choosing a day it should disappear

## Context

Use a date picker

Video:
https://github.com/themesberg/flowbite-react/assets/39463084/b48cd144-9ad7-48c7-a9ac-495ad84225cf

**Comment by mmersiades** [comment]
I'm not sure if this will solve your problem, @dlopesa , but...

I had the same problem. I had the `<DatePicker/>` wrapped in a `<label/>`. Problem went away when I changed `<label/>` to `<div/>`.

FROM:

```
<label >
    <div >
        <span >
            {label}
          </span>
     </div>
     <Datepicker/>
</label>
```

TO:

```
<div >
    <div >
        <span >
            {label}
          </span>
     </div>
     <Datepicker/>
</div>
```

**Comment by dlopesa** [comment]
Thank you so much, I decided to move "https://react-tailwindcss-datepicker.vercel.app"
