### ISSUE TITLE
Module '"flowbite-react"' has no exported member 'Drawer'.

### ISSUE THREAD

**Issue by Kokoserver** [themesberg/flowbite-react#1392]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

the Drawer is not exported, this a blocker to me right now at my place of work

**Comment by SutuSebastian** [comment]
What version are u on?

**Comment by Kokoserver** [comment]
@SutuSebastian the current version i installed is:     "flowbite-react": "^0.9.0"

**Comment by jecorrales-dev** [comment]
I have the same error on the verison "flowbite-react": "^0.8.0"

**Comment by paulshaun-kdtk** [comment]
yep also got the issue today

**Comment by SutuSebastian** [comment]
> I have the same error in the version of **“flowbite-react”: “^0.8.0”**.

`Drawer` and `MegaMenu` were introduced in `v0.9.0`, u can check the release [here](https://github.com/themesberg/flowbite-react/releases/tag/flowbite-react%400.9.0).

**Comment by SutuSebastian** [comment]
> @SutuSebastian the current version i installed is: "flowbite-react": "^0.9.0"

I just tried reproducing this locally and there's no issues with version `0.9.0`
