### ISSUE TITLE
Tabs SSR not working

### ISSUE THREAD

**Issue by vitalijalbu** [themesberg/flowbite-react#1395]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Steps to reproduce

just create a nextjs +14 pro version and you'll see that it's not compatible yet...

## Current behavior

Describe what is currently happening and why it's a problem.

## Expected behavior

must work perfectly

## Context

![Screenshot 2024-05-16 alle 19 22 52](https://github.com/themesberg/flowbite-react/assets/40239902/a9be922f-8205-4f52-97e6-312cb53da24c)
<img width="903" alt="Screenshot 2024-05-16 alle 19 23 04" src="https://github.com/themesberg/flowbite-react/assets/40239902/965befbc-e2a6-4fdb-a12d-6a1133094f04">

**Comment by SutuSebastian** [comment]
Compound components are not supported in RSC.

Please read:
https://flowbite-react.com/docs/getting-started/server-components#compound-components

To solve ur issue, just add `"use client"` directive at the top of ur file.

**Comment by vitalijalbu** [comment]
> Compound components are not supported in RSC.
> 
> Please read: https://flowbite-react.com/docs/getting-started/server-components#compound-components
> 
> To solve ur issue, just add `"use client"` directive at the top of ur file.

hi yes i solved by using `"use client"`,  and move it in another component.
basically my page structure is:
**page.tsx** to get data (**ssr**)

then i should split it into client mini-components to render flowbite??
is that a good approach?
thanks.
