### ISSUE TITLE
flowbite style css not found

### ISSUE THREAD

**Issue by robiul215** [themesberg/flowbite-react#1401]
flowbite style css not found in nextjs with tailwindcss 
please check this link below

https://prnt.sc/v00Yg6oeK-GE
https://prnt.sc/u0bwna96w_9M
https://prnt.sc/3vXJqeVL4EJW

**Comment by rluders** [comment]
@robiul215 check the configuration steps again:
https://flowbite-react.com/docs/guides/next-js
