### ISSUE TITLE
Select doesn't have same height as inputs

### ISSUE THREAD

**Issue by vitalijalbu** [themesberg/flowbite-react#1417]
![Screenshot 2024-06-06 alle 10 34 42](https://github.com/themesberg/flowbite-react/assets/40239902/38110c95-1f32-4218-bd88-88a6c6ab9e00)

**Comment by SutuSebastian** [comment]
What was the issue after all? Theme override?

**Comment by vitalijalbu** [comment]
yes right, theme override...
