### ISSUE TITLE
Provide clear option for TextInput component.

### ISSUE THREAD

**Issue by QBT-VinayAdiga** [themesberg/flowbite-react#1432]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary

Describe how it should work, and provide examples of the solution, which might include screenshots or code snippets.

## Context

What are you trying to accomplish? How is your use case affected by not having this feature?

**Comment by SutuSebastian** [comment]
A bit more info please.

**Comment by bhuynhdev** [comment]
I think what he may have meant is that the TextInput component exists but there is no documentation on the flowbite-react.com site

**Comment by rluders** [comment]
It is documented: https://flowbite-react.com/docs/components/forms

**Comment by bhuynhdev** [comment]
Thank you so much. I was blind. I saw the "Forms" heading on the left-side navbar with only FileInput and Floating Label and thought where did all the inputs go
