### ISSUE TITLE
Build Process Fails Due to Missing Modules in React Client Manifest for flowbite-react Components

### ISSUE THREAD

**Issue by itsbalamurali** [themesberg/flowbite-react#1446]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to the project directory containing the Next.js application.
2. Run the `next build` command to create an optimized production build.
3. Wait until the build process reaches the static page generation phase.

## Current behavior

During the static page generation phase, the build process throws errors related to missing modules in the `flowbite-react` package. Specifically, the errors mention that the modules `Sidebar` and `Sidebar.ItemGroup` cannot be found in the React Client Manifest. The build process fails with the following errors:

```
Error: Could not find the module "/Users/someuser/andpath/Web/node_modules/flowbite-react/dist/esm/components/Sidebar/Sidebar.mjs#Sidebar#Items" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
Error: Could not find the module "/Users/someuser/andpath/Web/node_modules/flowbite-react/dist/esm/components/Sidebar/Sidebar.mjs#Sidebar#ItemGroup" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```

## Expected behavior

The build process should complete successfully without any errors. The modules from `flowbite-react` should be properly included and resolved in the React Client Manifest, allowing for successful static page generation.

## Context

I am trying to build a production version of a Next.js application that uses `flowbite-react` components. This issue occurs during the build process on a macOS operating system. It might be related to the configuration of the Next.js server components bundler or the way `flowbite-react` exports its modules.

- Node.js version: v22.3.0
- Next.js version: 14.2.5
- Flowbite React version: ^0.9.0

```json
{
  "name": "flowbite-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@builder.io/partytown": "^0.10.2",
    "flowbite": "^2.4.1",
    "flowbite-react": "^0.10.1",
    "next": "14.2.5",
    "next-auth": "^5.0.0-beta.19",
    "next-seo": "^6.5.0",
    "preline": "^2.3.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@cloudflare/next-on-pages": "^1.12.1",
    "@types/node": "^20.14.10",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.2.5",
    "postcss": "^8.4.39",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.5.3"
  }
}
```

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.
[build.log](https://github.com/user-attachments/files/16183667/build.log)

**Comment by SutuSebastian** [comment]
Make sure the components are imported properly if using RSC (eg: no `"use client";` directive), check [server-components#compound-components](https://flowbite-react.com/docs/getting-started/server-components#compound-components).

Is that page running on edge runtime defined?

**Comment by itsbalamurali** [comment]
@SutuSebastian you're right had used client side components on SSR. had changed them to server side ones where ever applicable. Thanks again!
