### ISSUE TITLE
Access to older versions of the documentation

### ISSUE THREAD

**Issue by lehelk** [themesberg/flowbite-react#1449]
- [ x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ x] I have tested the latest version

## Summary

Currently I have an older version of flowbite-react (0.7.8)
Since I want to add 2 new components Popover and Drawer (which is marked as new) in the documentation I decided that I would like to update flowbite-react. However shortly after updating it I ran into issues with custom button theming not being properly applied. This issue was already raised here: https://github.com/themesberg/flowbite-react/issues/1445

Now I'm a position where I can't upgrade flowbite-react and I can't access the documentation for my current version of flowbite-react.

## Context

I'm trying to access the documentation of the version of flowbite-react that I have now and from which I can't upgrade at the moment.

**Comment by rluders** [comment]
@lehelk I think that this is important, but... only once we reach the `1.0.0` release, as for the pre-stable release `< 1.0.0` you can clone it based on the tag and build the documentation locally.
