### ISSUE TITLE
Datepicker duplicate month

### ISSUE THREAD

**Issue by khareembld** [themesberg/flowbite-react#1456]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Select January 31
2. Click on the month header to select another month
3. It will show duplicated "Mar"

## Current behavior
![image](https://github.com/user-attachments/assets/4fc81b11-8fab-4c08-9581-c4167d71bfd5)

**Comment by khareembld** [comment]
I opened a PR
https://github.com/themesberg/flowbite-react/pull/1457

**Comment by adeherysh** [comment]
I am having the same issue, please fix this 🙏
In any month on date
30th duplicate => Mar
31st duplicate => Mar, May, Jul, Oct, Dec

**Comment by adeherysh** [comment]
Hi @rluders thanks for your help,
is there any plan to release this fix?
cc: @fiqryq

**Comment by rluders** [comment]
I think that we should have a new release soon. @SutuSebastian is updating some dependencies, and I think that as soon he finishes it we may have a new release.
