### ISSUE TITLE
[Feature request] Dropdown make the label optional

### ISSUE THREAD

**Issue by raky291** [themesberg/flowbite-react#1466]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary

<img width="331" alt="Screenshot 2024-08-16 at 7 01 30 a m" src="https://github.com/user-attachments/assets/59b3b8c7-0229-4161-9082-6a9fa4fdbcbb">

Hi, I would like to suggest a change, and that is to make the label optional, it is not necessary if we are using the renderTrigger property to define the button and its content, forcing the dev to define it empty. Regards.

**Comment by haruki860** [comment]
@rluders 
I’m participating in an open-source project for the first time, and if there are no assignments, may I work on this issue

**Comment by rluders** [comment]
@haruki860 I think that we already have a PR for this one, and it should be closed... by you can find any issue with the label 'good first issue' and we will be super happy with your contribution.
