### ISSUE TITLE
Table Cannot set properties of displayName

### ISSUE THREAD

**Issue by Bijig0** [themesberg/flowbite-react#1472]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

on flowbite-react 0.6.4, woke up and got this error randomly? Started out only running in my tests then started actually breaking in my app the following day

chunk-MVHE7MKX.js?v=a7c07ed8:9309 Uncaught TypeError: Cannot set properties of undefined (setting 'displayName')
    at chunk-MVHE7MKX.js?v=a7c07ed8:9309:23

Tried upgrading to 0.10.1 which gives this error instead

 ✘ [ERROR] Missing "./lib/esm/components/Table/TableBody" specifier in "flowbite-react" package [plugin vite:dep-scan]

## Current behavior

Describe what is currently happening and why it's a problem.

## Expected behavior

Describe what you expected to happen.

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by SutuSebastian** [comment]
A lot of things changed from version `0.6.4` to now `0.10.1`, the most changes happened in [flowbite-react@0.8.0](https://github.com/themesberg/flowbite-react/releases/tag/flowbite-react%400.8.0) release regarding breaking changes, please read the changelog.

The most simple way to fix ur problem is to follow the latest installation guide, for example [this guide](https://flowbite-react.com/docs/guides/vite) is for Vite.

**Comment by Bijig0** [comment]
nvm it was a bad import

`import { TableBody } from "flowbite-react/lib/esm/components/Table/TableBody";`
