### ISSUE TITLE
Expose hide, show in Select Dropdown Component

### ISSUE THREAD

**Issue by beatelite** [themesberg/flowbite-react#1482]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary

When trying to hide a dropdown from within the dropdown, there's no way to do it. 

if I try: 
```js
import { useState, useRef } from 'react';
import { Dropdown } from 'flowbite-react';

const MyComponent = () => {
  const dropdownRef = useRef(null);

const closeDropdown = () => {
  if (dropdownRef.current) {
    dropdownRef.current.hide();
  }
};

return (
<Dropdown ref={dropdownRef}>
  <Dropdown.Item >
    Item 1 ... etc
  </Dropdown.Item>

<button onClick={closeDropdown} > Close </button>
</Dropdown>
)
}
```

it doesn't work. 

## Context

I want a simple close button inside a dropdown select that closes the dropdown. I know they can clickoutside, but we want a button as well.

**Comment by rluders** [comment]
<button onClick={closeDropdown} > Close </button> isn't an valid child for Dropdown. You should use the DropdownItem, please, check the documentation.
