### ISSUE TITLE
Issue with this library

### ISSUE THREAD

**Issue by xiaolin911211** [themesberg/flowbite-react#149]
Getting this error now:
SyntaxError: Unexpected token 'export'
With the following codes that i follow in https://github.com/themesberg/flowbite-react.

```js
// tailwind.config.js
module.exports = {
    content: [
        "./src/**/*.{html,js,svelte,ts}",
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {},
    },
    plugins: [require('flowbite/plugin')],
}
```
```jsx
// app.js
import Modal from "flowbite/src/components/modal";

const MyApp = ({Component, pageProps}) => {
    return (
        <>
            <Modal>
            </Modal>
        </>
    );
}

export default MyApp
```

**Comment by tulup-conner** [comment]
Hey there, if you are importing from `flowbite/src/components/modal`, you are using `flowbite`, not `flowbite-react`. You will need to change your import to something like this:

```js
import { Modal } from "flowbite-react";
```

**Comment by xiaolin911211** [comment]
> 

When i do this is back to the old issue again ReferenceError: document is not defined

**Comment by xiaolin911211** [comment]
Did anyone actually test this with NextJS or is there a sample project i can download using NextJS with this library?

**Comment by Siumauricio** [comment]
You can import the component using Dynamic imports https://stackoverflow.com/questions/53139884/next-js-disable-server-side-rendering-on-some-pages 

Using this you will rendering the component in the client side

**Comment by tulup-conner** [comment]
> Did anyone actually test this with NextJS or is there a sample project i can download using NextJS with this library?

Yea, I haven't gotten around to completing it yet unfortunately. 

With that said, the issue you are having should be resolved in the latest version of the software. The issue you are having is related to https://github.com/themesberg/flowbite-react/pull/124.

I just checked and, unfortunately, a release hasn't actually been produced for it yet on npm. 

If you want to use it in the meantime, you should be able to install the latest on Github via npm.

**Comment by tulup-conner** [comment]
Hey @xiaolin911211, I just created a Next.js starter app that you can use as a baseline for your app: https://github.com/tulup-conner/flowbite-next-starter

All of the components work, save Breadcrumb. I found a bug with that that is not Next.js related - should be fixed soon.

**Comment by rluders** [comment]
@xiaolin911211 did the sample repository and the last release help with this issue? Can we close it?

**Comment by rowlandekemezie** [comment]
> Hey @xiaolin911211, I just created a Next.js starter app that you can use as a baseline for your app: https://github.com/tulup-conner/flowbite-next-starter
> 
> All of the components work, save Breadcrumb. I found a bug with that that is not Next.js related - should be fixed soon.

Thanks for this @tulup-conner. Maybe we should add this example of example folder in the repository. Did you get the `DarkThemeToggle` working as well?

**Comment by xiaolin911211** [comment]
Thank you so much, is working for me

> > Hey @xiaolin911211, I just created a Next.js starter app that you can use as a baseline for your app: https://github.com/tulup-conner/flowbite-next-starter
> > All of the components work, save Breadcrumb. I found a bug with that that is not Next.js related - should be fixed soon.
> 
> Thanks for this @tulup-conner. Maybe we should add this example to examples folder in the repository. Did you get the `DarkThemeToggle` working as well?
