### ISSUE TITLE
Move docs to a separated project inside the repository

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#152]
I still not happy with the fact that the docs are inside the `src` folder. It always drive me crazy, 'cause it isn't part of the librabry. So we should move it to a separated react application inside our repository, and it will also works as an example.

**Describe the solution you'd like**
- Inside the repository create a new react project on project root `/docs` folder
- Link the dependencies to its `package.json` to use the ones on the librabry `node_modules`, including the own `flowbite-react` librabry
- Move the build scripts to the `package.json` for the `docs` project
- Move the `src/docs` to the new project

**Describe alternatives you've considered**
n/a

**Additional context**
Better if we could create the docs project without CRA and using NextJS or Remix.

**Comment by rluders** [comment]
@davemooreuws what I want to do with this task is something very similar to it. I also want to make it a monorepo, my main issue right now with the current structure is that we are using CRA, and we do have a lot of folders inside the `src/` folder. 
IMHO, we need to split it into separated projects, by having, for now, the `./src` storing the library things, while the `./docs` being a separated project, inside the repository, that will only have the documentation.

With that we could simplify the `package.json` for both projects as well to remove the CRA to the library itself, removing the "magic layer" that it introduces to the build.

But yep, you got the idea. I'm not sure how it is going to be with the storybook yet, 'cause I consider to have the stories close to the components as a HUGE benefit, and I think that I already discussed with someone about it, based on [this post](https://betterprogramming.pub/10-storybooks-best-practices-ad5fec0f145a). But of course, that we could still have a `./storybook` at the project root to hold some `.mdx` files. But this is another task. Right now, **docs**! :smile:

**Comment by tulup-conner** [comment]
I'm thinking...

```
docs/
  public/
  (Hugo .md files)
  ..
examples/
  flowbite-next-starter
    src/
    ..
  flowbite-remix-starter
    src/
    ..
  ..
packages/
  flowbite-react/
    src/
      components/
        *.stories.tsx (include stories also)
        ..
      helpers/
      theme/
    ..
  ..
tests/
  integration/
    docs/
    examples/
  unit/
    components/*.spec.tsx
    helpers/*.spec.ts
  ..
```

**Comment by rluders** [comment]
I don't think that moving the unit tests away from the components is a good idea. I like to keep it close, maybe because it is a good practice on Go.

But I'm not totally against it, it is just my opinion. So, let's try to find some info.

- What are the pros or cons?
- Is it a community standard?
- If not, what is the community standard for unit testing?

**Comment by tulup-conner** [comment]
I think Jest suggests `__tests__` which is weird.

I am indifferent, my logic is keep the integration tests and unit tests together, rather than having Cypress in its own folder `cypress` randomly.
