### ISSUE TITLE
Incorporate the original documentation layout from the main library

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#165]
**Is your feature request related to a problem? Please describe.**

I have already mentioned this in the Discord channel, the idea is to use the same documentation layout across the main library and the React one. This will help the community migrate faster from one library to another as they are already used to the two sidebar and main content area.

This will also help us write texts and make the documentation SEO ready to target keywords like "React Button - Flowbite", "React Modal - Flowbite" and so on. Here's the link for the main docs: https://flowbite.com/docs/getting-started/quickstart/.

The source code can be copied and integrated into the React docs: https://github.com/themesberg/flowbite (it's open-source under the MIT license, so no problem here).

The documentation layout is pretty static, so I don't see a problem integrating it with React.

**Describe the solution you'd like**

Copy the layout (if it's 100% the same better) from the main docs area and based on this layout create the docs for Flowbite React.

**Describe alternatives you've considered**

The current layout is okay, but if we want to get this library in competition with Material UI and other libraries we need to upgrade the docs including an Algolia Search integration (I can help with this after the main layout is finished).

**Additional context**

We can keep talking here and on Discord to get this going.

**Comment by rluders** [comment]
Since this one is related to #167 and #152 I guess that we can handle it in one single task.

**Comment by tulup-conner** [comment]
We should revisit this for 1.0. There's no reason we can't simply redesign the docs to look just like the vanilla docs, TBH.

**Comment by zoltanszogyenyi** [comment]
@tulup-conner this is super important and also related to the SEO issue (https://github.com/themesberg/flowbite-react/issues/165) because without the new docs layout we cannot properly set up the tags and necessary content.

We can either keep the current sidebar layout for the menu and iterate on the current set up or we can replicate the main library more or less but re-create it using Flowbite React components. Probably would be easier in terms of design because we would only need to make direct integrations instead. So I would recommend using the main layout.

I would be more than happy to help with adjustments and upgrades but it would be great if the main structure was already built up using the Flowbite React components. Though I am available to help in terms of advice and couple of PRs.
