### ISSUE TITLE
Update logo & primary color

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#166]
**Is your feature request related to a problem? Please describe.**

We have created a new logo for Flowbite React and I suggest we also change the current blue color to the hex `#61dafb` with `text-gray-700` for the text color.

**Describe the solution you'd like**

Update the logo everywhere (including GitHub and the docs) and also the OG image based on what I have shared. The primary color can also be changed and tested if it looks good (if not, we can keep the current blue color).

**Describe alternatives you've considered**

-

**Additional context**

-

Assets:

![flowbite-react-icon](https://user-images.githubusercontent.com/8052108/170982669-82299dfa-b4e1-4fc0-93a9-d42a11848c88.svg)
![flowbite-react-logo](https://user-images.githubusercontent.com/8052108/170982673-d8baba9b-934f-44cd-a021-38cca2e2516e.png)
![flowbite-react-og-image](https://user-images.githubusercontent.com/8052108/170982674-26cee09b-7497-48ae-b454-6df19ac33e58.png)

**Comment by farshmachine** [comment]
Hi there. Mind if i help you with this one?

**Comment by rluders** [comment]
Hi @farshmachine, yes, please, go ahead. :)

I'll just say that if you found any change needed to the `docs/` just ignore it. We are going to move it to use [Hugo](https://gohugo.io/) instead using the react.
