### ISSUE TITLE
Simplify the usage of spinner inside the Button component

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#175]
**Is your feature request related to a problem? Please describe.**

Currently in order to have a `Spinner` inside a `Button` to indicate processing we need to manually build all the logic. Lets make it something present inside the component.

**Describe the solution you'd like**

Some ideas:

```jsx
<Button type="submit" color="info" processing={true} processingText="Sending...">Send</Button>
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tulup-conner** [comment]
Thoughts on `<Button spinner spinnerText="Sending..">Send</Button>` here? This is easy to implement.

**Comment by rluders** [comment]
Yep, I think that it makes sense.

**Comment by rluders** [comment]
I updated the existing PR for this one. Maybe someone could test and review it.

**Comment by MirSowasVonEgal** [comment]
Hey, how can I use/install it? :)
npm i flowbite flowbite-react is not working.
