### ISSUE TITLE
Component: Datapicker

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#186]
**Is your feature request related to a problem? Please describe.**

We need to implement the Flowbite Datapicker component.
https://flowbite.com/docs/plugins/datepicker/

**Describe the solution you'd like**

The component should be exactly has described in the Flowbite core documentation.

**Describe alternatives you've considered**

PR must have:
- Component (w/ Theme support)
- Storybook
- Documentation
- Unit test

I can see two options here:
- Rewrite the Datapicker (it is going to be hard, but maybe the best)
- Use the existent library (will it work with React/Nextjs?)

**Additional context**
- [Link to original Datapicker JavaScript file](https://unpkg.com/flowbite@1.4.7/dist/datepicker.js)

**Comment by tulup-conner** [comment]
Moving to #626
