### ISSUE TITLE
Component: Range slider

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#188]
**Is your feature request related to a problem? Please describe.**

We need to implement the Range slider component as described in the core library.
https://flowbite.com/docs/forms/range/

**Describe the solution you'd like**

PR must have:
- Component (w/ Theme support)
- Storybook
- Documentation
- Unit test

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by yoku2010** [comment]
Can I implement the `RangeSlider` component?

**Comment by rluders** [comment]
Sure, @yoku2010

**Comment by yoku2010** [comment]
@rluders I have completed the `RangeSlider` component. Please check the linked PR. Thanks!
