### ISSUE TITLE
[components] Floating Label

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#189]
**Is your feature request related to a problem? Please describe.**

We need to implement the Floating Label component as described in the core library.
https://flowbite.com/docs/forms/floating-label/

**Describe the solution you'd like**

PR must have:
- Component (w/ Theme support)
- Storybook
- Documentation
- Unit test

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by okellomarvinkevin** [comment]
I am taking this on

**Comment by okelloMarvinSophany** [comment]
@rluders Is the Floating folder meant for the floating label component? If so, I see that there's already some code, what context do I need to know before under taking this task?

**Comment by rluders** [comment]
@okelloMarvinSophany well, there are some possibilities that we may need to consider.

1. It can be an option to the `Label`
2. It can live in a separated folder `FloatingLabel`

Also, as the `Label` it will work together with the Forms elements (`TextInput` and `TextArea` - I guess) ;

**Comment by okelloMarvinSophany** [comment]
@rluders I made a pr. The build failed with this error Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov' failed with exit code 255. I do not think that its coming from  my side. I need help with that
