### ISSUE TITLE
Development: Fix annoying error when `yarn watch`

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#196]
**Describe the bug**

> **Note**
> This is NOT A BUG IN THE LIBRARY. it doesn't impact users only developers/contributors.

When I'm running the `watch` or `dev` on my machine I'm getting this error:

```
Failed to parse source map from '/flowbite-react/node_modules/@base2/pretty-print-object/src/index.ts' file: Error: ENOENT: no such file or directory, open '/flowbite-react/node_modules/@base2/pretty-print-object/src/index.ts'
 @ ./node_modules/react-element-to-jsx-string/dist/cjs/index.js 11:24-61
 @ ./src/docs/pages/ThemePage.tsx 4:0-66 57:20-43 110:18-41
 @ ./src/docs/routes.tsx 37:0-42 444:34-43
 @ ./src/docs/Root.tsx 12:0-34 104:22-32 160:22-32
 @ ./src/index.tsx 5:0-35 17:37-41

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```

**To Reproduce**
1. Clone the repository
2. Install the dependencies
3. Execute: `yarn watch`

**Expected behavior**
It should not have any error when running the command `dev` or `watch`.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Node: 16.14.0
 - Yarn: 1.22.17

**Additional context**
n/a

**Comment by tulup-conner** [comment]
This goes away with migration to Next.js so I'm just going to close it now
