### ISSUE TITLE
Chore: Improve test speed with concurrency

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#233]
Unit tests are really slow, in some cases. I think that we can make it faster.

**Describe the solution you'd like**
Implement [concurrency](https://vitest.dev/guide/features.html#running-tests-concurrently) to the tests.

**Describe alternatives you've considered**
None

**Additional context**
I didn't test to see the real speed impact, it could happen that it actually don't happen the test speed at all. In this case, the answer to this issue is to get it dropped and keep the test as it is.

**Comment by tulup-conner** [comment]
Already done.
