### ISSUE TITLE
Refactor: formControls components must have its own folders

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#234]
**Is your feature request related to a problem? Please describe.**
The way that the `formControls` are organized right now doesn't actually match the other component structure. We need to move it to a flat folder structure and keep it consistent with the rest of the components' structure.

**Describe the solution you'd like**
Every component inside the `formControls` folder must be moved to its own folder at the components' root folder, and the main file for each component must be `index.tsx`.

**Describe alternatives you've considered**
We could also keep the components in their own folders but instead move them to the components' root folder, and keep them inside the `formControls` folder. This would avoid some breaking changes, but IMHO, I would prefer to keep all the components in the same folder, even if it means breaking things, better doing it right now than later.

**Additional context**
None.

**Comment by tulup-conner** [comment]
Do you mind if I do this? It's been bothering me lol

**Comment by rluders** [comment]
@tulup-conner go ahead.
