### ISSUE TITLE
React v18

### ISSUE THREAD

**Issue by MahdyarEn** [themesberg/flowbite-react#251]
Flowbia does not work with React version 18

https://stackoverflow.com/questions/72159197/how-can-i-add-flowbite-to-the-react-js-followed-the-guide-on-the-flowbite-but

**Comment by rluders** [comment]
You are not using `flowbite-react`.

**Comment by rluders** [comment]
@MahdyarEn does it help?

**Comment by MahdyarEn** [comment]
Thanks Worked 🔥!
