### ISSUE TITLE
Misbehavior for sidebar when collapsed

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#258]
**Describe the bug**

The sidebar, when collapsed is acting weird:
- It shows the badge
- It makes the whole `children` as its tooltip (even the icon)

**To Reproduce**

1. Create a CRA project with flowbite-react
2. Create the sidebar menu as described in the documentation (with icons and labels)
3. Change its attribute to be collapsed `<Sidebar collapsed={true} ...>...</Sidebar>`
4. Hover the mouse hover to see the issue

**Expected behavior**
- When collapse it should NOT display the `Badge`, ONLY the icon
- The content of `Tooptip` must be or the original `children` or/and also allow it to be overwrite by `Sidebar.Item` property

**Screenshots**

![localhost_3000_](https://user-images.githubusercontent.com/191027/177106599-f952e9ad-74af-4c9e-b266-e08567567450.png)

**Additional context**
n/a

**Comment by tulup-conner** [comment]
I found some tests are reporting false positive here. `userEvent.focus(something)` is not reliable. We should add `Tooltip` integration tests in `cypress` to actually cover user interactions like `hover`
