### ISSUE TITLE
docs: migrate the Tooltips to Hugo

### ISSUE THREAD

**Issue by mouracamila** [themesberg/flowbite-react#297]
**Feature request**
Move the Tooltips documentation from the [current documentation page](https://flowbite-react.com/) to Hugo, it must look similar to the **Alert example** that can be [found here](https://github.com/themesberg/flowbite-react/blob/main/docs/content/components/alerts.md)

**Describe the solution you'd like**
It would be nice if it had these elements in the documentation:

- [ ] Usage
- [ ] Properties
- [ ] Examples

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by xeno** [comment]
Happy to help, but I'm not quite sure what you mean by "to Hugo". Can you add a little more detail?

Thanks!

**Comment by rluders** [comment]
@xeno unfortunately all documentation tasks are blocked by this PR: https://github.com/themesberg/flowbite-react/pull/311

But answering your question about Hugo: https://gohugo.io/
