### ISSUE TITLE
Error: useSidebarItemContext should be used within the SidebarItemContext provider!

### ISSUE THREAD

**Issue by valerius21** [themesberg/flowbite-react#299]
**Describe the bug**
I'm getting the in the title mentioned error while using the example code. Browsing the code, it looks alright to me.

**To Reproduce**

1. Create a new component
2. use the following code
```tsx
import { Sidebar } from 'flowbite-react'

const TemplateSidebarNavigation = () => {
  return (
    <div>
      <h2>{'TemplateSidebarNavigation'}</h2>
      <Sidebar aria-label="Test DB">
        <Sidebar.Items>
          <Sidebar.Item href="#">Dashboard</Sidebar.Item>
        </Sidebar.Items>
      </Sidebar>
    </div>
  )
}

export default TemplateSidebarNavigation
```
3. See error

**Expected behavior**
The component should render without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/10323945/178987972-f1564d78-7c0d-49e5-9671-c400c9016d0a.png)

**System information:**

- Device: PC
- Resolution: 1440p
- OS: Windows 11
- Browser: Chrome
- Version: latest

**Project information:**

- Tailwind: ^3.1.4
- Flowbite: ^1.4.7
- Flowbite React: ^0.1.3
- Type: Redwoodjs with React 18.2.0

**Comment by ValTM** [comment]
Same issue here.

**Comment by rluders** [comment]
@valerius21 can you confirm that the solution above works?

**Comment by valerius21** [comment]
@rluders Thank you for the response. I'll retry everything again when RedwoodJS finishes the React 18 upgrade officially. I did not see it initially. https://github.com/redwoodjs/redwood/pull/4992
