### ISSUE TITLE
Empty Form Submission

### ISSUE THREAD

**Issue by hlauinfo** [themesberg/flowbite-react#303]
**Describe the bug**
Form submissions are returning empty responses when using the form control React components.

**To Reproduce**
Replicated sample form, pointed action to an external URL.

**Expected behavior**
Form should submit data

**Screenshots**

**System information:**

- Device: MacBook
- Resolution:
- OS:
- Browser: Chrome
- Version:

**Project information:**

- Tailwind: 3.1.6
- Flowbite: 1.4.7
- Flowbite React: 0.1.3
- Type: CRA

**Additional context**

**Comment by hlauinfo** [comment]
This one was staring at me for a bit. Forms need field names in addition to ids in order for them to be properly submitted. Recommend that documentation be updated to reflect this.

**Comment by tulup-conner** [comment]
The browser is documented to not submit inputs that do not have a `name` attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name
