### ISSUE TITLE
After upgrading from 0.0.27 to 0.1.3, TextInput "color" prop does not change color of input

### ISSUE THREAD

**Issue by joelcieslar** [themesberg/flowbite-react#306]
**Describe the bug**

This is how I've been using `TextInput`:

```jsx
<TextInput
        id="postcode-field"
        type="text"
        color={errors.postcode ? 'red' : undefined} // 👈 see here
        helperText={errors.postcode}
        onChange={...}
 />
```
When there is an error, the text area is shaded red:

![image](https://user-images.githubusercontent.com/18103212/180121585-b02ff884-0c27-4a7e-8deb-e8c637cf4c01.png)

Just now, I upgraded from `0.0.27` to `0.1.3` and this is no longer the case:

![image](https://user-images.githubusercontent.com/18103212/180122021-e132d4fa-60b0-44ad-98fe-4426fe0ff36a.png)

It's also happening in the _"Success and error validation"_ example in the docs: https://flowbite-react.com/forms

**Project information:**

- Tailwind: `3.1.6`
- Flowbite: `1.5.1`
- Flowbite React: `0.1.3`

**Comment by rluders** [comment]
@joelcieslar yep, the documentation isn't showing the correct color.

Check this https://github.com/themesberg/flowbite-react/blob/bfef57a8edc6d338ba6971f07d3a8cd5856b9fa6/src/lib/theme/default.ts#L350

For this case we are using the color names based on states, so... warning, info, success, and so.

**Comment by rluders** [comment]
BTW, I just marked it as a `wontfix` 'cause we are moving the documentation to Hugo for the v1.0.0 release.
