### ISSUE TITLE
Allow className for all components

### ISSUE THREAD

**Issue by leesiongchan** [themesberg/flowbite-react#307]
**Is your feature request related to a problem? Please describe.**

I wish to customize & improve some of the primitive components like `Checkbox` or `Label` to have different look-and-feel. One common example is like the `TextInput` with `sizing` props to allow user to customize sizing at will. I curious why most components disallow to extend `className` ? 

**Describe the solution you'd like**

Allow `classname` for all components.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by rluders** [comment]
Nope. :)

**Comment by leesiongchan** [comment]
But sometime we need to adjust its positioning, padding, margin, etc.? One example is like the below where I wish to align center & provide a little gap between.

```
<Label className="inline-flex gap-2 items-center">
  <Checkbox />
  Remember me
</div>
```

I understand there is another way to accomplish the same thing, but I believe there are more cases like this where we need `className` not only to customize its styling but also for us to adjust its positioning.

**Comment by rluders** [comment]
```jsx
<Label>
  <div  className="inline-flex gap-2 items-center">
    <Checkbox />
    Remember me
  </div>
</Label>
```
and
```jsx
<div  className="w-full"><Button>Hello World</Button></div>
```

**Comment by leesiongchan** [comment]
The second wont work though haha.

**Comment by rluders** [comment]
I didn't tested it. :)
AFAIK, default Button style is `w-fit`, isn't? It should have the parent size. If not, it is a bug.

**Comment by rluders** [comment]
Also, theme support: https://github.com/themesberg/flowbite-react/blob/bfef57a8edc6d338ba6971f07d3a8cd5856b9fa6/src/lib/theme/default.ts#L192

**Comment by jwhitmarsh** [comment]
@rluders `w-fit` applies `width: fit-content` which is the available space up to the max of the content, _not_ the available space of the parent. `w-full` would do that.

**Comment by rluders** [comment]
@jwhitmarsh in this case, probably a easy fix to theme will do the job. Do you want to create one?

**Comment by rluders** [comment]
Opening a new issue to the `w-fit`

**Comment by nihirv** [comment]
I understand the library is still early on in development, but that's exactly why I think you should allow users to break the design system at will with className. Themeing does work for most usecases in any given application, but these applications likely also have a component which need to break conventional design patterns.

And whilst the library is still being developed, I imagine some users (myself included) use both vanilla tailwindcss and some components from flowbite react. Adding another theme provider on top of what I currently have (including how I support darkmode) seems very ugly, when in reality all I might want to do is change the colour of one particular instance of a component.
