### ISSUE TITLE
`ButtonGroup` ignores nested `Button`s

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#318]
**Describe the bug**
`ButtonGroup` prop-drills its immediate children, assuming they are `Button`s. Thus, something like this:

```js
<Button.Group>
  <div className="w-10">
    <Button color="gray">Profile</Button>
  </div>
  <div className="w-10">
    <Button color="gray">Settings</Button>
  </div>
  <div className="w-10">
    <Button color="gray">Messages</Button>
  </div>
</Button.Group>
```

Does not work like expected.

**To Reproduce**

1. Add the above snippet to a `flowbite-react` project
2. Observe that the buttons are not grouped together, since props (namely, `positionInGroup`) aren't being passed

**Expected behavior**
We should be able to put any HTML inside a `Button.Group`. Obviously, as long as there's a few `Button`s in there.

This wasn't necessary before `FlowbiteTheme`, but now, in order to customize `Button`s, you sometimes need to wrap them in a `<div>`. That behavior should be supported by `ButtonGroup`s.

We can switch to context, but I don't think there's any way to keep track of the order of the buttons by doing that. So what might be necessary is to prop-drill until we find `Button`s, specifically, rather than regular HTML elements.

**Comment by rluders** [comment]
@tulup-conner I think that now we don't need the `<div />` wrapping the buttons again, right? So probably this issue isn't valid anymore. Right?

**Comment by tulup-conner** [comment]
@rluders In short, yeah. I believe this is a product of the time when after we added theme support but neither the ability to edit className nor theme per component. So the problem I was trying to solve here was to be able to change Button behavior dynamically, which we can do now with className or inline theme.
