### ISSUE TITLE
useId is not exported in react 17

### ISSUE THREAD

**Issue by BaumgartnerWilliam** [themesberg/flowbite-react#321]
**Describe the bug**
Some components use newest react feature `useId` which is not available in react 17.

**To Reproduce**

1. `npm i react@17 react-dom@17 flowbite flowbite-react`
2. Import any component that uses `useId` such as [Progress](https://github.com/themesberg/flowbite-react/blob/main/src/lib/components/Progress/index.tsx#L32)
3. see error

**Expected behavior**
The component should be rendered w/o errors since react 17 is still [supported](https://github.com/themesberg/flowbite-react/blob/main/package.json#L60-L61)

**Screenshots**

<img width="611" alt="image" src="https://user-images.githubusercontent.com/3015038/182456790-1d868dc2-c11e-4e15-86e4-316b8b8b7b3d.png">

**Comment by rluders** [comment]
Hi @BaumgartnerWilliam thanks for reporting it. We need to remove the React 17 from the `package.json` we discussed and we don't have the intention to keep it working for it.

**Comment by BaumgartnerWilliam** [comment]
Oh I see. Thank you for the heads up. Cheers mate.
