### ISSUE TITLE
Unable to import Breadcrumb and Breadcrumb.Item

### ISSUE THREAD

**Issue by nakulnagariy** [themesberg/flowbite-react#322]
**Describe the bug**
While importing Breadcrumb from flowbite-react show an error.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/26174424/182904373-fa7f225a-4363-41cd-8334-459d42911de1.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/26174424/182904446-216d0234-707f-4ce1-a2eb-8e396c27c8ec.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

**Comment by rluders** [comment]
```jsx
import { Breadcrumb } from 'flowbite-react';
```

```jsx
<Breadcrumb.Item>...</Breadcrumb.Item>
```

**Comment by nakulnagariy** [comment]
> You are using it wrong. Check the import and the tag.
> 
> ```js
> import { Breadcrumb } from 'flowbite-react';
> ```
> 
> ```js
> <Breadcrumb.Item>...</Breadcrumb.Item>
> ```

Actually, I tried with that too, but I found out that since it's a freemium component so I can't use it.

**Comment by rluders** [comment]
@nakulnagariy the flowbite is free. MIT license. It isn't freemium.
