### ISSUE TITLE
Tooltips can get rather wide with a lot of content - perhaps would work better with an (optional?) max width

### ISSUE THREAD

**Issue by joelcieslar** [themesberg/flowbite-react#323]
I'm using tooltips to provide hints for form fields. In some cases, the content can be several sentences or more.

The result is a very wide tooltip. I think it would look better if the width was fixed and text could wrap into several lines.

![image](https://user-images.githubusercontent.com/18103212/183136624-fea857fc-10be-4594-b02f-a962c256cce6.png)

**Comment by rluders** [comment]
I think that just adding some `w-max-md` or something to this line:

https://github.com/themesberg/flowbite-react/blob/c9c257e75f702961739f13fcc926eb58af5e3670/src/lib/theme/default.ts#L888

Should solve the issue. Can someone test it and create a PR?

**Comment by rluders** [comment]
I tested it, and I didn't find the bug. This was before we enable access to `className` to the components. If necessary now it is possible to limit the width of the tooltip just by using it.
