### ISSUE TITLE
Collapse Sidebar on small screens

### ISSUE THREAD

**Issue by magixus** [themesberg/flowbite-react#329]
**Describe the bug**
When the screen is on "xs sm md", sidebar needs to collapse 
 
**To Reproduce**

1. Add a sidebar with all its items
2. Change the browser width to small screen
3. Sidebar does not collapse

**Expected behavior**
Sidebar to collapse on small screens

**Screenshots**
![sidebar](https://user-images.githubusercontent.com/7642058/184508316-a72ee061-93c8-443d-b957-2dcf5f016f3d.gif)

**Project information:**

- Tailwind: 3.1.8
- Flowbite: 1.4.7
- Flowbite React: 0.0.22
- Type: CRA

**Comment by rluders** [comment]
@magixus Please, upgrade it to the latest `flowbite-react` and see it the issue still happening.

**Comment by magixus** [comment]
@rluders I did, but still not collapsing on small screen. 
```json
{
    "flowbite": "^1.4.5",
    "flowbite-react": "0.1.10",
}
```
Maybe my approach is not the most sophisticated one 
```jsx
...
const [collapsed, setCollapsed] = useState(true)

...
{/* Navication top bar */}
<Navbar
	fluid
	rounded
	className="border-b border-gray-200 dark:border-gray-600 bg-slate-50"
>
	<div className="flex items-center">
		{/* Toggle Sidebar */}
		{collapsed ? (
			<div
				type="button"
				className="top-navigation-icon !mr-6"
				onClick={() => setCollapsed(!collapsed)}
			>
				<span className="sr-only"> Toggle sidebar</span>
				<FaOutdent size={24} />
			</div>
		) : (
			<div
				className="top-navigation-icon !mr-6"
				onClick={() => setCollapsed(!collapsed)}
			>
				<span className="sr-only"> Toggle sidebar</span>
				<FaIndent size={24} />
			</div>
		)}

...
{/* Sidebar */}
<div className="flex h-full overflow-hidden bg-white dark:bg-gray-900">
<Sidebar collapsed={collapsed} className={`shadow bg-slate-50`}>
	<Sidebar.Items>
		<Sidebar.ItemGroup>
			{routes.map(({ href, icon, title }, key) => (
				<Sidebar.Item
					key={key}
					icon={icon}
					as={Link}
					to={href}
					active={href === pathname}
					onClick={() => mainRef.current?.scrollTo({ top: 0 })}
				>
					{title}
				</Sidebar.Item>
			))}
		</Sidebar.ItemGroup>
	</Sidebar.Items>
</Sidebar>
<main>...</main>
</div>
```

**Comment by Drex72** [comment]
can i word on this?

**Comment by Drex72** [comment]
can i work on this

**Comment by rluders** [comment]
@Drex72 sure, go ahead

**Comment by Drex72** [comment]
@rluders 
![Screenshot 2022-10-17 200120](https://user-images.githubusercontent.com/90635055/196250167-759db6a7-a729-4928-92bb-bc7d4a0e95dc.png)

How is the collapsed prop in the sidebar being toggled in the index.tsx
![Screenshot 2022-10-17 200323](https://user-images.githubusercontent.com/90635055/196250186-a946136c-bd93-4bef-9ebb-5352d1507830.png)

And what is the underlined code below doing.is it setting an intital state for the collapsed prop??

**Comment by rluders** [comment]
https://github.com/themesberg/flowbite-react/blob/37644b7247a35ce15df0379425139585bc8ae27f/src/lib/components/Sidebar/index.tsx#L21

Well, yep... This is definitely a bug.

**Comment by Drex72** [comment]
I've made the changes and its working.The issue now is committing.
I followed the contributing guide but i'm still getting an error
![Screenshot (40)](https://user-images.githubusercontent.com/90635055/196577798-ef24bf99-afec-4161-917b-fdd46b216293.png)
![Screenshot (41)](https://user-images.githubusercontent.com/90635055/196577912-62d67a58-44bb-475a-9ad5-1df991eff345.png)
![Screenshot (42)](https://user-images.githubusercontent.com/90635055/196577915-fc17e73b-a2d3-406f-8fc5-1ee8c63c8751.png)

**Comment by rluders** [comment]
@Drex72 is it possible that you are not using the [conventionalcommits](https://www.conventionalcommits.org/) rules at your commit message?

**Comment by Drex72** [comment]
I'm not familiar with it, can you give me an idea on what it is

**Comment by rluders** [comment]
@Drex72 there is the link from my previous commend and as well this video: https://www.youtube.com/watch?v=OJqUWvmf4gg

**Comment by rluders** [comment]
I was investigating this one today, and I'm not sure that it is a bug. I mean, OK, it isn't collapsing, but I think that it would be very arbitrary from the component perspective if we add this functionality directly to it.

So, my suggestion is to add this control to your own application and change the `isCollapsed` property of the sidebar according to your desired behavior.

**Comment by BhavyaJain711** [comment]
I tried solving this using ref and even fowardRef, but could not get it working. So i used plain JavaScript to solve this.

 ### Gave id to the NavbarToggle Component.
`<NavbarToggle id='navbarToggleButton' />`

### Added onClick to NavbarCollapse.
`<NavbarCollapse onClick={toggleNavbarCollapse} >`

### The toggleNavbarCollapse implementation.
```
const toggleNavbarCollapse = () => {
    if (window.innerWidth <= 768) {
      const navbarToggleButton = document.getElementById('navbarToggleButton');
      if (navbarToggleButton) {
        navbarToggleButton.click(); // Simulate a click on NavbarToggle
      }
    }
  };

```
