### ISSUE TITLE
Override className is not working

### ISSUE THREAD

**Issue by SerGem811** [themesberg/flowbite-react#334]
I can see that Navbar has property of className but when i put class there (tailwind for example, bg-black), it is not working!!
From the inspect i can see that even it is not there.

Kindly fix it

Mine
react: 17.0.2
flowbite-react: 0.1.8
next: 12.0.4

Regard

**Comment by rluders** [comment]
No flowbite-component give you direct access to `className`. If you want to customize it, you need to use the theme support.

```ts
export interface NavbarComponentProps extends Omit<PropsWithChildren<ComponentProps<'nav'>>, 'className'> {
```

This will not allow you to use the `className` property. Use:
https://flowbite-react.com/theme

**Comment by SerGem811** [comment]
If then why you have className there?
It has property className

**Comment by rluders** [comment]
Oh, oh. I just saw it. Now.

**Comment by SerGem811** [comment]
okay
