### ISSUE TITLE
README

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#34]
**Is your feature request related to a problem? Please describe.**
Currently, the repository doesn't have a `README.md`, so we need to introduce it to make it easy to people to use the library as well to contribute to it.

**Describe the solution you'd like**
I think that the current [flowbite](https://github.com/themesberg/flowbite/blob/main/README.md)'s README is pretty good. So, maybe get some inspiration there. Just be away that we already have at the project the `CODE_OF_CONDUCT.md` and the `CONTRIGUTING.md` files that probably need to be linked at the `README.md`.

**Describe alternatives you've considered**
Well, I guess that other alternatives are not possible, but maybe some guides and inspirations:

- https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/
- https://github.com/matiassingers/awesome-readme

**Additional context**
n/a

**Comment by tulup-conner** [comment]
I'll take this - let me know if you have anything particular in mind

**Comment by tulup-conner** [comment]
@rluders Can you close this? I failed to add a resolves note in the PR
