### ISSUE TITLE
[components] Drawer

### ISSUE THREAD

**Issue by NoHaxito** [themesberg/flowbite-react#340]
We need to implement the Drawer Label component as described in the core library.
https://flowbite.com/docs/components/drawer/

**Describe the solution you'd like**

PR must have:

- Component (w/ Theme support)
- Storybook
- Documentation
- Unit test

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dhensen** [comment]
Why is drawer not/no longer in this repo? https://github.com/themesberg/flowbite-react/commit/6e2b0911ce566b3ec91ebd775fbfde7047669f36

**Comment by rluders** [comment]
However, there is a PR to implement it: https://github.com/themesberg/flowbite-react/pull/1265

**Comment by dhensen** [comment]
@rluders I messed up when copy pasting link earlier, I wanted to point out [drawer being commented out in components.tsx](https://github.com/themesberg/flowbite-react/blob/ce257913c9ee3c6d52b6acf829d5b4688f0a6fc4/data/components.tsx#L298)

Thanks for the link to #1265  👍

**Comment by rluders** [comment]
@dhensen yet, it was never available as a component here. It is just commented in the sidebar to make it easy to enable it when it gets created.
