### ISSUE TITLE
Page scroll to Tabs.Group Component

### ISSUE THREAD

**Issue by itsaboutcode** [themesberg/flowbite-react#345]
**Describe the bug**
I have created a page, which included a component composed of `Tabs.Group` and placed it in the middle of the page. Now when I open this page, the page scroll to that component for no reason. Any idea why it's happening? 

**Project information:**

```
   "flowbite": "^1.5.2",
    "flowbite-react": "^0.1.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

**Comment by rluders** [comment]
Could you provide some example? Code? Vídeo? What browser are you using? And so...

**Comment by 2-fly-4-ai** [comment]
I have the same issue. 

When opening a new page, if it contains the flowbite-react Tabs component it will open on that element rather than the top of page as expected.

**Comment by lytonist** [comment]
Same to me. Even if you go to the docs page at https://flowbite-react.com/tabs focus goes to last tabs first item

**Comment by rluders** [comment]
Probably solved. At least at `0.4.10` it isn't happening at the documentation anymore.
