### ISSUE TITLE
Dropdown don't close on select

### ISSUE THREAD

**Issue by VlodkoMr** [themesberg/flowbite-react#349]
**Describe the bug**
I use Dropdown and when select item from this dropdown, it is still opened. 
Documentation also don't have any information how can we do it.

Reproduce:
- Click on dropdown to open it.
- Click on any option element
- Result: nothing changed. Action that was added as onClick for Dropdown.Item work but dropdown is opened.

**Project information:**

- Tailwind: 3.1.8
- Flowbite: 1.5.3
- Flowbite React: 0.1.10

**Comment by Nefarioum** [comment]
I am experiencing the same issue with this. Is there some sort of way I can hide it temporarily for now until a fix is release?

**Comment by AstrisDev** [comment]
I am experiencing with this bug too. Is any idea how to close dropdown on item click?

**Comment by thedaviddias** [comment]
Up!

**Comment by tiagossa1** [comment]
+1

**Comment by vonnue-be** [comment]
+1

**Comment by ShaneMaglangit** [comment]
Can I work on this?

**Comment by rluders** [comment]
Sure, @ShaneMaglangit

**Comment by thiendang-webtretho** [comment]
+1

**Comment by thiendang** [comment]
+1

**Comment by sazzer** [comment]
I've got the same problem. However, I'm putting navigation links into my dropdown - courtesy of react-router - and I'm finding that once I've used one of these links the dropdown not only remains open but doesn't close if I click outside it. The only way to close it is to click on the opener button again. The dropdown *does* close when clicking outside it before I click on one of these links though.

I'm *assuming* that the `Dropdown.Item` has an `onClick` to cause the menu to close, and that something is going wrong with it when the item has other functionality as well.

**Comment by ShaneMaglangit** [comment]
@sazzer actually, its precisely that `Dropdown.Item` does not have any functionality that updates the state of the floating menu. It is nothing more than a wrapper to a `<li>` element. The way that it is designed to be entirely independent of `Dropdown` makes it challenging to add that, since it would require passing the `setOpen` of `Floating` to its children.

I do have a proposed solution but I've had problems with `commitlint` when trying to commit my changes. Haven't really had the extra time to sort it out, so it remains on my local environment.

**Comment by donnguyen** [comment]
We might need to completely re-implement the Dropdown component. `React DOM Interactions` now support a tree with nested item, it could be a good way to go, the example is available here: https://codesandbox.io/s/admiring-lamport-5wt3yg?file=/src/DropdownMenu.tsx

**Comment by rluders** [comment]
PR is very welcome to fix this one.

**Comment by sayinmehmet47** [comment]
+1

**Comment by ShaneMaglangit** [comment]
@rluders perhaps we can add the hacktoberfest tag on the repo to attract more help on this?

**Comment by vylink** [comment]
+1

**Comment by fs-innonova** [comment]
+1 please

**Comment by WenLonG12345** [comment]
+1

**Comment by nsoubelet** [comment]
@sazzer @ShaneMaglangit To me this is the kind of issues one could find when designing using a composite approach with cisolation, I mean, separating components completely. In this case `Dropdown` knows nothing about `Dropdown.Item`s and viceversa.
I rather prefer to think of events, therefore `Dropdown.Item`s could handle clicks internally and first notify it's parent (`Dropdown`) and then execute component's handler function.

@ShaneMaglangit instead of passing down `setOpen` to children, would not it be cleaner to only notify parent and let it decide so concerns keep separated?

**Comment by ShaneMaglangit** [comment]
@nsoubelet May you clarify what is your proposed solution? How can we achieve that effect?

Based on how I initially understood your suggestion, propagating `setOpen` is doing exactly what you hope to achieve. The Dropdown container is notified of the event when `setOpen` is called.

**Comment by nsoubelet** [comment]
@ShaneMaglangit  I did not say your solution won't work, I just said that maybe a better practice would be notify `Dropdown` instead calling `setOpen` in a child component.
`open` is a `Dropdown` inner property and **ideally** should be changed and only visible by the component itself.

Having said that, I agree with you the effect will be the same using either style and we all need this fixed ASAP.

**Comment by ShaneMaglangit** [comment]
> @ShaneMaglangit I did not say your solution won't work, I just said that maybe a better practice would be notify `Dropdown` instead of calling `setOpen` in a child component. `open` is a `Dropdown` inner property and **ideally** should be changed and only visible by the component itself.
> 
> Having said that, I agree with you the effect will be the same using either style and we all need this fixed ASAP.

I do have a proposed solution in my local environment, I'll try to deal with the issues so I can submit a PR tonight.

I do understand what you are suggesting. However, I'm having trouble figuring out how to do this precisely on React. If you can clarify how to do this, perhaps I can modify my work a bit. To clarify, how can we notify the Dropdown from DropdownItem without my initial idea?

**Comment by nsoubelet** [comment]
> > @ShaneMaglangit I did not say your solution won't work, I just said that maybe a better practice would be notify `Dropdown` instead of calling `setOpen` in a child component. `open` is a `Dropdown` inner property and **ideally** should be changed and only visible by the component itself.
> > Having said that, I agree with you the effect will be the same using either style and we all need this fixed ASAP.
> 
> I do have a proposed solution in my local environment, I'll try to deal with the issues so I can submit a PR tonight.
> 
> I do understand what you are suggesting. However, I'm having trouble figuring out how to do this precisely on React. If you can clarify how to do this, perhaps I can modify my work a bit to better align with your idea.
> 
> To be clear, I would appreciate it if you can explain how to notify Dropdown from DropdownItem aside from propagating `setOpen`?

Something like this:

In `Dropdown` component
```
const handleClickDropDown = () => {
  setOpen(!open);
}
```
In `Dropdown.Item` component
```
const handleClickItem = () => {
  handleClickDropDown();
  itemClickHook();
}
```
`handleClickDropDown` you pass same way you are planning to pass `setOpen`.
`itemClickHook` is the function that comes from the top-level component, passed in `onClick` prop. In this approach item handles the click internally, notify it's parent and then continues upstream.

**Comment by rluders** [comment]
Some reference:
https://github.com/fraserxu/react-dropdown/blob/master/index.js

**Comment by ShaneMaglangit** [comment]
> > > @ShaneMaglangit I did not say your solution won't work, I just said that maybe a better practice would be notify `Dropdown` instead of calling `setOpen` in a child component. `open` is a `Dropdown` inner property and **ideally** should be changed and only visible by the component itself.
> > > Having said that, I agree with you the effect will be the same using either style and we all need this fixed ASAP.
> > 
> > 
> > I do have a proposed solution in my local environment, I'll try to deal with the issues so I can submit a PR tonight.
> > I do understand what you are suggesting. However, I'm having trouble figuring out how to do this precisely on React. If you can clarify how to do this, perhaps I can modify my work a bit to better align with your idea.
> > To be clear, I would appreciate it if you can explain how to notify Dropdown from DropdownItem aside from propagating `setOpen`?
> 
> Something like this:
> 
> In `Dropdown` component
> 
> ```
> const handleClickDropDown = () => {
>   setOpen(!open);
> }
> ```
> 
> In `Dropdown.Item` component
> 
> ```
> const handleClickItem = () => {
>   handleClickDropDown();
>   itemClickHook();
> }
> ```
> 
> `handleClickDropDown` you pass same way you are planning to pass `setOpen`. `itemClickHook` is the function that comes from the top-level component, passed in `onClick` prop. In this approach item handles the click internally, notifies its parent and then continues upstream.

I see, I better understand what you meant now. I've seen debates about this but in the end, it is just a matter of preference whether to pass setState directly or wrap it in a function. Either way, I ended up not following this in my PR.

> Some reference:
> https://github.com/fraserxu/react-dropdown/blob/master/index.js

@rluders I believe this reference has a very different structure than our implementation. Thus, isn't really transferable to this. I did submit a PR, please do check it out and let me know your thoughts about it.

**Comment by rluders** [comment]
I'll check the PR later. Or if someone else is interested in testing it and reviewing it I'll also accept it.

I must say that I do prefer it done than perfect. We can rework the component if we felt that it is too complicated or if it doesn't fully match our expectations. 

I guess that our main goal here is to relieve the existing pain and let users close the Dropdown by:

- Clicking outside the dropdown;
- Selecting an Item;
- Pressing `ESC`;

What do you folks think?

**Comment by rluders** [comment]
Thanks @ShaneMaglangit for the hard work on this one.

**Comment by nigellima** [comment]
Am I mistaken or has [this](#392 ) fix been overridden? 

On the website and in the latest version of the library, the Dropdown component still does not close when clicking on an option or by pressing Esc

**Comment by JCAdkins** [comment]
I ran into this issue just recently and while looking into DropDown.js code I saw that there is a DropDownItem.js. This was intriguing as flowbite-react.com has the code implemented with an <Item>. I replaced the <Item> with a <DropDownItem> and the issues was fixed.

**Comment by swee76** [comment]
I have a dropdown that opens when I click on a TextInput. However, when I change the selected item in the dropdown, it doesn't close when I click outside of it, even though I've used dismissOnClick. How can I make the dropdown close when changing the selected item and clicking outside? Additionally, I'd like to confirm that I've correctly used the renderTrigger method to include a TextInput as the trigger for the dropdown.
