### ISSUE TITLE
Cypress + Axe testing

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#35]
**Is your feature request related to a problem? Please describe.**
I believe that is important for us to have some automated tests. Since we do have the docs pages it should not be complicated to test the behaviors of the components. The test must cover usability and accessibility.

**Describe the solution you'd like**
- Install Cypress
- Install Axe
- Create at least ONE example test

**Describe alternatives you've considered**
I don't know any alternative.

**Additional context**
The [Sumé LMS frontend](https://github.com/sumelms/frontend) already has those tests on it, maybe it would be easy to just bring them to this repository. Also, there is [this guide](https://www.deque.com/blog/how-to-test-for-accessibility-with-cypress/), that can be useful.

**Comment by tulup-conner** [comment]
I think Cypress would be fantastic. The Jest DX is inferior, but tests will take longer. Would the plan be to migrate all tests to Cypress? I'm trying to imagine how you would distinguish unit tests from end-to-end in a library like this.

**Comment by rluders** [comment]
No, we will not migrate any unit test to Cypress. Both have different proposals.

The plan is to use Cypress + Axe to test the components by interacting with Storybook and the Documentation. By doing it we can also check a11y aspects.

**Comment by tulup-conner** [comment]
Ok, what would an example Cypress test actually look like then? I'm a bit confused by that explanation. Would you repeat the behavioral tests of the unit tests, just on the Storybook pages?

**Comment by rluders** [comment]
Let me give you one scenario:

**Test button documentation page**
- Open the documentation page
- Navigate to the carousel page
- Check if it all examples are correctly being rendered
- Check if you can interact with the examples

> This is a very, very, very basic scenario, since I'm not QE :)

**Comment by tulup-conner** [comment]
Yeah that makes perfect sense, you mean to use these purely to test the Storybook/docs pages themselves. I'm silly

**Comment by rluders** [comment]
'Cause, by doing it, we are also testing our components and it's the desired behavior. Right? :)
