### ISSUE TITLE
Missing avatar with placeholder initials

### ISSUE THREAD

**Issue by tiagossa1** [themesberg/flowbite-react#357]
**Describe the solution you'd like**

Flowbite React's Avatar component does not provide an avatar that has placeholder initials, unlike flowbite. E.g. https://flowbite.com/docs/components/avatar/ - see "Placeholder Initials".
The solution could be: instead of passing an image URL, Avatar could have another prop called "placeholderInitials" or similar where the developer passes the initials as a string.
Internally:
- If "img" props was provided, display the avatar with an image.
- If "placeholderIntitials" was provided, display the the initials only.

An suggestion: both should not be filled. If they are, avatar with an image should be display or just throw an error.

**Comment by iamargentum** [comment]
hi @rluders !
can  i work on this issue?

**Comment by rluders** [comment]
@iamargentum go ahead.
