### ISSUE TITLE
Tooltips are behind tables

### ISSUE THREAD

**Issue by phbernard** [themesberg/flowbite-react#359]
**Describe the bug**
When displayed, tooltips are supposed to appear in front of anything else. However, they are behind tables:

![image](https://user-images.githubusercontent.com/423852/191195612-e1b53206-7489-4f2e-9ed4-f2b248a160c2.png)

**To Reproduce**

1. Go to [Flowbite React website, Table page](https://flowbite-react.com/tables)
2. Reduce the brower's window
3. Collapse the sidebar
4. Hover a sidebar item

For example :

![image](https://user-images.githubusercontent.com/423852/191196371-d33fde60-a8aa-465f-a6af-8d90bc48b09b.png)

**Expected behavior**
The tooltip should appear in front of anything else. For example:

![image](https://user-images.githubusercontent.com/423852/191196547-549d6fc8-6526-409f-bbf8-f9c0baecd330.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/423852/191196371-d33fde60-a8aa-465f-a6af-8d90bc48b09b.png)

**System information:**

- Device: Laptop
- OS: Windows
- Browsers: Chrome, Firefox
- Versions: 105.0.5195.127 (Chrome) and 104.0.2 (Firefox)

**Project information:**

Unknown, please refer to whatever is in use with https://flowbite-react.com

**Comment by rluders** [comment]
@phbernard flowbite version?

**Comment by Chetan-B-B** [comment]
@rluders  assign this bug to me , I'm happy to work
