### ISSUE TITLE
Buttons outline does not match specification

### ISSUE THREAD

**Issue by fs-innonova** [themesberg/flowbite-react#361]
If we set the outline prop to true the Button component does not behave as in the docs

expected outcome:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/93779923/191533383-4b6a4070-4bc2-4b17-95da-2a0e0bb48914.png">

current outcome:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/93779923/191533542-78c7249a-52c7-4695-a70a-1d761be7c8d1.png">
 
Why is it so thick? Am I missing something? Thank you

**Comment by rluders** [comment]
Well, this is at least strange. I was checking the classes applied to the button and it should be forced to `focus:!ring-2` but the normal one is `focus:ring-4`, the same as standard flowbite docs.

Anyway, maybe we need to do some extra tailwind configuration or update some dependency?

**Comment by IamGideonIdoko** [comment]
@rluders Can I work on this?

**Comment by rluders** [comment]
@IamGideonIdoko go ahead
