### ISSUE TITLE
Unit test for FormControls

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#38]
**Is your feature request related to a problem? Please describe.**
The component is missing its unit test.

- [ ] Checkbox
- [ ] FileInput
- [ ] Label
- [ ] Radio
- [ ] Select
- [ ] TextInput
- [ ] TextArea
- [ ] ToggleSwitch

**Describe the solution you'd like**
Implement the unit test to the component.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tulup-conner** [comment]
I'll take these
