### ISSUE TITLE
Bug scrollIntoView stopped by carousel change

### ISSUE THREAD

**Issue by fogracvxy** [themesberg/flowbite-react#384]
**Describe the bug**
`javascript
const scrollTo = (element) => {
    const section = document.querySelector(element);
    section.scrollIntoView({ behavior: "smooth", block: "start" });
  };`

**To Reproduce**

Scroll randomly stops in the middle of the page sometimes it seems when picture in carousel is changed. What could produce this error. I tested it with changing slideInterval to 0 whole navigation stopped working... Same bug is with <a href=""....>. Could only be happening on Chromium.

**Expected behavior**
Not to stop when images changes.

**Screenshots**

**System information:**

- Device: WINDOWS PC
- Resolution: 2K
- OS: WINDOWS
- Browser: BRAVE / CHROME
- Version: LATEST

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Comment by rluders** [comment]
It could be related to #395

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
