### ISSUE TITLE
Export useTheme and useThemeMode from ThemeContext

### ISSUE THREAD

**Issue by myasteiner** [themesberg/flowbite-react#389]
**Is your feature request related to a problem? Please describe.**
I would like to have accessibility to the `useTheme` and `useThemeMode`, due to custom element styling. 

**Describe the solution you'd like**
Export `useTheme` and `useThemeMode` from `ThemeContext`.

**Describe alternatives you've considered**
The current workaround is to modify the ThemeContext files on `postinstall` with a script.

**Comment by rluders** [comment]
@myasteiner Can you provide a hypothetical example of how you will use the `useTheme` and `useThemeMode` in your scenario?

What are you expecting to achieve with this? How you are going to use it? Which type of customization are you looking for?

**Comment by myasteiner** [comment]
Hi @rluders , i've created a PR for it with the updated docs.

I would like to use the $`useTheme` hook and `useThemeMode` hook for custom components (e. g. custom form element). Therefore i would need to know the current theme mode but also colors in each mode. I want to ensure, that my own component is styled like Flowbite's components.
