### ISSUE TITLE
Novas animações

### ISSUE THREAD

**Issue by SperandioIcaro** [themesberg/flowbite-react#400]
Uma questão que sempre vi no tailwind é  sobre as animações disponibilizadas, e toda vez que quero adicionar uma animação diferente é precioso fazer do zero,

Seria interessante já adicionar essas animações, como animação de onda, gravidade 0 e etc..

**Comment by rluders** [comment]
@SperandioIcaro eu não entendi qual a requisição aqui. Poderia dar mais detalhes? Você quer adicionar animações onde? Qual componente? Se a ideia for expandir as animações que existem no TailwindCSS, imagino que esta não seja a proposta da biblioteca aqui em questão.
