### ISSUE TITLE
Theme with TS doesn't accept Partial<T>

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#408]
**Describe the bug**

I'm trying to extend the `FlowbiteTheme` to create my own theme using Typescript but it doesn't seems to be work as expected.

**To Reproduce**

1. Create a CRA project with TypeScript
2. Install flowbite-react `0.3.*`
3. Create a custom `theme.ts` (sample code bellow)
4. See it fail

```ts
import { FlowbiteTheme } from 'flowbite-react';

const theme: Partial<FlowbiteTheme> = {
  navbar: {
    base: 'border-gray-50 bg-white px-2 py-2.5 sm:px-4',
    rounded: {
      on: 'rounded',
      off: '',
    },
  },
};

export default theme;
```

**Expected behavior**

It should be possible to partially extend the theme without need to declare all theme properties.

**Screenshots**

![image](https://user-images.githubusercontent.com/191027/197396833-e29e33b2-293b-482f-acc4-8f29b3c6ac44.png)

**System information:**

N/A

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.3.2
- Type: CRA

**Additional context**

N/A

**Comment by rluders** [comment]
@tulup-conner could you please help on this one? Am I doing something wrong?

**Comment by tulup-conner** [comment]
Yeah, Partial is a shallow TypeScript Partial. In other words, it won't look for deeply nested members (i.e., further than one level deep). What you want is either the custom DeepPartial type I created, or to just use the CustomFlowbiteTheme type I also created. @rluders
