### ISSUE TITLE
Bug in the navbar

### ISSUE THREAD

**Issue by fomundifr** [themesberg/flowbite-react#410]
Hi, I'm seeing a bug and it's that when using the Navbar everything looks small and when you click on the avatar everything returns to normal, I don't know if it happens in all lerl it happens to me in Nextjs

**Comment by dubisdev** [comment]
Same here!

I'm using nextjs too. I see the error when I use the navbar with the avatar component. When I use it with something different like a button it works fine.

**Comment by rluders** [comment]
Folks, we do have a template for bugs, when you are creating an issue. Please use it. I can't actually work on those issues if I don't have enough information to reproduce the issue. Please, @fomundifr, edit your issue as [use this template](https://raw.githubusercontent.com/themesberg/flowbite-react/main/.github/ISSUE_TEMPLATE/bug_report.md) and fill up as much info as possible.
