### ISSUE TITLE
How to customize file input button color?

### ISSUE THREAD

**Issue by sayinmehmet47** [themesberg/flowbite-react#419]
**Is your feature request related to a problem? Please describe.**
I can not change the color of the choose file button which is inside form file input component. 
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/75525090/199091206-48505e12-e207-45fe-9a5d-8a21c33cbe7b.png">

https://flowbite-react.com/storybook/?path=/docs/components-formcontrols--default-file-input

**Describe the solution you'd like**
I want to customize the color of the button from black to other colors

**Describe alternatives you've considered**
Component can take a button color that enable color customization of the button

**Additional context**
No

**Comment by rluders** [comment]
@sayinmehmet47 you can customize if by adding a class to the component and then customize if with CSS using it.

```jsx
<FileInput className="custom-fileinput" />
```

```css
.custom-fileinput input { ... }
```

Or you can use the theme support to customize it, if the style is going to be the same for all your `FileInput` components.

**Comment by singhay** [comment]
This does not work, the CSS classes here override that of Tailwind as a side-effect

```
<FileInput className="block w-full text-sm text-violet-900 border border-violet-300 rounded-lg cursor-pointer bg-violet-50 " />
```

```
<input className="block w-full text-sm text-violet-900 border border-violet-300 rounded-lg cursor-pointer bg-violet-50 file:bg-violet-50 file:text-violet-700
      hover:file:bg-violet-100" aria-describedby="file_input_help" id="file_input" type="file" onChange={handleFileChange} />
```

Tailwind 3
Flowbite 2.X.X
