### ISSUE TITLE
Use of primary and secondary color key

### ISSUE THREAD

**Issue by ritechoice23** [themesberg/flowbite-react#423]
I want to say a big well-done job to the entire team working on this great project. my suggestion is on color, can the color key used in the component be changed to something like primary and secondary instead of using tailwind's default blue and the like?

**Comment by rluders** [comment]
Well, you can actually extend the `FlowbiteColors` and add as much colors you like to for your theme, and use it as `primary` and `secundary`.

https://github.com/themesberg/flowbite-react/blob/0e4ae62b2b93561c4857bea63df45fe9170f546e/src/lib/components/Flowbite/FlowbiteTheme.ts#L514
