### ISSUE TITLE
Next.js Sidebar Multi-level dropdown Tooltip Overlap

### ISSUE THREAD

**Issue by arkmech** [themesberg/flowbite-react#429]
**Describe the bug**
Condition: Sidebar Collapsed State Hovering over items in a dropdowns
Tooltips do now show correctly

**To Reproduce**
Have sidebar collapsed and have multi-level dropdown expanded, then hover over the elements

**Screenshots**
Not Collapsed: Good
<img width="277" alt="Screenshot 2022-11-12 at 1 18 27 AM" src="https://user-images.githubusercontent.com/114366662/201460450-ca28adc5-5aed-498c-9964-9e455a831549.png">

Collapsed hovering over Parent: Good
<img width="157" alt="Screenshot 2022-11-12 at 1 18 06 AM" src="https://user-images.githubusercontent.com/114366662/201460464-8d4c3795-b0b9-49c9-9792-b392845a8fec.png">

Collapsed hovering over Dropdown Item: Bad
<img width="186" alt="Screenshot 2022-11-12 at 1 18 21 AM" src="https://user-images.githubusercontent.com/114366662/201460494-aea5e8cd-18b6-42ba-9b2f-a7545c272630.png">

**System information:**

- Device: Macbook Pro 2018
- Resolution:
- OS: Ventura 13.0.1
- Browser: Google Chrome
- Version:

**Project information:**

- Tailwind: 3.2.3
- Flowbite: 1.5.3
- Flowbite React: 0.3.4
- Type: Next.js 13.0.2 (Using backwards compatible pages router)

**Additional questions**
1. Possibly of adding icons to dropdown items?
2. How do I get the Sidebar Navigation to use Next.js Link component?

**Comment by rluders** [comment]
I want to get the #430 solved first, 'cause I think that we could have some overlap here. But I could be wrong.

**Comment by tulup-conner** [comment]
Hey @arkmech I fixed this in a new PR which you will see linked below.
