### ISSUE TITLE
Maximum update depth exceeded with Next/Link and SidebarItem

### ISSUE THREAD

**Issue by myasteiner** [themesberg/flowbite-react#430]
**Describe the bug**
I opened a bug ticket here, see: https://github.com/vercel/next.js/issues/42902

**To Reproduce**
See: https://codesandbox.io/p/sandbox/hopeful-thompson-1lw449

**Expected behavior**
That it only renders once.

**Additional context**
This problem is occuring, because we're currently creating Components inside of other Components for e. g.: https://github.com/themesberg/flowbite-react/blob/v0.3.4/src/lib/components/Sidebar/SidebarItem.tsx#L34-L56

**Comment by rluders** [comment]
@myasteiner I think that we can try. Do you want to create a PR for it? I guess that we also going to need to update the doc/example page and storybook. Right?
