### ISSUE TITLE
Dropdown menu does not close when passing onclick event to Dropdown component

### ISSUE THREAD

**Issue by sayinmehmet47** [themesberg/flowbite-react#432]
I have passed onclick event to Dropdown to understand if dropdown is open or not. 

``` js
  <Dropdown
        arrowIcon
        color="light"
        onClick={() => setIsOpen(!isOpen)}
        label={
          <span className="truncate max-w-[150px] md:w-full text-left">
            {project?.name || c('select-project')}
          </span>
        }
        placement="bottom-start"
        size="xs"
      >

```
But when I pass onclick to that component, I cant  close the dropdown in mobile size. It works on desktop mode

![image](https://user-images.githubusercontent.com/75525090/195569842-cebd5df0-d769-4aad-9bda-dbebc37d630f.png)

Is there any other way to find if dropdown open or close??

**Comment by rluders** [comment]
flowbite-react version? Can you provide a working example? Codepen or something helps a lot.

**Comment by rluders** [comment]
I'm not sure about this one, 'cause there was no more info from users. So... I'm assuming that it could be related to #451 - I'm closing this one.
