### ISSUE TITLE
Export all components interface/types to `flowbite-react`

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#433]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to handle some data from API or configurations that will later be passed to a flowbite-component. In this case, I would like to convert this data to the component property types.

**Describe the solution you'd like**
All interfaces/types used by flowbite components must be exported as types to the default package.

**Describe alternatives you've considered**
None.

**Additional context**
One good example is when you are using the `react-router` to create the `Breadcrumb` and you need to handle some logic to the data to apply it to the `Breadcrumb. Item`. I can't import the `BreadcrumbItemProps` directly from the `flowbite-react` package.

**Comment by rluders** [comment]
BTW, the goal is to allow this:

```ts
import Navbar, { NavbarProps } from 'flowbite-react';
```

**Comment by Rafaelb4rros** [comment]
Hello, I would love to do this issue. The best place to export the types is from the 'index' file on the 'components' folder right?

**Comment by rluders** [comment]
@Rafaelb4rros I think that the existing `export * from `./Component'` that we have at the `index.ts` is already doing it. But, I'm not sure why it isn't working for all the components interface.

It seems that it only exports the interface from the main component at the folder, ignoring the subcomponents.

I would like to have it all the components and interfaces exported. So, maybe just by doing some `export * './Component/Subcomponent';` would be enought.

**Comment by Rafaelb4rros** [comment]
> @Rafaelb4rros I think the existing `export * from './Component'` that we have at the `index.ts` is already doing it. But, I'm not sure why it isn't working for all the components' interfaces.
> 
> It seems that it only exports the interface from the primary component in the folder, ignoring the subcomponents.
> 
> I would like to have all the components' interfaces exported. So, maybe just doing some `export * './Component/Subcomponent';` would be enough? Not sure, 'cause we don't want to export the subcomponents only their interfaces.

Yes, only the types of the primary component is being exported correctly: 
![image](https://user-images.githubusercontent.com/80357541/202287740-9334f2ba-6395-4cc3-98f7-6f85713791b2.png)
I think doing like you said will solve it.

**Comment by rluders** [comment]
For `Breacrumb` component it should look like this:

```ts
export type { BreadcrumbItemProps } from './BreadcrumbItem'
export * from './Breadcrumb';
```

**Comment by Rafaelb4rros** [comment]
is this a typo error? 
![image](https://user-images.githubusercontent.com/80357541/202289187-592fef5f-2fb3-4a87-9960-0b2ca13f0d0e.png)
should i fix it?

**Comment by Rafaelb4rros** [comment]
tem outro problema, alguns componentes são exportados "diretamente": 
![image](https://user-images.githubusercontent.com/80357541/202308414-778ee00c-8ad4-4ef1-9fd2-8dc9a8ef9b5a.png)
o ideal seria trocar o import para o arquivo Index: `export * from './Accordion';`

**Comment by Rafaelb4rros** [comment]
> some components are being exported "directly": ![image](https://user-images.githubusercontent.com/80357541/202308414-778ee00c-8ad4-4ef1-9fd2-8dc9a8ef9b5a.png) the solution would be export the Index file: `export * from './Accordion';`

and there are some primary components that are not being exported on the `components` index file, like the `Floating` component, this breaks the types import: 
![image](https://user-images.githubusercontent.com/80357541/202311961-784e56bd-145d-400f-892e-5d25d29ccd7b.png) 
we can export the `Floating` component like the others:
![image](https://user-images.githubusercontent.com/80357541/202312537-e8666ead-3cff-46e7-bf48-99eba7a3a5fa.png)
