### ISSUE TITLE
Textfield Icon Position

### ISSUE THREAD

**Issue by DaRabus** [themesberg/flowbite-react#436]
**Is your feature request related to a problem? Please describe.**

While using the TextField Input from your repository i figured it there is right now only a way to display the Icon on the left side.

![image](https://user-images.githubusercontent.com/44967066/202989630-10d747e7-5587-44da-a6b0-3114faadf9b8.png)

**Describe the solution you'd like**
I would like to introduce an optional parameter which sets the position of the Icon on the "left/right" side. 

**Additional context**

![image](https://user-images.githubusercontent.com/44967066/202999327-5595be0f-7040-4d7b-ae09-dbf102d9415a.png)

**Comment by rluders** [comment]
I like this idea. It should be pretty easy to implement.

Once the `TextInput`'s base style is `flex`, we can probably just change the [order](https://tailwindcss.com/docs/order) of the elements based on the given property.

https://github.com/themesberg/flowbite-react/blob/dadd5b9c2a9298281a56bc85ce8e47319c941da2/src/lib/theme/default.ts#L384

**Comment by rluders** [comment]
So, @myasteiner, in this case, we can have two "addon" per field, right? So it would be something like:

```jsx
<TextInput rightIcon={<MyRightIcon />} leftIcon={<MyLeftIcon /> ... />
````

Let me ask another thing... Do we want to somehow interact with those add-ons? By clicking or something?

```jsx
<TextInput rightIcon={<MyRightIcon onClick={doSomething} />} leftIcon={<MyLeftIcon /> ... />
````

**Comment by DaRabus** [comment]
I created a draft PR for this one, still gotta do some tests, so it doesn't crash anything else, but should be easy like this to implement.

Might be something for you to consider to refactor in a future approach to make it easier and more generic

**Comment by DaRabus** [comment]
Added some examples to the docs and tested it so far :)

@rluders
