### ISSUE TITLE
Overriding the default background of Navbar component with custom colors is not working

### ISSUE THREAD

**Issue by sami3ullah** [themesberg/flowbite-react#442]
**The Problem**
I am trying to change the background of a `<Navbar>` component of Flowbite(which is based on tailwind, so it doesn't matter). when I am giving it my custom as "bg-primary" it's not working but "bg-secondary" is working which is also my custom color. It's happening for some other colors as well.

**To Reproduce**
Link to the repo: https://github.com/sami3ullah/amplify-basics

**Expected behavior**

**System information:**

- OS: Ubuntu 20.0
- Browser: Chrome

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.5.4
- Flowbite React: 0.3.5

**Things I tried**
- Restarting the server
- Changing the names of the colors
- Tried the plain HTML component of Flowbite, and it's working fine. But react one is not

**My tsconfig**
```js
** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: ["Graphik", "sans-serif"],
    },
    extend: {
      colors: {
        primary: "#F28157",          //not working 
        darkprimary: "#BF665E",      // not working
        secondary: "#04BF9D",        //working 
        darksecondary: "#03A696",    // working
        darkgrey: "#191718",         // not working
        blueishsecondary: "#253659", // not working
      },
    },
  },
  plugins: [require("flowbite/plugin")],
};
```
**Using the Flowbite react component like this**
```js
<Navbar fluid={true} rounded={true} className="bg-secondary">
      <Navbar.Brand href="/">
        <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">
          Prognosus
        </span>
      </Navbar.Brand>
      <div className="flex md:order-2">
        <Dropdown
          className="bg-darkgrey"
          arrowIcon={false}
          inline={true}
          label={
            <Avatar
              alt="User settings"
              img="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
              rounded={true}
            />
          }
        >
          <Dropdown.Header>
            <span className="block text-sm">Bonnie secondary</span>
            <span className="block text-sm font-medium truncate">
              name@flowbite.com
            </span>
          </Dropdown.Header>
          <Dropdown.Item>Dashboard</Dropdown.Item>
          <Dropdown.Item>Settings</Dropdown.Item>
          <Dropdown.Item>Earnings</Dropdown.Item>
          <Dropdown.Divider />
          <Dropdown.Item>Sign out</Dropdown.Item>
        </Dropdown>
        <Navbar.Toggle />
      </div>
      <Navbar.Collapse>
        <Navbar.Link href="/navbars" active={true}>
          Home
        </Navbar.Link>
        <Navbar.Link href="/navbars">About</Navbar.Link>
        <Navbar.Link href="/navbars">Services</Navbar.Link>
        <Navbar.Link href="/navbars">Pricing</Navbar.Link>
        <Navbar.Link href="/navbars">Contact</Navbar.Link>
      </Navbar.Collapse>
    </Navbar>
```

**Comment by rluders** [comment]
1. Did you check if you can use the custom colors anywhere else?
2. Did you try to overwrite the colors using the flowbite-react theme system?
3. Did you try to make the `className="!bg-customColorName'` important?

**Comment by sami3ullah** [comment]
> 2\. Did you try to overwrite the colors using the flowbite-react theme system?

Isn't it the same as tailwind? I checked the Flowbite docs. It's configured the same way as of tailwind https://flowbite.com/docs/customize/theming/. Or maybe I am missing something(please correct me if I am).

> 3\. Did you try to make the `className="!bg-customColorName'` important?

It works with `!` but I don't want to use `!important` everywhere. Even if this is the case, I am failing to understand why it's working for some colors and why it's not for other colors? i.e: why do I need to write `!bg-primary` and not for `bg-secondary`.

One more thing I forgot to mention, which is that in dev tools, when my custom color is not applied then somehow the specificity of it is less, that is why it is overridden by the  default color `bg-white`

**Comment by rluders** [comment]
@sami3ullah, not the standard flowbite/tailwindcss theming. OK. You should probably be able to use it to create your own custom styles/CSS classes, but if you want to customize the flowbite-react component style without using the `className` in a way to make it a little bit more consistent. I do recommend you use this: https://flowbite-react.com/theme

You can check the flowbite-react documentation source code as an example of how to use the theme system, or I'm pretty sure you'll find some help at the Flowbite Discord server as well.

**Comment by rluders** [comment]
Also, I want to point you to #443 that I just created. The idea is to extend the theme support to allow some theme overwriting per component, so the styling for specific-custom components can be easier.

**Comment by tulup-conner** [comment]
You can achieve this with `className="!bg-X"` or by providing a `<Flowbite theme={..}>` with `bg-X` in the `navbar.root.base` key.

**Comment by alvindera97** [comment]
> It works with `!` but I don't want to use `!important` everywhere. Even if this is the case, I am failing to understand why it's working for some colors and why it's not for other colors? i.e: why do I need to write `!bg-primary` and not for `bg-secondary`.

It still doesn't work for example `className="!bg-cyan-700"` does not work! Besides, the "theming" you're recommending is "highly experimental".
