### ISSUE TITLE
Theme overwrite per component

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#443]
**Is your feature request related to a problem? Please describe.**

Today we do have the [flowbite-react theme[(https://flowbite-react.com/theme) that can be used to customize the components and also direct access to component `className`.

The problem with this approach is that using the `className` you can only apply custom classes to the `root element component` (normally the one with `theme.base`), and you need to sometimes use `!important` tag to overwrite some existing styles. This is OK for small customizations, or if you don't mind writing some CSS.

> **Note** 
> You could add to your component using `className` a custom class as `.my-custom-class` and overwrite all the component styles with CSS.

Also, the theme support is great, and it helps to keep the UI consistent, but it also leads you to not be able to create multiple component styles that can be reused. In this case, with the theme component, you can customize every single item inside the component, access its defined theme property styles, and even extend some of them. But, this style will be shared between all components, and today you can't apply custom themes per component, which is painful.

**Describe the solution you'd like**

Allow the user to create custom component themes that can be individually applied and fully overwrite the main flowbite-react theme for one specific component.

Example of usage:

```tsx

const AccordionCustomTheme =  {
    base: 'divide-y divide-gray-200 border-gray-200 dark:divide-gray-700 dark:border-gray-700',
    content: {
      base: 'py-5 px-5 last:rounded-b-lg dark:bg-gray-900 first:rounded-t-lg',
    },
    flush: {
      off: 'rounded-lg border',
      on: 'border-b',
    },
    title: {
      arrow: {
        base: 'h-6 w-6 shrink-0',
        open: {
          off: '',
          on: 'rotate-180',
        },
      },
      base: 'flex w-full items-center justify-between first:rounded-t-lg last:rounded-b-lg py-5 px-5 text-left font-medium text-gray-500 dark:text-gray-400',
      flush: {
        off: 'hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:hover:bg-gray-800 dark:focus:ring-gray-800',
        on: '!bg-transparent dark:!bg-transparent',
      },
      heading: '',
      open: {
        off: '',
        on: 'text-gray-900 bg-gray-100 dark:bg-gray-800 dark:text-white',
      },
    },
};

// ...

return (
<Accordion theme={AccordionCustomTheme}>
  <Accordion.Panel>
    <Accordion.Title>What is Flowbite?</Accordion.Title>
      <Accordion.Content>
        <p className="mb-2 text-gray-500 dark:text-gray-400">
          Flowbite is an open-source library of interactive components built on top of Tailwind CSS including buttons,
          dropdowns, modals, navbars, and more.
        </p>
        <p className="text-gray-500 dark:text-gray-400">
          Check out this guide to learn how to{' '}
          <a
            href="https://flowbite.com/docs/getting-started/introduction/"
            className="text-blue-600 hover:underline dark:text-blue-500"
          >
            get started
          </a>{' '}
          and start developing websites even faster with components on top of Tailwind CSS.
      </p>
    </Accordion.Content>
  </Accordion.Panel>
</Accordion>
)

```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Related issues**

- [X] AccordionTheme (#450)
- [X] AlertTheme (#450)
- [X] AvatarTheme (#450)
- [X] AvatarGroupTheme (#450)
- [X] BadgeTheme (#450)
- [X] BreadcrumbTheme (#450)
- [X] ButtonTheme (#450)
- [X] ButtonGroupTheme (#450)
- [X] CardTheme (#450)
- [X] CarouselTheme (#450)
- [X] DarkThemeToggleTheme (#450)
- [X] DropdownTheme (#450)
- [X] FloatingTheme (#450)
- [X] FooterTheme (#450)
- [X] HelperTextTheme (#450)
- [X] ListGroupTheme (#450)
- [X] ModalTheme (#450)
- [X] NavbarTheme (#450)
- [X] PaginationTheme (#450)
- [X] ProgressTheme (#450)
- [X] RatingTheme (#450)
- [X] SidebarTheme (#450)
- [X] SpinnerTheme (#450)
- [X] TabTheme (#450)
- [X] ToastTheme (#450)
- [X] TooltipTheme (#450)
- [x] #452
- [x] #453
- [x] #454
- [x] #455
- [x] #456
- [x] #457
- [x] #458
- [x] #459
- [x] #460
- [x] #461
- [x] #462
- [ ] #465

**Comment by sldk-yuri** [comment]
@rluders I've tested the case where we may add `theme` prop to each component and than deepcopy the `useTheme()` result and deepMerge with `theme` prop object.

```typescript
export interface AccordionProps extends PropsWithChildren<ComponentProps<'div'>> {
  alwaysOpen?: boolean;
  arrowIcon?: FC<ComponentProps<'svg'>>;
  children: ReactElement<AccordionPanelProps> | ReactElement<AccordionPanelProps>[];
  flush?: boolean;
  theme?: DeepPartial<FlowbiteTheme['accordion']>;
}

const AccordionComponent: FC<AccordionProps> = ({
  alwaysOpen = false,
  arrowIcon = HiChevronDown,
  children,
  flush = false,
  className,
  theme: customTheme = {},
  ...props
}): JSX.Element => {
  const [isOpen, setOpen] = useState(0);

  const systemTheme: FlowbiteTheme['accordion'] = JSON.parse(JSON.stringify(useTheme().theme.accordion));
  const theme = mergeDeep(systemTheme, customTheme);

  // ...
```

And we may use component like this 
```typescript
  <div className="space-y-8">
    <Accordion
      theme={{
        base: 'divide-y-4 divide-rose-200 border-rose-200 dark:divide-rose-700 dark:border-rose-700',
      }}
    >
        // ...
    </Accordion>

    <Accordion>
        // ...
    </Accordion>
  </div>
```
![image](https://user-images.githubusercontent.com/118747540/204549262-d0b6b589-ab21-4a81-b34a-f470d863b309.png)

What do you think about that?

**Comment by rluders** [comment]
@sldk-yuri In general it looks good. I do have two questions:

- Do we really have to `JSON.stringfy` and `JSON.parse` the component theme object?
- Do we need to access FlowbiteTheme['accordion'] like this? Is it to get the object type?

**Comment by sldk-yuri** [comment]
1) we have to deepcopy the object otherwise we will work with the same object `src/lib/theme/default.ts` and mutate it, all updates will be global. `JSON.parse(JSON.stringfy())` is naive solution, the main thing is clone object deep so we may change/update code ([lodash`s cloneDeep()](https://lodash.com/docs/4.17.15#cloneDeep)?). 
2) I've use `FlowbiteTheme['accordion']` to add correct type for the `systemTheme` becouse JSON methods return `any`. `theme?: DeepPartial<FlowbiteTheme['accordion']>;` to add correct type for `theme` prop so we can choose only accordion related theme keys.

we probably may divide Flowbite Theme interface  
https://github.com/themesberg/flowbite-react/blob/104d6fb83bd48de696c2b79138640e747e5b020f/src/lib/components/Flowbite/FlowbiteTheme.ts#L33-L53
to components pieces to avoid `FlowbiteTheme['accordion']` and make code more readable. For example:

```typescript
export interface AccordionTheme {
  base: string;
  content: {
    base: string;
  };
  flush: FlowbiteBoolean;
  title: {
    arrow: {
      base: string;
      open: {
        off: string;
        on: string;
      };
    };
    base: string;
    flush: FlowbiteBoolean;
    heading: string;
    open: FlowbiteBoolean;
  };
}

export interface FlowbiteTheme extends Record<string, unknown> {
  accordion: AccordionTheme;
  // ...
````
```typescript
export interface AccordionProps extends PropsWithChildren<ComponentProps<'div'>> {
  alwaysOpen?: boolean;
  arrowIcon?: FC<ComponentProps<'svg'>>;
  children: ReactElement<AccordionPanelProps> | ReactElement<AccordionPanelProps>[];
  flush?: boolean;
  theme?: DeepPartial<AccordionTheme>
}
```

I also have some ideas about nester theme provider
```typescript
<Flowbite theme={{
        base: 'divide-y-4 divide-rose-200 border-rose-200 dark:divide-rose-700 dark:border-rose-700',
      }}>
  <Accordion>
    // ...
  </Accordion>
</Flowbite>
```

**Comment by sldk-yuri** [comment]
I'm agree with you, lets start with branch for theme types decomposition because it look like refactoring

I'm going to:
1. Create a branch "refactor-theme-decomposition" and update theme types in `default.ts` file. 
3. Run tests, make sure that everything work correct, fix if something don't.
3. Merge the branch

I think it's a good start point. After that we may continue work on components theme implementation.

btw what is the good way to keep interfaces in this project - in the same file `default.ts` or make a ton of separate files inside `theme` folder?

**Comment by rluders** [comment]
Also, maybe I would try to move the:

```ts
const systemTheme: FlowbiteTheme['accordion'] = JSON.parse(JSON.stringify(useTheme().theme.accordion));
const theme = mergeDeep(systemTheme, customTheme);
```

Into some generic helper function that could be used by all the components.

**Comment by rluders** [comment]
```ts
const theme = useComponentTheme<FlowbiteAccordion>(customTheme);
```

**Comment by sldk-yuri** [comment]
@rluders Seems that idea about nested provider is better, we don't need to change components code just update provider. I've done with all necessary steps (testing, refactoring, adding new features). Take a look at my PR please.

**Comment by sldk-yuri** [comment]
- [x] #453 Toast was closed with #450
- [x] #455 CheckboxTheme 
- [x] #456 FileInput
- [x] #457 Label
- [x] #458 Radio
- [x] #459 Select
- [x] #460 TextInput
- [x] #461 Textarea
- [x] #462 ToggleSwitch
- [ ] #452 
- [ ] #454

**Comment by rluders** [comment]
OK. I think that now that we have all the components with their own theme interfaces, we could move to the second Phase of this task which is to implement the `theme={}` props to all components.

@tulup-conner @sldk-yuri right? I think that we can address it in one single PR. It should be ~4 lines per component change.

**Comment by sldk-yuri** [comment]
@rluders yes, you're right the next phase is add `theme` prop to all components. I'm agree that we may use one PR for that.

**Comment by tulup-conner** [comment]
This is really great, nice work, and exciting!

**Comment by someguy9** [comment]
Would love theme= support for Sidebar

**Comment by tulup-conner** [comment]
> Would love theme= support for Sidebar

That exists and is documented above

**Comment by tulup-conner** [comment]
See #611

**Comment by dev-gush** [comment]
I tried doing the following - 

```
const AccordionTheme: FlowbiteAccordionTheme = {
    "root": {
      "base": "divide-y divide-gray-200 border-gray-200",
      "flush": {
        "off": "rounded-lg border",
        "on": "border-0"
      }
    },
    "content": {
      "base": "py-5 px-5 "
    },
    "title": {
      "arrow": {
        "base": "h-6 w-6 shrink-0",
        "open": {
          "off": "",
          "on": "rotate-180"
        }
      },
      "base": "flex w-full items-center justify-between first:rounded-t-lg last:rounded-b-lg py-5 px-5 text-left font-medium text-gray-500 ",
      "flush": {
        "off": "hover:bg-gray-100 focus:ring-0 focus:ring-gray-200 ",
        "on": "bg-transparent text-primary!"
      },
      "heading": "",
      "open": {
        "off": "",
        "on": "text-primary"
      }
    }
  }
  
  return (
    <Accordion className={twMerge(`w-full ${className}`)} theme={AccordionTheme}>
```

Can confirm it is not working, am i doing something wrong here?
