### ISSUE TITLE
Bugs on Avatar, Dropdown and Button.

### ISSUE THREAD

**Issue by 0rangeFox** [themesberg/flowbite-react#451]
Hey folks 👋, I'm reporting here several bugs of the components that are mentioned in the title.

**Avatar**:
The problem with the "_Avatar_" component is the "_Color_" property that can't even change the color of the "_border_" and always stays gray. It is in the video running this problem and the code I have is as follows:
```tsx
<Avatar img={discordImage} rounded bordered color='purple' />
```

**Dropdown**:
This problem only happens in safari and not in Google Chrome, which is "_Toggle_", if I click on the area outside the "_Dropdown Menu_" nothing happens unless I go and click on the "_Dropdown Button_" again. As you can see in the video, I make several clicks on the "_body_" and it starts selecting text and the menu don't disappear.

**Button**:
As you can see in the video, when I am in google chrome and if I click on the button the "_blur_" doesn't disappear and stays as it is "_focused_", but when I do it in safari, it already has the normal behavior. Now you must be asking, and what happens when you are browsing the [official flowbite website](https://flowbite-react.com/buttons)? The behavior is normal and just seems to only happen when I have it hosted on my computer and even I have tested it with [starter project](https://github.com/tulupinc/flowbite-next-starter) and it has the same problem. It must be because Google Chrome has some special setting for localhost urls, maybe for debug/testing? The truth is, I have searched and found nothing like this on the internet.

**Video**:
https://user-images.githubusercontent.com/38193239/205129550-e2656f64-ad9c-4dc4-b7e4-0f7b929f7b1a.mov

**Project information**:
- Tailwind: 3.2.4
- Flowbite: 1.5.4
- Flowbite React: 0.3.5
- Type: NextJS _(Without Turbopack)_

**Comment by 0rangeFox** [comment]
It seems that the file I uploaded is not working properly, anyway I uploaded it to youtube, [click me](https://youtu.be/JApAL5fkEEQ) to see.

**Comment by victorfunes** [comment]
I have the problem of clicking outside of the dropdown menu and the component is not closing also in Google Chrome, but it only occurs the second time you click on it (the first time it works well).

Steps to reproduce:
1. Click on the dropdown button to show the dropdown menu
2. Click outside of the component: it will close the dropdown menu
3. Click again on the dropdown button to show the dropdown menu
4. Click outside of the component: the dropdown menu will remain open until you click again the dropdown button

Project information:

Tailwind: 3.2.4
Flowbite: 1.6.5
Flowbite React: 0.4.10

**Comment by rluders** [comment]
I hope this isn't working anymore, so, I'm closing it.
