### ISSUE TITLE
Button outline with fullSized is just wrong

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#466]
**Describe the bug**

**To Reproduce**

1. Go to [this link](https://flowbite-react.com/storybook/?path=/story/components-button--default-button&args=outline:true;fullSized:true)

**Expected behavior**

It should look like the outline buttons in standard flowbite docs. See [here](https://flowbite.com/docs/components/buttons/). I guess that we also have a weird and unnecessary (?) `span` tag inside the button. 

**Screenshots**

![flowbite-react com_storybook__path=_story_components-button--default-button args=outline_true;fullSized_true;color_purple (1)](https://user-images.githubusercontent.com/191027/205510367-54c2e9e3-8330-46c0-ae7b-c86fae84ae1f.png)

**System information:**

N/A

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.3.5
- Type: CRA

**Additional context**

N/A

**Comment by Lonecloud7** [comment]
can I get a link to the code where this button is declared? as you guessed I think the span around the button is set to width 100%, and also the trigger for the hover effect is set to the span instead of the button element.

**Comment by rluders** [comment]
@Lonecloud7 https://github.com/themesberg/flowbite-react/blob/main/src/lib/components/Button/Button.tsx

**Comment by rluders** [comment]
I was looking into this one today, and it seems that it is a little bit more complex than it looks. First, adding the `w-full` to the `span` seems to "solve" but the problem is deeper. The buttons don't match the flowbite style and the theme structure seems far way more complex than desired to achieve the desired style.

I'm removing the `good first issue` from this one, and I'll propose here a refactoring to the `Button` theming, that could be handled when we implement the #443 for this component.

**Comment by yoku2010** [comment]
@rluders I have fixed this issue using CSS classes. Please check the linked PR. Thanks!
