### ISSUE TITLE
AvatarGroup has unecessary margin

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#467]
**Describe the bug**

This is a change to the flowbite-react default theme. The `AvatarGroup` component has an unnecessary `mb-5` that needs to be removed.

**To Reproduce**

1. Go to storybook
2. Click on Avatar > Grouped
3. Inspect the AvagarGroup base HTML tag
4. See unnecessary `mb-5` there

**Expected behavior**

It should NOT have the `mb-5`.

**Screenshots**

N/A

**System information:**

N/A

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.3.5
- Type: CRA

**Additional context**

The fix is very easy, just remove it from here:

https://github.com/themesberg/flowbite-react/blob/cd26e24b4a0faec1aec8d4bceac14f3ad9bd91de/src/lib/theme/default.ts#L116

**Comment by MaverickDe** [comment]
Can I get assigned this
