### ISSUE TITLE
Accordion closed by default doesn't work

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#472]
Basically, the `Accordion.Panel` is ignoring the `isOpen` props. In this case, users can't opt to have all Panels closed by default, as also, they can't choose the one that will be open by default as well.

Does it make sense? Anyway, this is probably a "refactoring" opportunity to simplify the way that the `Accordion` component works.

### Discussed in https://github.com/themesberg/flowbite-react/discussions/360

<div type='discussions-op-text'>

<sup>Originally posted by **WolverStones** September 20, 2022</sup>
How to make Accordion closed by default when loading or refreshing the page?

Like this: https://i.imgur.com/SwU01cg.png</div>

**Comment by gmixoulis** [comment]
Did you find any solution to start the accordion as closed? I need this solution too. Thanks.

**Comment by daeho-haruto** [comment]
> Did you find any solution to start the accordion as closed? I need this solution too. Thanks.

An accordion to start with closed is here: https://github.com/themesberg/flowbite-react/pull/524
