### ISSUE TITLE
Support for all theme colors in components (pink, teal, etc.)?

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#473]
All components that support the property `color=` MUST support all `FlowbiteColors`. 

Currently, we are using `Pick` to select the ones that we want. Not ideal, I would say/. It would be better if we support all the colors.

It doesn't mean that we should/must provide styling at the theme for all these colors, just support removing the `Pick` probably is good enough.  (NEED TO BE TESTED - I do accept other solutions ideas)

### Discussed in https://github.com/themesberg/flowbite-react/discussions/325

<div type='discussions-op-text'>

<sup>Originally posted by **dasveloper** August  9, 2022</sup>
My application is based around the "pink" color from Tailwind's default theme colors. However with flowbite-react, the Button, Progress, Dropdown, etc. components don't seem to support `color="pink"`. Radio and Checkbox don't appear to support colors at all?

Regular Flowbite [support pink](https://flowbite.com/docs/customize/colors/) and some components like the badge do too. Just wondering if that is something that can be updated or if I'm missing something?</div>

**Comment by lirbre** [comment]
Hey @rluders. I'm looking foward to start contributing. 

Can you provide me some context? This issue had some progress? This seems to be a pretty good issue to start collaborating. :)
