### ISSUE TITLE
Nesting accordion components causes hydration error in nextjs

### ISSUE THREAD

**Issue by BossDaily** [themesberg/flowbite-react#474]
**Describe the bug**
Nesting accordion components causes a hydration error
**To Reproduce**
Nest accordion components
```jsx
<Accordion alwaysOpen={true}>
          <Accordion.Panel>
            <Accordion.Title>Embed</Accordion.Title>
            <Accordion.Content>
              <Accordion alwaysOpen={true}>
                <Accordion.Panel>
                  <Accordion.Title>Embed</Accordion.Title>
                  <Accordion.Content>fdsafsadfsdfa</Accordion.Content>
                </Accordion.Panel>
              </Accordion>
            </Accordion.Content>
          </Accordion.Panel>
        </Accordion>
  ```
![image](https://user-images.githubusercontent.com/75937850/205958607-549a66c9-292a-41fd-ad2e-29dededb253e.png)

**Expected behavior**
This should just be nested without throwing an error like this 
![image](https://user-images.githubusercontent.com/75937850/205958998-fabac25e-cca0-41f7-a363-3ecf3dc7232a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/75937850/205958607-549a66c9-292a-41fd-ad2e-29dededb253e.png)
![image](https://user-images.githubusercontent.com/75937850/205958998-fabac25e-cca0-41f7-a363-3ecf3dc7232a.png)
**System information:**

- Device: (This happened on both my person windows machine & my vs code server which is on ptero panel & ubuntu 20.04)
- Resolution:
- OS: Windows 10 Home & Ubuntu 20.04
- Browser: Firefox & Brave
- Version:

**Project information:**

- Tailwind: ^3.2.1
- Flowbite: ^1.5.3
- Flowbite React: ^0.3.5
- Type: CRA

**Additional context**
Im using TurboRepo

**Comment by BossDaily** [comment]
any progress?

**Comment by niccolo92matinum** [comment]
Mybe  it is the props you pass to the component(in my case props).  When your accordion component  rendering it doesn't have the data yet. 
For me useEffect was the solution.  Wait for the data first and then inject your jsx

This is my code
function AccordionOrder ({ products, showProductOnChoosen }) {
  const [open, setOpen] = useState(1)
  const [tag, setTag] = useState('waiting')

  const handleOpen = (value) => {
    setOpen(open === value ? 0 : value)
  }

  useEffect(() => {
    const accordionVariable = <Fragment>
    {
       Object.values(products).map((categoryArr, i) => {
         return (

            <Accordion key={Math.random()} open={open === ((i + 1)) }>
            <AccordionHeader key={i} onClick={() => handleOpen(i + 1)}>
             {categoryArr[0].category}
              </AccordionHeader>
              {categoryArr.map((singleObj) => {
                return (

          <AccordionBody key={Math.random()}>

            <h1>{singleObj.title} </h1>
          <button onClick={() => { showProductOnChoosen(singleObj) }} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Select Product</button>
          <p>{singleObj.description}</p>

          </AccordionBody>

                )
              })}

          </Accordion>

         )
       })
    }

  </Fragment>
    setTag(accordionVariable)
  }, [])

  return (
  <>
  {tag}
  </>
  )
}

export default connect(null, null)(AccordionOrder)

**Comment by niccolo92matinum** [comment]
I think the problem is the props you pass through the component.  Using useEffect hook you should resolve the issue.
This is my code:
function AccordionOrder ({ products, showProductOnChoosen }) {
  const [open, setOpen] = useState(1)
  const [tag, setTag] = useState('waiting')

  const handleOpen = (value) => {
    setOpen(open === value ? 0 : value)
  }
// il componente viene renderizzato prima delle props  perciò bisogna usare lo use effect
  useEffect(() => {
    const accordionVariable = <Fragment>
    {
       Object.values(products).map((categoryArr, i) => {
         return (

            <Accordion key={Math.random()} open={open === ((i + 1)) }>
            <AccordionHeader key={i} onClick={() => handleOpen(i + 1)}>
             {categoryArr[0].category}
              </AccordionHeader>
              {categoryArr.map((singleObj) => {
                return (

          <AccordionBody key={Math.random()}>

            <h1>{singleObj.title} </h1>
          <button onClick={() => { showProductOnChoosen(singleObj) }} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Select Product</button>
          <p>{singleObj.description}</p>

          </AccordionBody>

                )
              })}

          </Accordion>

         )
       })
    }

  </Fragment>
    setTag(accordionVariable)
  }, [open])

  return (
  <>
  {tag}
  </>
  )
}

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
