### ISSUE TITLE
Allow the <img> component in <Avatar> to be overridden by the user

### ISSUE THREAD

**Issue by alexanderson1993** [themesberg/flowbite-react#482]
**Is your feature request related to a problem? Please describe.**
When creating a website, I used Google SSO for logging in the user. When displaying the profile image (which is on Google's domain), I had no way to override the <Avatar> image to add `referrerPolicy="no-referrer"`. I'm sure there are other situations when having direct access to the underlying element would be helpful as well.

I also would like to use Next.js's <Image> component with <Avatar>, but that's not possible without forking the component entirely.

**Describe the solution you'd like**
Add a new prop to <Avatar> called `imgElement`. This would be a render prop which lets the user render whatever component they want in place of <img>. This makes it possible to add extra props to the <img>, or replace it with Next.js < Image > or any other component. 

The existing props passed to the <img> component in <Avatar> would be passed to the render prop function so they can be spread on the user provided component.

```jsx
<Avatar src={avatarUrl} rounded imgElement={(props) => <img {...props} referrerPolicy="no-referrer" />} />
<Avatar src={avatarUrl} rounded imgElement={(props) => <Image {...props} width={64} height={64} />} />
```

The render prop solution is elegant because it solves for both adding props to the <img> and changing the underlying element without adding a ton of extra props. This would be a non-breaking change, because omitting the optional `imgElement` prop would fall back on the existing behavior.

**Describe alternatives you've considered**
My workaround for this was to fork the <Avatar> element entirely by copying its source code into my project. 

**Additional context**
If this issue is accepted, I intend to implement it and submit a PR myself.

**Comment by rluders** [comment]
I think this is a good idea, @alexanderson1993. I really enjoyed the approach. Please, go ahead with the PR.
