### ISSUE TITLE
TextInput Success and error validation

### ISSUE THREAD

**Issue by Mahmoud-Khaled-FS** [themesberg/flowbite-react#485]
The TextInput has bug when i use color property, any color i use make the background color white, and the same bug It appears clearly in the website https://flowbite-react.com/forms

**Comment by mortezasabihi** [comment]
@rluders 

https://github.com/themesberg/flowbite-react/blob/21dab1fe576a09d33c8ecd35cd10cf93eb332e9a/src/lib/theme/default.ts#L397

Just these colors are defined.

And in the Figma design, there are four main colors exist:
**gray, blue, green, red**
https://www.figma.com/file/xOF7lECLNjnutDX31LlivW/Flowbite-Pro-Figma-v2.4.0?node-id=3279%3A34618&t=ppoaHeewszEp7cRq-0


should all colors support form inputs?
