### ISSUE TITLE
Tooltip is offset when using it wrapping a button

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#487]
**Describe the bug**

When I integrate the latest version of Flowbite React and use the Tooltip component to wrap a button the arrow is not being positioned properly and looks like the whole tooltip is also offset to the right.

Here's the code:

```
<div className="flex items-center justify-center mb-2 space-x-4">
  <Tooltip content="Available in HTML + Tailwind CSS">
    <button
      type="button"
      className="relative inline-flex items-center justify-center rounded-full w-14 h-14 bg-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 hover:bg-gray-100 focus:ring-4 focus:ring-blue-300 dark:focus-ring-blue-400"
    >
      <span className="relative w-8 h-8">
        <Image
          layout="fill"
          objectFit="contain"
          src="/images/technologies/tailwind.svg"
          alt="Tailwind CSS logo"
        />
      </span>
    </button>
  </Tooltip>
  <Tooltip content="Available in React + TypeScript">
    <button
      type="button"
      className="relative inline-flex items-center justify-center rounded-full w-14 h-14 bg-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 hover:bg-gray-100 focus:ring-4 focus:ring-blue-300 dark:focus-ring-blue-400"
    >
      <span className="relative w-8 h-8">
        <Image
          layout="fill"
          objectFit="contain"
          src="/images/technologies/react.svg"
          alt="React logo"
        />
      </span>
    </button>
  </Tooltip>
</div>;
```

**To Reproduce**

1. Write the code about using the Tooltip
2. Hover on the button component
3. See error offset

**Expected behavior**
Tooltip arrow should be positioned correctly.

**Screenshots**

<img width="292" alt="Screenshot 2022-12-12 at 13 43 02" src="https://user-images.githubusercontent.com/8052108/207037156-bcb2882c-4a82-4252-a934-3ffeb890c632.png">

**System information:**

- Device: iMac
- OS: MacOS
- Browser: Chrome

**Project information:**

- Tailwind: 3.1.4
- Flowbite: 1.5.5
- Flowbite React: 0.3.7
- Type: CRA

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
