### ISSUE TITLE
Select content and caret overlap

### ISSUE THREAD

**Issue by phbernard** [themesberg/flowbite-react#489]
**Describe the bug**
In a Select component, the caret and the content sometimes overlap:

![image](https://user-images.githubusercontent.com/423852/207389691-efaec6c6-8d3d-4f6b-880b-88b11a14613f.png)

**To Reproduce**

1. Go to the official [Flowbite React doc](https://flowbite-react.com/forms) and scroll down to the "Select input" section:

![image](https://user-images.githubusercontent.com/423852/207390127-cd7e08c9-6469-4fa3-9313-49e59c0cd85e.png)

2. Open the dev tools
4. Spot the `select` container:

![image](https://user-images.githubusercontent.com/423852/207390384-976e4ed7-9b92-479f-aaff-6c386a277e1b.png)

6. Remove its classes (ie. `relative w-full`)

![image](https://user-images.githubusercontent.com/423852/207390488-d459e0a7-1434-4e7a-bafa-b9ceb864e827.png)

Now the option and the caret overlap.

**Expected behavior**

The field should be large enough to fit the content and the caret without overlap:

![image](https://user-images.githubusercontent.com/423852/207391100-eeb973ca-4599-435b-a493-b05156d84058.png)

**System information:**

- Device: PC
- Resolution: any
- OS: Windows
- Browser: Chrome
- Version: 108.0.5359.99

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Comment by rluders** [comment]
@phbernard please, update your flowbite-react

**Comment by rluders** [comment]
@zoltanszogyenyi the issue also happens for the standard flowbite library. It seems that it is related to the select padding.

**Comment by phbernard** [comment]
Thank you for investigating. I realize I didn't check the standard lib itself. Do you want me to fill an issue there and reference it here?

**Comment by rluders** [comment]
@phbernard I think that it would be nice.

**Comment by phbernard** [comment]
As mentioned above, the [issue exists in the Flowbite standard library](https://github.com/themesberg/flowbite/issues/360), which is probably where it should be addressed.

**Comment by rluders** [comment]
We are going to fix it from our side as well. So... I'll keep this one open and track the flowbite one.

**Comment by zoltanszogyenyi** [comment]
Thanks for the detailed report. This will be addressed on the main library too.

**Comment by zaheershaikh936** [comment]
Can I get assigned this

**Comment by tulup-conner** [comment]
@zaheershaikh936 Please feel free to submit a PR if you want to solve the issue

**Comment by zaheershaikh936** [comment]
Hello @tulup-conner I was working on this issue. but it's look all good !
hey is the screenShot link : [https://ibb.co/L0hbXh1](url)
Please take a look and let me know so that i can working on this if it's open?
Thank you!

**Comment by rluders** [comment]
This was fixed and it is working for `0.4.10`
