### ISSUE TITLE
Scroll on dropdown

### ISSUE THREAD

**Issue by arifals27** [themesberg/flowbite-react#490]
Hello

I'm using a <Dropdown> component but the same number of <Dropdown.Item> has hundreds. If possible, add features to make <Dropdown.Item> scrollable so it doesn't extend to the bottom. 

Thank you

**Comment by rluders** [comment]
I'm pretty sure that you can change it at theme, just by adding a `h-*` and `overflow-y-auto` to [this line](https://github.com/themesberg/flowbite-react/blob/4934a8998bf125ead6a1309fad279d2a9d0d086e/src/lib/theme/default.ts#L304) at your theme.

**Comment by rluders** [comment]
Also, I'm not sure if having this large amount of items at the Dropdown is something that "should be good to have".
