### ISSUE TITLE
Dropdown - event.stopPropagation prevents dropdown from opening

### ISSUE THREAD

**Issue by ghost** [themesberg/flowbite-react#494]
**Describe the bug**
On stopping event propagation on Dropdown `onClick` prevents the dropdown items from opening.

**To Reproduce**
Suppose I have a `div` with an `onClick` listener and `Dropdown` component is it's child. I want to prevent the propagation of click event on dropdown menu icon from reaching the  onClick listener on it's parent `div`.
While using the below snippet, the dropdown won't open.
```jsx
<div onClick={() => doSomething()}
  <Dropdown
    onClick={(e) => {
      e.stopPropagation();
    }}
  >
    <Dropdown.Item>Item</Dropdown.Item>
  </Dropdown>
  {/* ... /}
</div>
```

**Expected behavior**
Dropdown items should open and stop the event from propagating.

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.

**Comment by gsdev01** [comment]
any update ?

**Comment by jerome-Dh** [comment]
In my case
flowbite-react: 0.10.2
Tailwind: 3.4.1

Stopping event propagation on Dropdown didn't work

```
<tr key={row.id} onClick={e => handleRowEvent(e, row.id)}>
  <td>Text</td>
  <td>
    <Dropdown>....</Dropdown>
  </td>
</tr>
```


But this workaround worked for me

```
<tr key={row.id} onClick={e => handleMainEvent(e, row.id)}>
  <td>Text</td>
  <td>
    <div onClick={e => e.stopPropagation()}>
      <Dropdown>....</Dropdown>
    </div>
  </td>
</tr>
```

It stops the click event from bubbling up to the `<tr>` element's onClick handler.
