### ISSUE TITLE
Button "Choose File" issue with the border radius 

### ISSUE THREAD

**Issue by alexialechot** [themesberg/flowbite-react#496]
**Describe the bug**
The border radius of the 'Choose file' button on the fileUpload component is rectangular, instead of being rounded as it should be.

**To Reproduce**

1. Open Safari browser
2. Look at the button of the fileUpload component

**Expected behavior**
**With Chrome:**
<img width="1279" alt="Screenshot 2022-12-21 at 09 25 50" src="https://user-images.githubusercontent.com/30685658/208856249-ed569238-07ed-4c3a-b605-8669da505765.png">

**Screenshots**
**With Safari:**
<img width="1409" alt="Screenshot 2022-12-21 at 09 19 56" src="https://user-images.githubusercontent.com/30685658/208856464-b2f96c63-0e89-4fb2-8dcd-6bef3bfbc34d.png">

**System information:**

- Device: MacBook Pro
- Resolution: 16-inch (3456 × 2234)
- OS: macOS Ventura Version 13.0.1
- Browser: Safari
- Version: Version 16.1 (18614.2.9.1.12)

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.5.3
- Flowbite React: 0.3.4
- Type: CRA

**Additional context**

**Comment by rluders** [comment]
This is probably a very simple fix. Just need to fix the FileInput style inside the default theme.
