### ISSUE TITLE
Modal doesn't close when clicking outside of the container

### ISSUE THREAD

**Issue by bestan** [themesberg/flowbite-react#497]
**Describe the bug**
Modal doesn't close when clicking outside of the modal container, i.e. a semi-transparent black background.

**To Reproduce**

1. Go to https://flowbite-react.com/modal
2. Click on Toggle modal
3. Click outside of the Term of Service modal (anywhere on the semi-transparent background)
4. Note that modal isn't closed after the click

**Expected behavior**
The modal closes after the click outside of the container, see the original flowbite modal https://flowbite.com/docs/components/modal/

**System information:**

- Device: Macbook Pro
- OS: macOS Ventura 13.0.1 
- Browser: Chrome
- Version: 108.0.5359.124

**Comment by rluders** [comment]
What we need her is some way to make modals dismissable by clicking outside it. This feature must be optional, 'cause sometimes we may not want to allow users to close the modal by clicking outside it.

**Comment by lassegit** [comment]
Exactly what I was looking for. When will this be released? 😃

**Comment by rluders** [comment]
@lassegit `0.4.0` is targeting the end of January. Hopefully, if we get #443 done by that.
