### ISSUE TITLE
Build Modal component

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#5]
Reference: https://flowbite.com/docs/components/modal/

**Comment by bacali95** [comment]
I started implementing this component locally, I will push as soon as it is done.

**Comment by zoltanszogyenyi** [comment]
Hey @bacali95,

Awesome! Please mark yourself as an "Assignee".

I think we could also create a Kanban board on Github so we can see which ones are being worked on already.

**Comment by zoltanszogyenyi** [comment]
Here's the [project kanban board](https://github.com/orgs/themesberg/projects/2). Added your task to "in progress".

**Comment by bacali95** [comment]
Great, thanks :smile:
