### ISSUE TITLE
Input elements except for file type get border width of 1px and it is NON-OVERRIDABLE

### ISSUE THREAD

**Issue by kibrukuture** [themesberg/flowbite-react#506]
I am trying to override the border width of 1px (coming from flowbite ui lib), but it is not getting overriden no matter what. 

-I am using tailwindcss and flowbite for the stylesheet.

**Comment by rluders** [comment]
Why did you ignore the bug template? I can't help. Please, open it again, fill up the bug issue template and provide more information about the issue you are having.
