### ISSUE TITLE
<Dropdown.items> breaking responsive chrome tools

### ISSUE THREAD

**Issue by corbin1988** [themesberg/flowbite-react#509]
**Describe the bug**
In chrome responsive dev tools the `<html>` and `<body>` width don't reach the full width of the screen when using 

**To Reproduce**

1. Open up chrome tools
2. Click responsive tab
3. Adjust width of screen

**Screenshots**

Picture of bug on: https://flowbite-react.com/

![Screen Shot 2022-12-30 at 4 48 58 PM](https://user-images.githubusercontent.com/37128501/210113833-f7e97b71-20b3-462a-901d-232277b0f2ae.png)

**System information:**

- Chrome
- MBP

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

I've tested this on Firefox, and the same bug does not apply.

Here's the raw HTML for a <Dropdown>

```
<div data-testid="flowbite-tooltip" tabindex="-1" className="z-10 w-fit rounded divide-y divide-gray-100 shadow transition-opacity duration-100 invisible opacity-0 border border-gray-200 bg-white text-gray-900 dark:border-none dark:bg-gray-700 dark:text-white" style={ {position: 'absolute', top: '59px', left: '1161.68px'}} id=":R1km:" role="tooltip">
    <div className="py-1 text-sm text-gray-700 dark:text-gray-200">
      <ul className="py-1">
          <div className="block py-2 px-4 text-sm text-gray-700 dark:text-gray-200"><span className="block text-sm">Bonnie Green</span><span className="block truncate text-sm font-medium">name@flowbite.com</span></div>
          <div className="my-1 h-px bg-gray-100 dark:bg-gray-600"></div>
          <li className="flex items-center justify-start py-2 px-4 text-sm text-gray-700 cursor-pointer hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-white">Dashboard</li>
          <li className="flex items-center justify-start py-2 px-4 text-sm text-gray-700 cursor-pointer hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-white">Settings</li>
          <li className="flex items-center justify-start py-2 px-4 text-sm text-gray-700 cursor-pointer hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-white">Earnings</li>
          <div className="my-1 h-px bg-gray-100 dark:bg-gray-600"></div>
          <li className="flex items-center justify-start py-2 px-4 text-sm text-gray-700 cursor-pointer hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-white">Sign out</li>
      </ul>
    </div>
</div>
```
If you remove:

```
style={ {position: 'absolute', top: '59px', left: '1161.68px'}}
```

The problem goes away. More than likely due to chrome not being able to keep up to the top and left values set on the client.

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
