### ISSUE TITLE
Has the 0.3.7 been published on npm correctly?

### ISSUE THREAD

**Issue by hydRAnger** [themesberg/flowbite-react#512]
The current version on npm is 0.3.7(https://www.npmjs.com/package/flowbite-react)

But the code seems different between our repo and npm module?
for example, the Tab component(as I'm looking for things like ```onActiveTabChange```, to handle some side-effect with the tabs):
- in repo(v0.3.7): https://github.com/themesberg/flowbite-react/blob/main/src/lib/components/Tab/Tabs.tsx#L99-L102
- in npm(v0.3.7): 
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1228449/210253853-853d34bc-bfc7-450f-9574-ad259b1cbe05.png">

**Comment by rluders** [comment]
@hydRAnger 'cause the code that you are getting from the repository is the one at the `main` branch (that is the next release - 0.4.0), not the one that was tagged to the `0.3.7` release.

The `0.3.7` code can be found here:
https://github.com/themesberg/flowbite-react/tree/v0.3.7

**Comment by hydRAnger** [comment]
@rluders 
Thanks a lot.

btw, if I wanna use a feature like [onActiveTabChange](https://github.com/themesberg/flowbite-react/blob/main/src/lib/components/Tab/Tabs.tsx#L99-L102), where should I get the latest release? (seems not on npm: https://www.npmjs.com/package/flowbite-react?activeTab=versions )
