### ISSUE TITLE
Tailwindcss border not working after installing Flowbite

### ISSUE THREAD

**Issue by fprackwieser** [themesberg/flowbite-react#513]
My component is wrapped by this div:

```
    <div className="bg-gray-800 border border-gray-700 rounded-lg">

....
      </div>
```
After installing Flowbite the border wasn't taking any color. [Look after install.](https://i.stack.imgur.com/fwRJF.png)

Somehow also the Dividers lost their color.

**Comment by rluders** [comment]
I'm closing this one, there is not enough information to work with. Please, if you want us to check it try to use the template for `bug report` and fill up it with as much information as possible.
