### ISSUE TITLE
Dropdown Menu does not close after outside click

### ISSUE THREAD

**Issue by thornzz** [themesberg/flowbite-react#527]
Describe the bug
Dropdown Menu doesn't close when clicking outside of the menu.

To Reproduce

Go to https://flowbite-react.com/dropdown
Click on any Dropdown Menu
Click outside of the Menu
Note that Menu isn't closed after the click
Expected behavior
The Menu closes after the click outside of the menu, see the original flowbite dropdown menu https://flowbite.com/docs/components/dropdown/

System information:

Device: Macbook Pro
OS: macOS Ventura 13.0.1
Browser: Chrome
Version: 108.0.5359.124

**Comment by rluders** [comment]
It looks like the issue only happens in the first example if you click on some dropdown item before clicking outside it. I recorded a video to demonstrate it, and I can also confirm that it doesn't seem to be browser-related.

https://user-images.githubusercontent.com/191027/211885837-72fe0953-c1ce-45ca-8449-7b5064a58f3f.mov

**Comment by nezzard** [comment]
Same problem, next js flowbite react

**Comment by matheus-omena** [comment]
Any solution?

**Comment by anbkit** [comment]
Any ideas to fix the problem?

**Comment by rluders** [comment]
Nope. But if someone wants to investigate and submit a PR, it would be super welcome.

**Comment by Tejas9535** [comment]
Hi, I would like to work on this issue.

**Comment by rluders** [comment]
Solved by #840
