### ISSUE TITLE
Dark Theme Toggle Page

### ISSUE THREAD

**Issue by mouracamila** [themesberg/flowbite-react#54]
**Is your feature request related to a problem? Please describe.**
The Dark Theme Togglepage missing in the documentation

**Describe the solution you'd like**
Implement the Dark Theme Toggle page
 
**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rluders** [comment]
I think that we don't need it. 'Cause now it is related this component: https://flowbite-react.com/theme

What do you folks think? @mouracamila @bacali95 @tulup-conner

**Comment by tulup-conner** [comment]
I agree, and there should be an example DarkThemeToggle added to the Theme page IMO

**Comment by rluders** [comment]
@tulup-conner it is there already. So... are we good here?

**Comment by tulup-conner** [comment]
Am I missing something? I don't see one anywhere except the header.

**Comment by bacali95** [comment]
@tulup-conner check here https://github.com/themesberg/flowbite-react/blob/main/src/docs/pages/ThemePage.tsx
