### ISSUE TITLE
How customize slider?

### ISSUE THREAD

**Issue by robokonk** [themesberg/flowbite-react#544]
Hello, 

I want slider:
- hide arrow
- change color of dots
- change height, at the moment max size I can set `h-96`, in another way slider was hidden.

This is my code:
```
<div className="min-h-96">
          <Carousel
            slideInterval={5000}
            leftControl="&nbsp;"
            rightControl="&nbsp;"
          >
          ....
        </Carusel>
</div>
```

What I should change, and where I can find information about it?
On this page is readed, that I use new Carusel, but I don't understand it, anyone can help me?
https://flowbite.com/docs/components/carousel/

**Comment by rluders** [comment]
@robokonk you need to use the flowbite-react theme system.

https://github.com/themesberg/flowbite-react/blob/v0.3.7/src/lib/theme/default.ts
https://flowbite-react.com/theme
