### ISSUE TITLE
No Server Component Support in React / Next 13?

### ISSUE THREAD

**Issue by AlexW301** [themesberg/flowbite-react#553]
**Is your feature request related to a problem? Please describe.**
I can not seem to use react server components with next 13 when using the flowbite react library. When using a simple button component I get this error. 

"You're importing a component that needs flushSync. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default."

**Describe the solution you'd like**
Support for server components, theres no need to not be able to use server components when using something as simple as a button.

**Comment by zoltanszogyenyi** [comment]
Hey @rluders @tulup-conner,

Can you please check this out? Recently I've made an update to the main library to support SSR rendering by adding a check flag for the window object.

Cheers,
Zoltan

**Comment by rluders** [comment]
I'm closing this on 'cause, this is duplicated with #448
