### ISSUE TITLE
Sidebar stories 

### ISSUE THREAD

**Issue by mouracamila** [themesberg/flowbite-react#56]
**Is your feature request related to a problem? Please describe.**
Add the Sidebar component to the storybook

**Describe the solution you'd like**
Add the Sidebar component to the storybook. 
Like this example: https://flowbite-react.com/storybook/?path=/story/components-carousel--default-carousel

**Describe alternatives you've considered**
n/

**Additional context**
n/

**Comment by tulup-conner** [comment]
This can be closed!
