### ISSUE TITLE
Programmatically Changing Tabs Component Issue

### ISSUE THREAD

**Issue by AlexW301** [themesberg/flowbite-react#563]
Hi, I am having a problem with your React library changinging the tabs programatically, this example in the react docs does not work. The onActiveTab property doesn't exist and i get an error that I can put a useRef on functional component. 

const Tabs: FC = () => {

const [activeTab, setActiveTab] = useState<number>(0);

const tabsRef = useRef<TabsRef>(null);

return (

<>

[<Tabs.Group](http://%3Ctabs.group/)

aria-label="Default tabs"

style="default"

ref={tabsRef}

onActiveTabChange={tab => setActiveTab(tab)}

>

<Tabs.Item active title="Profile">

Profile content

</Tabs.Item>

<Tabs.Item title="Dashboard">Dashboard content</Tabs.Item>

<Tabs.Item title="Settings">Settings content</Tabs.Item>

<Tabs.Item title="Contacts">Contacts content</Tabs.Item>

</Tabs.Group>

<div>Active tab: {activeTab}</div>

<Button.Group>

<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(0)}>

Profile

</Button>

<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(1)}>

Dashboard

</Button>

<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(2)}>

Settings

</Button>

<Button color="gray" onClick={() => tabsRef.current?.setActiveTab(3)}>

Contacts

</Button>

</Button.Group>

</>

);

};

**Comment by rluders** [comment]
Could you please, follow the bug report template? I don't know what is expected, I don't know the version that you are using.

**Comment by tulup-conner** [comment]
Hi there, let us know if you're still having this issue, and please use the provided template for bug reports, it makes it easier for everybody.
