### ISSUE TITLE
Remove user preference from Flowbite component

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#565]
**Is your feature request related to a problem? Please describe.**
The #546 triggered a lot of discussion about data privacy and also it is the responsibility of the Flowbite component to handle user preference. And honestly, I think that it doesn't belong to the component since it can be restricted by a particular set or rules and laws that we are not aware of.

**Describe the solution you'd like**
Remove the user preference support from `Flowbite` component.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tulup-conner** [comment]
Follow this via #582
