### ISSUE TITLE
Tooltip Component

### ISSUE THREAD

**Issue by mouracamila** [themesberg/flowbite-react#57]
**Describe the bug**
The tooltip element is misaligned from the parent element 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ['storybook'](https://flowbite-react.com/storybook/?path=/story/components-tooltip--default-tooltip)
2. Click on Tooltip
3. See the error

**Expected behaviour**
The tooltip is aligned to parent element

**Screenshots**
![image](https://user-images.githubusercontent.com/41678283/163859592-995a7a2d-001b-4292-8a1e-185bd92c3cf1.png)

I believe this is impact other components like the dropdown. 
![image](https://user-images.githubusercontent.com/41678283/163860831-9395b442-288a-4584-b007-a75c3112e403.png)

**Desktop (please complete the following information):**
 - Browser: Chrome and Brave (Firefox is working)

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by rluders** [comment]
Keep in mind that this issue also affects other components that depends on tooltip, like `Dropdown`.

**Comment by tulup-conner** [comment]
I can reproduce this and see it works fine on Firefox as well.

This appears to be an issue with Popper. It generates totally different values for the X offset in `transform: translate()` in Firefox vs Chromium.

I notice that Popper appears to be deprecated in favor of Floating UI. It may be worth upgrading the components to the new version. Popper is over 200 commits behind now. That may result in a magic fix.

**Comment by rluders** [comment]
@tulup-conner do you want to take this one?

**Comment by tulup-conner** [comment]
I would be happy to give it a try!

**Comment by tulup-conner** [comment]
I should have something soon. For reference, Floating UI created a full example Tooltip, which we can basically copy: https://codesandbox.io/s/winter-tree-wmmffl?file=/src/Tooltip.tsx:910-1058
