### ISSUE TITLE
Accordion is not collapsing after being opened. 

### ISSUE THREAD

**Issue by RoyBkker** [themesberg/flowbite-react#570]
**Describe the bug**
When you open a panel in the Accordion, and want to close all panels again, that is not possible.

**To Reproduce**

1. Open a panel from accordion
2. Click again for trying to close it
3. Panel is not closing

**Expected behavior**
I expect to have the panel from the accordion being closed again, and all panels should be closed.

**System information:**

- Device: Macbook
- Resolution: 
- OS: 
- Browser: Arc
- Version:

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: CRA

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
