### ISSUE TITLE
dropdown menu props open={true or false}  and this label style with className 

### ISSUE THREAD

**Issue by Md-Anamul-Haque** [themesberg/flowbite-react#572]
# iI want to be dropdown menu props open={true or false}  and this label style with className 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

**Comment by rluders** [comment]
I'm closing this one @Md-Anamul-Haque - please, reopen if and use the correct template, and fill up all the required information. Thank you.
