### ISSUE TITLE
Dropdown component menu default width + rounded edges

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#575]
**Describe the bug**

On a presentational level the [dropdown menu example widths](https://flowbite-react.com/dropdown) are less wide than expected. Additionally, the main Flowbite Library updated the default rounded values for the menu from `rounded` to `rounded-lg` in order to improve consistency as a design system.

Here are the new examples from Flowbite: https://flowbite.com/docs/components/dropdowns/

**To Reproduce**

1. Go to [Flowbite React Dropdown](https://flowbite-react.com/dropdown)
2. Click on button
4. Dropdown width not correlating with the button aesthetically + rounded edges are `rounded` not `rounded-lg`

**Expected behavior**

Pass custom width classes for the dropdown menus that look out in the order. I don't think we need to do anything on a component definition level because as I can see the width of the dropdown is now based on the width of the content inside which is correct. But when we showcase the dropdowns they should look good in order to convince early adopters to use this library.

Also, the default value of the dropdown menu should be `rounded-lg` in order to keep consistency across the design system and make it consistent relative to the roundedness of the button.

**Screenshots**

<img width="346" alt="Screenshot 2023-01-31 at 17 48 51" src="https://user-images.githubusercontent.com/8052108/215811538-50c841a3-ce6c-4bac-a55c-fdd506d1f6df.png">

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: Remix

**Additional context**

None.

**Comment by rluders** [comment]
The #578 fixes the `rounded-lg`, but this one still with the `width` issue.

**Comment by tcrz** [comment]
Has this been fixed?

**Comment by rluders** [comment]
It seems that this one was fixed already.
