### ISSUE TITLE
Remove auto-generated symbols from docs 

### ISSUE THREAD

**Issue by NabajitS** [themesberg/flowbite-react#576]
**Describe the bug**
{' '} symbol exist in the docs in many places making it a bit confusing.

**Screenshots**
![Screenshot 2023-01-31 213044](https://user-images.githubusercontent.com/86390740/215814260-8447ba96-c4c4-4698-8b47-9bffed3e6828.png)

**Additional context**
{' '} symbols exist in docs, they have most likely been auto-generated by the linter or prettier.

**Comment by NabajitS** [comment]
I would love to work on this issue to get familiar with the codebase a little.

**Comment by tulup-conner** [comment]
@NabajitS Since you deleted your branch, are you done trying to add this patch yourself, or will you be trying again?

**Comment by tulup-conner** [comment]
Never mind. Resolved via #614
