### ISSUE TITLE
Flowbite theme ThemeProps dark attribute does not change if false

### ISSUE THREAD

**Issue by haron68** [themesberg/flowbite-react#581]
**Describe the bug**
When using [Flowbite component](https://flowbite-react.com/theme) to create custom theme it does not accept `dark: false`. All rendered components use dark theme

**To Reproduce**

1. Go to root component either `index.ts` or `App.tsx`
2. Use `<Flowbite>` custom theme component and wrap it around the app container. Set `dark: false` in ThemeProps
```
<Flowbite theme={{
    dark: false
  }}>
    <App {...props} />
</Flowbite>
```
3. Go to inspect tools on browser
4. See that `<html class="dark">` and all Flowbite components when used within the app render in dark mode

**Expected behavior**
Flowbite components should render in light mode

**System information:**

- Device: 2020 Macbook Pro M1
- Resolution: 13.3-inch (2560 × 1600)
- OS: macOS Ventura 13.0.1
- Browser: Brave/Chrome

**Project information:**

- Tailwind: ^3.1.6
- Flowbite: ^1.5.5
- Flowbite React: ^0.3.7
- Type: CRA

**Comment by haron68** [comment]
This behavior I've noticed is actually happening because my default OS theme is dark mode. So when the `Flowbite` component initializes and has `usePreferences = true` it will run the media query and see that my preference is dark mode on an OS level and then save that preference in `localStorage`. This effectively overrides the `dark = false` setting in the `ThemeProps` in this case

**Comment by haron68** [comment]
I think intuitively if a developer sets `dark = false` or `dark = true` this should render the page as so no matter what the user's OS level settings are.

**Comment by rluders** [comment]
This is all cool, @haron68. Maybe you want to check this one #565

**Comment by haron68** [comment]
@rluders I agree that userPreferences should be managed by the developer. I can make this change instead for my contribution

**Comment by rluders** [comment]
This would be great @haron68
