### ISSUE TITLE
Server Error TypeError: (0 , react_1.useId) is not a function with SidebarItem

### ISSUE THREAD

**Issue by pawelkontek** [themesberg/flowbite-react#584]
**Describe the bug**
While using SidebarItem.js in Next.js project I am getting this error:

**Screenshots**
![image](https://user-images.githubusercontent.com/7879784/216817734-d9c44ec3-5f4d-4587-9f38-003c2aad0c94.png)

**Project information:**

"dependencies": {
    "@svgr/webpack": "^6.5.1",
    "firebase": "^9.12.1",
    "firebase-admin": "^11.5.0",
    "flowbite": "^1.6.3",
    "flowbite-react": "^0.3.8",
    "next": "^12.3.1",
    "next-themes": "^0.2.1",
    "nookies": "^2.5.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-icons": "^4.7.1",
    "tailwind": "^4.0.0"
  },
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@tailwindcss/typography": "^0.5.9",
    "@types/react": "^17.0.20",
    "autoprefixer": "^10.4.13",
    "eslint": "7.32.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-import": "^0.13.0",
    "eslint-config-next": "^12.3.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.25.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^8.0.0",
    "lint-staged": "^13.0.3",
    "postcss": "^8.4.21",
    "prettier": "^2.7.1",
    "tailwindcss": "^3.2.4",
    "typescript": "4.4.2"
  }

**Additional context**
I am using React 18:

**Comment by rluders** [comment]
```"react": "^17.0.2",```
