### ISSUE TITLE
Toggle switches don't look right if the label spans more than one line

### ISSUE THREAD

**Issue by multiwebinc** [themesberg/flowbite-react#587]
Unchecked:

![image](https://user-images.githubusercontent.com/901732/217953151-2bac9189-b56e-4457-a480-639a1b2eb789.png)

Checked:
![image](https://user-images.githubusercontent.com/901732/217952864-37cb090b-c5ee-4f9f-a98b-d7e923237556.png)

**Project information:**

- Tailwind: 3.2.6
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: Nextjs

**Comment by multiwebinc** [comment]
The bug is in https://github.com/themesberg/flowbite

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.

**Comment by multiwebinc** [comment]
Steps to reproduce:

1. Go to https://flowbite.com/docs/forms/toggle/
2. Right click on the text "Toggle me" and in your dev tools change the text to something that spans more than one line.

Result:

![image](https://github.com/themesberg/flowbite-react/assets/901732/0a3c978c-c87c-4697-b9b7-64a095fadb14)
