### ISSUE TITLE
Allow Toasts to be positioned around the edge of the viewport and allow them to auto hide

### ISSUE THREAD

**Issue by multiwebinc** [themesberg/flowbite-react#588]
It would be great if you could choose the position where the toast shows up instead of inline or absolute relative to the current container (which is usually not `document.body`).

Also, allowing it to auto hide would be great.

For example:

```
<Toast
  position="bottom-left"
  autoHideDuration={6000}
/>

<Toast
  position="top-center"
  autoHideDuration={6000}
/>
```

**Comment by tulup-conner** [comment]
I agree with this, although I believe you can achieve this more or less just by adding Tailwind CSS classes, right? Via an absolute position. Regardless, I still think that adding the shortcut to facilitate that would be a nice touch. Would you be able to work on this?
