### ISSUE TITLE
Build breaks because of missing icons

### ISSUE THREAD

**Issue by nikandfri** [themesberg/flowbite-react#590]
Problem: 
When using the footer component with icons to social media platforms, there is little documentation from where the icons are used. Build breaks immediately. 

Solution:
Please integrate in the docs a description that icons are imported from Bootstrap
`import { ArrowRight } from 'react-bootstrap-icons'
<Footer.Icon href="#" icon={ArrowRight}/>`

**Comment by rluders** [comment]
We normally use this package.
https://react-icons.github.io/react-icons/
