### ISSUE TITLE
HOW TO CONTRIBUTE?

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#593]
Hey folks,

Several people are arriving here and want to contribute to the project. I'll give my advice here, so you don't need to be afraid and know how to start.

## Create my PR

1. I do always recommend people try to create a project using `flowbite-react` to know the basics.
2. Check our [Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md) and our [Code of conduct](https://github.com/themesberg/flowbite-react/blob/main/CODE_OF_CONDUCT.md) it has the basic info how to start.
3. Now you need a task, so check the [issues](https://github.com/themesberg/flowbite-react/issues) and pick up one. You don't need to ask for permission, if it is confirmed, or if it is an enhancement and you feel that you have enough info to start to work on it.
4. Before creating the PR, make sure that your code passes all the tests and that the code style is also good.
5. Create a PR, please use the template and fill up all the information. Do not forget to link the issue that the PR closes.

## Reporting issues/Requesting features

1. First search if there are no existing [issues](https://github.com/themesberg/flowbite-react/issues) for the bug/feature request - we normally try to prioritize the ones with more reactions, and duplicates just create chaos.
2. If there is no existing issue, create a new issue, use the right template - PLEASE, DO NOT IGNORE THE TEMPLATE - and provide as much information as possible. Sometimes an example repository is very helpful to reproduce the error.
3. The best Report/Request is the one that already came as a PR - So, if you found the issue or want the feature, why not to contribute?

**Comment by tulup-conner** [comment]
See https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md
