### ISSUE TITLE
Hook into `<Carousel>` `onChange`

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#596]
### Discussed in https://github.com/themesberg/flowbite-react/discussions/440

<div type='discussions-op-text'>

<sup>Originally posted by **jayspirits** November 25, 2022</sup>
Is there a way to access the callback onChange? and how to access the current state of the carousel like for example the current index. i have a gallery where i have to show the current number position of the current photo shown.</div>

I think probably the simplest solution to this problem is to just add a prop to `<Carousel>` that is a function that will execute each time the `<Carousel>` changes slides.

**Comment by ujjwalpandey922** [comment]
Hi can I work on it

**Comment by tulup-conner** [comment]
@ujjwalpandey922 Absolutely, feel free to ask if you have questions about how to contribute

**Comment by ujjwalpandey922** [comment]
Hi @tulup-conner ,
thank you so much for the opportunity ,
can you please elaborate on what is needed to be done and where exactly.
Regards

**Comment by rluders** [comment]
@Alreadywinner can you validate the implementation?
