### ISSUE TITLE
Unit test for Pagination

### ISSUE THREAD

**Issue by k2glyph** [themesberg/flowbite-react#60]
**Is your feature request related to a problem? Please describe.**
The component is missing its unit test.

**Describe the solution you'd like**
Implement the unit test to the component.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tulup-conner** [comment]
Ill take this

**Comment by tulup-conner** [comment]
@bacali95 I yet again forgot to include a tag on this issue lol, can you close it for me
