### ISSUE TITLE
Prevent scrolling on body when Modal is open

### ISSUE THREAD

**Issue by multiwebinc** [themesberg/flowbite-react#604]
Add option to prevent scrolling on `document.body` when Modal is open (or just enable it without having an actual option to do so). If the body can scroll, this leads to double scrollbars when the modal content is long.

**Describe the solution you'd like**
This can be accomplished by adding the following to the Modal component:

```jsx
useEffect(() => {
  if (document) {
    document.body.style.overflow = show ? 'hidden' : 'auto'
  }
}, [show])
```

**Comment by tulup-conner** [comment]
Weird... when I use the modals at https://flowbite-react.com/modal I'm not able to scroll in the background. Can you provide an example of where that is happening to you?

**Comment by multiwebinc** [comment]
@tulup-conner That page does not use default scrollbars, and in fact, you can still scroll the body with the keyboard's arrow keys.

Here's one using default scrollbars:

https://codesandbox.io/p/sandbox/epic-khayyam-87pg9k?file=%2Fpages%2Findex.tsx

Edit: It was working while developing, but now it seems #573 is messing things up.

**Comment by tulup-conner** [comment]
Well, that code sandbox you provided is on an old version (0.3.7) for starters so I'm not totally sure if it is still present in the latest version of the Modal.

Could you share the new error?

**Comment by multiwebinc** [comment]
@tulup-conner No, it's 0.3.8. `"^0.3.7"` installs the latest version between `0.3.7` and less than `0.4.0` ([see here](https://github.com/npm/node-semver#caret-ranges-123-025-004)). You can see from the `package-lock.json` file which version is installed.

![image](https://user-images.githubusercontent.com/901732/220664638-0fe5b6bb-25e5-4118-b073-bc079afa8a78.png)
