### ISSUE TITLE
Breaking in NextJs (SSR): Changes from Pull request #124 are not present in latest src

### ISSUE THREAD

**Issue by samratarmas** [themesberg/flowbite-react#609]
Hello team,

There was a merge of pull request #124 to address ssr last year, however, the latest source code is missing those changes.

Currently flowbite-react in Nextjs results in numerous errors all related to code accesing `document` or `window` when it is not yet present. You can replicate this yourself by importing modal components inside nextjs app. The error that I am getting is:

`ReferenceError: document is not defined
    at ModalComponent (webpack-internal:///(sc_client)/../../node_modules/flowbite-react/lib/cjs/components/Modal/Modal.js:17:50)`

This error stems from the line:
`root = document.body` present in `Modal.tsx`

_Originally posted by @samratarmas in https://github.com/themesberg/flowbite-react/issues/123#issuecomment-1435509021_

**Comment by tulup-conner** [comment]
Well.. that's interesting.

Fixing this along with #611, ergo, 0.4.0

**Comment by tulup-conner** [comment]
https://github.com/themesberg/flowbite-react/pull/495 @rluders This was the problematic PR

**Comment by tulup-conner** [comment]
@samratarmas The fix has been introduced, so if you can't wait to use the new version when it's actually released, consider using patch-package to add the commit temporarily to your repo

**Comment by rluders** [comment]
We should probably introduce some specific tests for nextjs ssr

**Comment by samratarmas** [comment]
It means a lot to the community to know that the team definitely takes ssr very seriously, We appreciate the quick patches!

Definitely, test cases where window is undefined can prevent regressions like this one in the future.

Since this is kind of related to the desire for flowbite team to align with Nextjs (or any other meta-react framework) and future of how react components will be rendered in multiple environments such as in nodejs runtime or the edge runtime inside cloudflare edge workers etc., I would also like to present a small seed for the future:

If the theme context in flowbite-react is made such that using context api is not necessary (so when useTheme hook reads theme context value it could check for a key in a cookie when in nodejs environment instead of trying to access the context value), then flowbite could support many of its components as react server component compatible in nextjs without having to declare them as client components.

Now obviously some components that require user interaction definitely need state and prop drilling, and context api is quite convinent for them, however it would be great experience for Nextjs 13 users if library authors do not rely on useState, useContext, and others for components that do not require user interaction,since those are not available in server components. 

At the very least, sharing the theme can be in a cookie which is supported by both browser and server, hence avoiding wrapping entire app component tree inside a client component because of use of context api. There are also other solutions than cookies, which we can research on if you like this idea. 

I saw another discussion here previously regarding how it was presented as adding "use-client" was an acceptable solution, however if you inspect the page source for nextjs flowbite project you will find that since the flowbite theme context is needed near the root of the component tree in the application, and it is a client component, the inspected page source does not show any content for "use-client" declared components. This can be seen in the community flowbite nextjs starter for example. This is basically making using nextjs and ssr useless altogether for SEO purposes if the inspected page source has none of the starter dashboard text and data.

**Comment by samratarmas** [comment]
It means a lot to the community to know that the team definitely takes ssr very seriously, We appreciate the quick patches!

Definitely, test cases where window is undefined can prevent regressions like this one in the future.

Since this is kind of related to the desire for flowbite team to align with Nextjs (or any other meta-react framework) and future of how react components will be rendered in multiple environments such as in nodejs runtime or the edge runtime inside cloudflare edge workers etc., I would also like to present a small seed for the future:

If the theme context in flowbite-react is made such that using context api is not necessary (eg: when useTheme hook reads theme context value it could check for a key in a cookie when in nodejs environment instead of trying to access the context value, and then depending on whether it's server or client environment we conditionally wrap the app inside of context, or get rid of context altogether for theme and read/write to the cookie in all environments), then flowbite could support many of its components as react server component compatible in nextjs without having to declare them as client components.

Now obviously some components that require user interaction definitely need state and prop drilling, and context api is quite convinent for them, however it would be great experience for Nextjs 13 users if library authors do not rely on useState, useContext, and others for components that do not require user interaction,since those are not available in server components.

At the very least, sharing the theme can be in a cookie which is supported by both browser and server, hence avoiding wrapping entire app component tree inside a client component because of use of context api. There are also other solutions than cookies, which we can research on if you like this idea. 

I saw another discussion here previously regarding how it was presented as adding "use-client" was an acceptable solution, however if you inspect the page source for nextjs flowbite project you will find that since the flowbite theme context is needed near the root of the component tree in the application, and it is a client component, the inspected page source does not show any content for "use-client" declared components. This can be seen in the community flowbite nextjs starter for example where the inspected page source has none of the starter dashboard text and data.  (It could also be that maybe the starter template is doing something incorrect that none of the components in that dashboard page can be seen when you inspect page source), but my main request was to try to support server components at the library level, which can be huge right now because none of the css-in-js based libraries based on emotion in react can be compatible with server components for the time being, and tailwind is fully compatible, its just the javascript in libraries that is making this a hindrance. 

@rluders @tulup-conner

**Comment by rluders** [comment]
Thanks, @samratarmas. I understand the concerns about NextJS and mainly the SSR functionality. We should find a solution to this.

However, using cookies is out of the question, it raises some LGPD problems, so IMHO this is out of the table. We probably need to find some other approach to solve this issue. We do have an issue related to Server Components (https://github.com/themesberg/flowbite-react/issues/448), the best is to discuss any possible approach over there.
