### ISSUE TITLE
Tabs automatically indexing on page load

### ISSUE THREAD

**Issue by benpatersonx** [themesberg/flowbite-react#612]
**Describe the bug**
When you load a page using the tabs component, the first item automatically appears with a focus ring around it or 'indexed' even though it should simply just show as selected.  I believe it is an issue with the tab index.

**To Reproduce**

1. Use the 'Tabs' component from flowbite-react (src/lib/components/Tab/Tabs.tsx)
2. Load/reload the page
3. You'll see that the first tab item is automatically focused/indexed (see screenshots)

**Expected behavior**
All tabs should appear the same until the user interacts with them, apart from the first which should simply be selected not focused like it is.

**Screenshots**
![image](https://user-images.githubusercontent.com/70548361/220189498-04a676c1-ada2-4c68-ab51-55d752cef99c.png)

**System information:**

- Device: Desktop PC
- Resolution: 2560 x 1440
- OS: Windows
- Browser: Google Chrome
- Version: 109.0.5414.120

**Project information:**

- Tailwind: 3.2.7
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: NextJS

**Comment by evanmays** [comment]
+1

**Comment by timomedia** [comment]
+1

**Comment by timomedia** [comment]
Please help us fix this. Currently if each page uses tabs then when accessing the default url it will select the first tab and automatically jump the scroll bar there. It's exactly like the picture above that @benpatersonx posted.

**Comment by ex-oleh** [comment]
focus ring is not the worst thing about this behavior. if you have a card component that has tabs at the bottom of the screen,
the view will always scroll to it on page refresh.

**Comment by timomedia** [comment]
@ex-oleh 
Yes.
It will always scroll to the section tab when the page loads. This is a pretty bad thing.
