### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by mikeknapp** [themesberg/flowbite-react#613]
**Describe the bug**
A number of components (e.g. `SidebarItem` and `Dropdown.Item`) don't include a `key` property, leading to error messages in the console. This wastes a little bit of time each time I'm debugging because I need to glance at the errors to check if they're the same or different.

![Screenshot 2023-02-21 at 11 06 20 am](https://user-images.githubusercontent.com/103593/220215686-5b18bed4-82ed-4332-846f-b45c382dcafb.png)

**To Reproduce**

1. Create a `Dropdown` component with multiple `Dropdown.Item` children. 
2. Notice the errors in your console.

**Expected behavior**
I'd like to be able to pass a `key` property to each child component so that the error disappears.

**Screenshots**
See above

**System information:**

- Device: Mac
- Resolution: 3840 x 1080
- OS: MacOs
- Browser: Chrome
- Version: 110.0.5481.100

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: CRA   <-- what is this, I assume Create React App?

**Additional context**
[Keys](https://reactjs.org/docs/lists-and-keys.html#keys)

Thanks for a brilliant package!! :-)

**Comment by tulup-conner** [comment]
I'm not sure I understand. There are no errors on the live example, https://flowbite-react.com/dropdown, and I can see that there is a key in each `<Dropdown.Item>`. I can also add a key to `<Dropdown.Item>` and `<Sidebar.Item>` alike and it is respected by React on my end.

By the error message, it seems like this is an issue with your custom components, `<TopNav>` and `<SideNav>`. Can you clarify what's going wrong?

**Comment by mikeknapp** [comment]
Ah, you're absolutely right – my apologies Conner. I found the issue in my code – I was wrapping in a span! Thank you for your help.
