### ISSUE TITLE
Check and fix the "No Display Name" for all components at the documentation

### ISSUE THREAD

**Issue by alpzaf** [themesberg/flowbite-react#616]
**Radio Buttons doesn't work because of No Display Name html tag**
`<div className="flex items-center gap-2">
                        <No Display Name  // TS2304: Cannot find name 'No'.
                            id="Admin"
                            name="role"
                            value="Admin"
                            defaultChecked={true}
                        />
                        <Label htmlFor="united-state">
                            Admin
                        </Label>
                    </div>`

 It looks like find and replace typo in codebase

**Screenshots**
![image](https://user-images.githubusercontent.com/77177157/220329539-85b092bf-52ae-41b8-94a0-5071bfa2fdb9.png)

Edit: 
*Screenshot from documentation*
![image](https://user-images.githubusercontent.com/77177157/220330915-bd133484-0be8-46ad-9fdd-9c7a4806eb8b.png)

**System information:**

- Device: Macbook Pro M2 13 inch 16GB
- Resolution: 2560 x 1440
- OS: Macos Ventura
- Browser: Chrome
- Version: Chrome 110.0.5481.100 (Official Build) (arm64) & Ventura 13.0

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: CRA + Vite + Ts

**Comment by rluders** [comment]
This is just an issue with the documentation. 

```jsx
<Checkbox id="accept" defaultChecked={true} />
```

**Comment by tulup-conner** [comment]
We've had a few of these issues, let's collapse to #641
