### ISSUE TITLE
Use custom colors from tailwind.config.js in `color` attribute

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#62]
**Is your feature request related to a problem? Please describe.**
I can't really migrate to `flowbite-react` without the ability to use custom colors I defined in `tailwind.config.js`. At the very least, I need an escape hatch in each component (`className`).

**Describe the solution you'd like**
I would like to be able to define a color, `primary` in `tailwind.config.js`, then use that color in `flowbite-react` components like so:

```js
<Button color="primary">Hi</Button>
```

**Describe alternatives you've considered**
As long as each component provides the ability to directly specify a `className`, I can do this myself.

**Additional context**
n/a

**Comment by rluders** [comment]
This is something that I want to introduce with this #61: the ability to theme supporting. I'm not sure if there is some workaround... @bacali95 any idea?

**Comment by bacali95** [comment]
Hello there, no there is no workaround for this for now.

**Comment by tulup-conner** [comment]
If that's the case, I would like to add `className`s to `Alert`, `Badge`, `Button` as an  escape hatch so users can apply colors themselves.

**Comment by tulup-conner** [comment]
Related issue: #79

**Comment by tulup-conner** [comment]
This should be resolved once theme support is added #92. I'll retroactively add an example of how to accomplish the above example.

**Comment by tulup-conner** [comment]
With #151 we have implemented the first component with theme support that specifically includes the ability to add your own colors.

I will be adding this to buttons this week and will close this with that PR.
