### ISSUE TITLE
Forced block style in dropdown with outline set to true

### ISSUE THREAD

**Issue by Dawid55a** [themesberg/flowbite-react#621]
**Describe the bug**
When you apply outline to Dropdown component, it is showing with different formatting than expected. After investigation, it is happening because of !block class.

**To Reproduce**

1. Use Dropdown component from flowbite-react
2. Set outline={true} 
3. The arrow is now under the text 
![obraz](https://user-images.githubusercontent.com/21986555/220733561-e4dc1c49-af60-48a0-b47e-c90a7aaaba9a.png)

**Expected behavior**
Component should look like this 
![obraz](https://user-images.githubusercontent.com/21986555/220733743-4624ae93-243e-4733-a5c0-2d797d89f670.png)
I removed !block style to achieve this 

**System information:**

- Device: Desktop PC
- Resolution: 2560 x 1440
- OS: Windows
- Browser: Firefox 
- Version: 110

**Project information:**

- Tailwind: 3.2.7
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: NextJS

**Comment by paghar** [comment]
I checked the outline dropdown list; It is correct.

![outline](https://github.com/themesberg/flowbite-react/assets/66066475/e27db60d-f405-40a5-a8e8-bbbc8f72d647)

**Comment by daryazata** [comment]
can't reproduce it either, tested on windows and firefox

**Comment by Dawid55a** [comment]
Yes, on the newest version this bug disappeared. It was fixed on #654.
So this issue can be closed
