### ISSUE TITLE
Allow customizing the button for dropdowns

### ISSUE THREAD

**Issue by multiwebinc** [themesberg/flowbite-react#624]
The Dropdown component is very opinionated.

I suggest adding a customizable `<Dropdown.Trigger>` component that would be used to render the `<button>` element. The `label` prop should be removed from `<Dropdown>` and `arrowIcon` and `floatingArrow` moved to `<Dropdown.Trigger>`.

Also, I would assume that the `<Dropdown.Item>` components would then need to be wrapped to differentiate between the trigger and the items.

Here's example markup that would render a red button with a 3 vertical dots icon:

```jsx
<Dropdown>
  <Dropdown.Trigger className="bg-red-500" arrowIcon={false}>
    Show the dropdown
    <HiDotsVertical />
  </Dropdown.Trigger>
  <Dropdown.Items>
    <Dropdown.Item icon={HiOutlinePencil} onClick={openRatePlanEditDialogAndCloseMenu}>
      Edit
    </Dropdown.Item>
    <Dropdown.Item icon={HiOutlineTrash} className="text-red-700">
      Delete
    </Dropdown.Item>
  </Dropdown.Items>
</Dropdown>
```

Or maybe allow the dropdown to be triggered from any element, not just buttons. Someone might want to use an icon instead of a button. For that, we could add a `<Trigger.Button>` element that would render the button with the arrow icon, but any children of `<Dropdown.Trigger>` can instead be used as a trigger.

**Comment by multiwebinc** [comment]
Now I see you can do `<Dropdown inline={true}>` and then use custom JSX for a button as a label. Maybe this issue isn't an issue after all.

**Comment by tulup-conner** [comment]
Yep, Dropdown is too opinionated. I like your idea - if you have the time to PR this it would be greatly appreciated

**Comment by Bilalzaiter** [comment]
how to make dropdown trigger on hover instead of click

**Comment by jcolvard** [comment]
I'm confused, cn you not customize a Dropdown <button> with tailwind utility class names?

How come

`<Dropdown label="Dropdown button" color="red">
      <Dropdown.Item>Dashboard</Dropdown.Item>
      <Dropdown.Item>Settings</Dropdown.Item>
      <Dropdown.Item>Earnings</Dropdown.Item>
      <Dropdown.Item>Sign out</Dropdown.Item>
    </Dropdown>`

changes the color of the button to red and leaves the dropdown menu alone, and 
    
`<Dropdown label="Dropdown button" className="bg-red-500 hover:bg-red-600">
      <Dropdown.Item>Dashboard</Dropdown.Item>
      <Dropdown.Item>Settings</Dropdown.Item>
      <Dropdown.Item>Earnings</Dropdown.Item>
      <Dropdown.Item>Sign out</Dropdown.Item>
    </Dropdown>`

puts those class names on the dropdown men wrapper, and leaves the button alone? That can't be by design, or am I missing something?

**Comment by nick-stebbings** [comment]
I just found a workaround for this, if you include an extra rule in your imported CSS to target the button.

```
button[data-testid="flowbite-dropdown-target"] {
  @apply bg-red-600;
}
```
