### ISSUE TITLE
Dropdown should close when we click outside

### ISSUE THREAD

**Issue by diamondback15** [themesberg/flowbite-react#625]
**Describe the bug**
Dropdown should close when we click outside

**To Reproduce**

1. Click on the dropdown
2. Click outside the dropdown
3. Dropdown won't close

**Expected behavior**
Dropdown should close

**Project information:**

- Tailwind: 3.0.18
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: Next.js

**Comment by tulup-conner** [comment]
Thank you, I just confirmed this is how it works in the normal Flowbite library. Off the top of my head, I'm not sure what the solution to this is in React but I'm sure it's probably not terribly challenging. I'll add this to 1.0.0

**Comment by tulup-conner** [comment]
Following up, can you reproduce this still? I just tested at https://flowbite-react.com/dropdown and it seems to work fine. Thank you!

**Comment by fsioni** [comment]
> Following up, can you reproduce this still? I just tested at https://flowbite-react.com/dropdown and it seems to work fine. Thank you!

Works well for me too

**Comment by RealEstateGuys** [comment]
It doesn't work fine at https://flowbite-react.com/dropdown ... If you click a dropdown to open it, and then click outside of it, it will close as it should. However, once you've clicked inside the dropdown it will no longer close when you click outside...

**Comment by MykolaM-Redvik** [comment]
Any updates on that?

**Comment by Marian0** [comment]
I can confirm that if you:

1. open the dropdown
2. click on any item
3. Click outside the dropdown

I expect the dropdown to close. But it keeps open.

**Comment by tulup-conner** [comment]
Hey all, it looks like we accidentally tracked this in two issues but you are all correct. There is indeed a problem with this behavior and someone has proposed a solution that works great. Please see #793 - if you have time to create a PR it would be welcome! See https://flowbite-react.com/docs/getting-started/contributing
