### ISSUE TITLE
Component: Datapicker 

### ISSUE THREAD

**Issue by osilkin98** [themesberg/flowbite-react#626]
It would be great if Flowbite shipped with a calendar or date picker out of the box.
There's already a calendar built within Flowbite which requests a datepicker JS script, however this is not currently present within flowbite-react without creating an ad-hoc solution. 
Other component libraries such as React Aria, Mantine, and a few others already ship one, so it'd be great to have one which integrates cleanly within an existing TailwindCSS project.

**Comment by osilkin98** [comment]
Going a little further, it looks like the datepicker component was already implemented in React  by @OMikkel here: [OMikkel/tailwind-datepicker-react](https://github.com/OMikkel/tailwind-datepicker-react). 

We can either add the existing package as a dependency or just recreate the same logic as what OMikkel has done using internal dependencies. The latter approach may be best simply because of issue #611 to be included in release v0.4.0

**Comment by OMikkel** [comment]
Feel free to use parts of my repo. 

I have moved to Spain so i dont have the time to maintain the repo.

If you happen to use the logic and i would appreciate some credit 😃

**Comment by multiwebinc** [comment]
If you're targeting modern browsers, you can also use:

```
<input type="date">
<input type="datetime-local">
<input type="time">
```

**Comment by osilkin98** [comment]
@OMikkel It would definitely make the most sense to integrate as much of your work as possible into the repo, and only fair that you get the credit for it. This way your work could live here and evolve as other components get updates as well.

**Comment by OMikkel** [comment]
Exactly that would be the best solution @osilkin98

**Comment by osilkin98** [comment]
@OMikkel I couldn't find a way to create an issue for this in your repo, but I'm seeing that the Datepicker component breaks when multiple `Datepicker` components are created within the same form.
Do you have any idea why this could be the issue?

**Comment by osilkin98** [comment]
Never mind I figured it out, it was me forgetting to separate the `show` state between the calendars.

**Comment by k1sul1** [comment]
Hate to be _that guy_ but... I tried using the repo in question for a pet project of mine a while ago and it didn't work out. To solve my problems, I ended up using https://react-spectrum.adobe.com/react-aria/useDatePicker.html.

There's literally a Tailwind example on that page. My main annoyance with tailwind-datepicker-react was that there was that it applied `disabledText` theme on... the next month which was a valid range. I don't want to bash the hard work of others, but I had a bunch of other issues with my seemingly simple use case, including but not limited to problems with min & maxDate and theme options being lacking. 

FWIW, all I had to make was a datepicker that prevented you from selecting days in the past and forced to pick at least a week from now. If all you need to have is a static "pick a date, any date" kinda component, then this'll work, but...

I think it's safe to say this is reinventing the wheel. It's a solved problem, and I'm pretty sure the people behind React ARIA have more resources to make nice datepickers.

**Comment by juliankoehn** [comment]
Maybe i am just superduperdump, but aint the change handler missing?

https://github.com/themesberg/flowbite-react/blob/ecf271a8dcb64c7c25e24ad1cfb7c33b8ea3d3bd/src/components/Datepicker/Datepicker.tsx#L72

The current onChange maps to the <TextInput /> as leftover from `restProps`, 

```ts
const changeSelectedDate = (date: Date, useAutohide: boolean) => {
    setSelectedDate(date);

    if (autoHide && view === Views.Days && useAutohide == true && !inline) {
      setIsOpen(false);
    }
  };
```

My `onChange` actually gets never fired.

```
onChange={(e) => {
            console.log(e.target.value);
          }}
```

**Comment by xSyki** [comment]
@rluders As I see @congon4tor added onSelectedDateChanged, can you please realese new beta, beacuse 0.7.1-beta does't have it and i really need it?
