### ISSUE TITLE
Ellipsis in Pagination in React Flowbite

### ISSUE THREAD

**Issue by wb-ts** [themesberg/flowbite-react#629]
Please add Ellipsis Feature in pagination in react-flowbite
![image](https://user-images.githubusercontent.com/88811953/221557689-4826454f-b733-4d56-93dd-bc445f579705.png)

**Comment by rluders** [comment]
@wb-ts does the standard flowbite supports this?

**Comment by zoltanszogyenyi** [comment]
Hey @wb-ts,

Open an issue on the main Flowbite Library and we’ll add a pagination example with ellipsis.

Cheers,
Zoltan

**Comment by wb-ts** [comment]
> Hey @wb-ts,
> 
> Open an issue on the main Flowbite Library and we’ll add a pagination example with ellipsis.
> 
> Cheers, Zoltan

Done.

**Comment by ronsigter** [comment]
@wb-ts may I know where the created opened issue is? A link would be great, thanks!
