### ISSUE TITLE
Carousel view on v0.0.18, the width it not full

### ISSUE THREAD

**Issue by dediananto** [themesberg/flowbite-react#63]
**Describe the bug**
on v0.0.17 we have a bug on carousel control, now on v0.0.18 it has been solved but I got the new bug, the slide width is not full.

**To Reproduce**
1. install flowbite & flowbite-react on nextjs with notus template
2. setup the tailwind config like in the documentation
3. create a carousel component
4. See an error

**Expected behavior**
carousel slide is full

**Screenshots**

![image](https://user-images.githubusercontent.com/92715176/165015860-3ee009ce-e5fc-489c-a73d-bf4d85b55142.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser firefox, chrome
 - Version 99, 100

**Comment by dediananto** [comment]
this issue is because notus theme, they change tailwind config. but I still getting issues with carousel control. the image doesn't change when I click next or prev. How to call flowbite-react? what I do :
import "flowbite"
import {Carousel} from "flowbite-react"

**Comment by rluders** [comment]
@dediananto should we consider this open or closed? :)

**Comment by dediananto** [comment]
@rluders is it ok to continue on this reported issue? or should I create a new issue for the bug (amount of image less than 4)
I also realize that the last image doesn't change. if we have 4 images, the 3rd image does not change to the 4th image. if we have 5 images, the 4th image doesn't change to the 5th image.

**Comment by rluders** [comment]
@dediananto it seems a different issue TBH. If you don't mind, can you create another ticker reporting the issue? As much info, you could add to it, the better. :)

**Comment by dediananto** [comment]
ok, thank you. 
so, let this issue be closed :D
