### ISSUE TITLE
Table docs have invalid tag for Checkbox

### ISSUE THREAD

**Issue by otang** [themesberg/flowbite-react#632]
**Describe the bug**
In the "Checkbox" section of [Tables](https://flowbite-react.com/tables) the example code has `<No Display Name />`, which is invalid. 
EDIT: this actual seems to affect all `<Checkbox />` in the example code. Another example is in [Forms](https://flowbite-react.com/forms).

**To Reproduce**
Go to https://flowbite-react.com/tables

**Expected behavior**
The sample code should have a checkbox element.

**Screenshots**
![image](https://user-images.githubusercontent.com/800081/221882298-287587be-b8eb-438a-bd8c-e23398372d4d.png)
![image](https://user-images.githubusercontent.com/800081/221882751-81193e91-7483-4175-94ab-68d6ff28058d.png)

**Comment by rluders** [comment]
Duplicate with #616
