### ISSUE TITLE
DropdownComponent is not an exported component

### ISSUE THREAD

**Issue by cadomani** [themesberg/flowbite-react#633]
**Describe the bug**
The documentation page for the **Dropdown** shows several examples that have non-functioning code due to an incorrect exported component name (`DropdownComponent` instead of `Dropdown`). Editors will usually suggest the correct component, but beginners and those new to the library may not know how to fix this.

**To Reproduce**

1. Go to the [Dropdown documentation](https://flowbite-react.com/dropdown)
2. Use any of the examples provided in a sample project
3. Component cannot be imported as it does not exist

**Expected behavior**
The examples should work as-is in any project that uses flowbite-react.

**Comment by rluders** [comment]
Duplicate #616
