### ISSUE TITLE
flowbite-react.com: `<No Display Name>`

### ISSUE THREAD

**Issue by osilkin98** [themesberg/flowbite-react#641]
**Describe the bug**
The component name for `<Select />` is shown to be `<No Display Name />` on the documentation for [flowbite-react forms](https://flowbite-react.com/forms).

**To Reproduce**

1. Go to [flowbite-react.com/forms](https://flowbite-react.com/forms)
2. Scroll down to where you see what looks like the select component

**Expected behavior**
It should say `<Select />` 

**Screenshots**

![image](https://user-images.githubusercontent.com/16809287/222625081-530dbf51-976a-40e7-b1c4-af23f717c78e.png)

**System information:**

- Device: PC
- Resolution: 1440p
- OS: Windows 10
- Browser: Firefox
- Version: 110

**Comment by tulup-conner** [comment]
Thanks for making the issue for this. BTW, if you would be able to make a PR resolving this it would be super helpful, let me know, or we can fix it for 1.0.0 regardless :)

**Comment by hrishikeshmane** [comment]
Hi @tulup-conner, mind if I pick this one?

**Comment by tulup-conner** [comment]
Perfect!
