### ISSUE TITLE
Some components' `theme={}` don't allow partials

### ISSUE THREAD

**Issue by Ncookiez** [themesberg/flowbite-react#646]
**Describe the bug**
With the latest update (`0.4.0`) the `theme` prop was added to a ton of components (thank you by the way, was waiting for this for a bit :3).

The `Button` component has it as the following:

```ts
theme?: FlowbiteButtonTheme;
```

This means the entirety of the `FlowbiteButtonTheme` interface needs to be included when passing it a custom theme.

For reference, this is how other components are setup (`Card` example):

```ts
theme?: DeepPartial<FlowbiteCardTheme>;
```

**To Reproduce**

1. Import the `Button` component and use it.
2. Pass it any custom theme through the `theme` prop.
3. See error:

![image](https://user-images.githubusercontent.com/22108522/222805853-2d07b3e3-37d8-47de-9ccc-36d62bb91a2c.png)

**Expected behavior**
The component should take in a partial interface and merge it with the default theme (the latter is already setup).

**Project information:**

- Tailwind: 3.2.7
- Flowbite: 1.6.3
- Flowbite React: 0.4.1
- Type: Next App

**Comment by Ncookiez** [comment]
I've gone ahead and also checked all the other components, and this seems to be the case for the `Carousel` and `Floating` components as well.

**Comment by tulup-conner** [comment]
Thanks for catching that, if you have the ability to submit a PR fixing these it would be wonderful, let me know
