### ISSUE TITLE
`Button` with `as={Link}`

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#655]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change the `Button` root component to use `Link` from `react-router-dom`

**Describe the solution you'd like**
Implement `as={}` property to support `Link` or `a` or `button`.

**Describe alternatives you've considered**
None

**Additional context**
Check this: https://codesandbox.io/s/example-for-button-forked-d51fyi?from-embed

**Comment by DarkSouL11** [comment]
I have similar requirement with next js Link component

**Comment by rluders** [comment]
Please, if someone is interested in working on this one, go ahead. We are going to be happy to review the PR.
