### ISSUE TITLE
Carousel image not show and random slide

### ISSUE THREAD

**Issue by dediananto** [themesberg/flowbite-react#66]
**Describe the bug**
I found 2 bugs that happen to me.  
1. Carousel does not show if I only have images less than 4 (3, 2, or 1)  
2. when the Carousel show (with the minimum image is 4) I realize that the order of the images doesn't match with the image order from my code.

**To Reproduce**
first bug:
1. using flowbite-react on NextJS  
2. try to create a carousel component with 2 images. is the carousel appear properly? in my case, it doesn't show the slide, only the next and prev control button.  
second bug:
1. I use example code on documentation.
```
<Carousel slideInterval={5000}>
  <img
    src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
    alt="..."
  />
  <img
    src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
    alt="..."
  />
  <img
    src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
    alt="..."
  />
  <img
    src="https://flowbite.com/docs/images/carousel/carousel-4.svg"
    alt="..."
  />
  <img
    src="https://flowbite.com/docs/images/carousel/carousel-5.svg"
    alt="..."
  />
</Carousel>
```
2. in my case, carousel-5.svg becomes first slide, 4th and 5th slide. 

**Expected behavior**
the image appears as slide and order position same as the code

**Screenshots**
I add some note on the pictures, hopefully it will help
![Screenshot_1](https://user-images.githubusercontent.com/92715176/165433692-8d37d425-63ec-47f0-844b-10a711a1638d.png)
![Screenshot_2](https://user-images.githubusercontent.com/92715176/165433697-d56a7ba8-9b92-4688-b077-0a66f6b9270e.png)
![Screenshot_3](https://user-images.githubusercontent.com/92715176/165433698-fe3479ac-af1b-4acc-8136-26f4dd8148cd.png)
![Screenshot_4](https://user-images.githubusercontent.com/92715176/165433700-7c6a831a-5e2e-4263-9e7a-6504a236938a.png)
![Screenshot_5](https://user-images.githubusercontent.com/92715176/165433704-0dacf348-d4b4-419f-8bba-363dc3854b42.png)

**Desktop**
 - OS: Windows
 - Browser Firefox v99 and Chrome v100
 - Flowbite-react version 0.0.18

**Comment by rluders** [comment]
Can anyone confirm this bug? @tulup-conner @bacali95 @mouracamila

**Comment by rluders** [comment]
I guess that the issue could be related to NextJS + Flowbite React. I tried to reproduce the error without using NextJS and it doesn't happen to me.

**Comment by bacali95** [comment]
I couldn't reproduce it as well, @dediananto can you please provide a repo example?

**Comment by dediananto** [comment]
hai @bacali95 you can use this [repo ](https://github.com/dediananto/flowbite-react-carousel-issue) to reproduce on your local

**Comment by dediananto** [comment]
> I guess that the issue could be related to NextJS + Flowbite React. I tried to reproduce the error without using NextJS and it doesn't happen to me.

I think so, I try regular flowbite + NextJS and the result is the carousel is not shown. with flowbite react, the carousel is shown but have this issue

**Comment by bacali95** [comment]
@dediananto i see you are using version 0.0.10 of the library which indeed has the described problem, can you please try to use the latest version and check if it works?

**Comment by dediananto** [comment]
@bacali95 ah it's because I install 0.0.18 the first time, and get this issue, I try every previous version to make sure this issue happens from the beginning, and now, the latest version is 0.0.20. I can confirm this issue was gone

**Comment by rluders** [comment]
Since the user confirmed that the issue was gone by updating the library, I'm now closing this issue.

If you feel that this isn't solved feel free to reopen the issue.
