### ISSUE TITLE
`Button`'s `theme={}` not applying

### ISSUE THREAD

**Issue by Ncookiez** [themesberg/flowbite-react#663]
**Describe the bug**
Passing a `theme={}` to a `Button` does nothing.

**To Reproduce**

1. Import `Button` from package
2. Pass it a custom theme through `theme={}`
3. See no changes

**Expected behavior**
The custom theme should be applied to the `Button`.

**Project information:**

- Flowbite React: 0.4.2

**Additional context**
Posting this here to not lose track of it - this was discussed in the Discord last week but I didn't have time to implement it. Will probably get a PR up this week, but if anyone else wants to take this, be my guest.

On Discord, from @rluders :

```ts
const theme = mergeDeep(useTheme().theme.button, customTheme);
const groupTheme = mergeDeep(useTheme().theme.buttonGroup, customTheme.inner ?? {});
```

Splitting the existing `useTheme()` [here](https://github.com/themesberg/flowbite-react/blob/main/src/lib/components/Button/Button.tsx#L98) to something like the above should do the trick. Needs testing.

**Comment by SoulThread2597** [comment]
Seems to be an issue to all compoents when they are applied with an individual theme

**Comment by Ncookiez** [comment]
> Seems to be an issue to all compoents when they are applied with an individual theme

Most likely not - Only confirmed with `Button` so far, although some other components are finicky with their children components (you can send root themes to the parent, but it doesn't correctly pass themes to children, etc.).

Am using custom individual themes just fine on my app with the `Card`, `Dropdown`, `Footer`, `Modal` and `Navbar` components.

**Comment by rluders** [comment]
I'm wondering if someone is interested in creating a PR for this one. I'll be happy to review it this week, or ASAP. Also, I'm curious if this issue is happening in any other components.

**Comment by alvindera97** [comment]
Inline themes for `<Accordion />` not working as well. Especially those that handle borders. I tried to set the inline theme for both `<Accordion />` and `<Accordion.Panel />` to no avail. Here: 

```
export const PriceHistory = () => {
    return <Accordion className="mt-3" alwaysOpen theme={{'root': {
        'base': "divide-y !border-3 !divide-gray-300 border-gray-300 dark:divide-gray-700 dark:border-gray-700",
        'flush': {
            'off': "rounded-lg border-4",
            'on': "border-b border-t border-l border-r"
        }
    }}}>
        <Accordion.Panel theme={{'root': {
            'base': "divide-y !border-3 !divide-gray-300 border-gray-300 dark:divide-gray-700 dark:border-gray-700",
            'flush': {
                'off': "rounded-lg border-4",
                'on': "border-b border-t border-l border-r"
            }
        }}}>
            <Accordion.Title className="!flex !flex-row !items-center" theme={{
                "flush": {
                    "off": "hover:bg-[#FDFDFD] bg-[#FDFDFD] dark:hover:bg-gray-800",
                    "on": "bg-transparent dark:bg-transparent"
                },
                "open": {
                    "off": "",
                    "on": "text-black bg-[#FDFDFD] dark:bg-gray-800 dark:text-white"
                },
                "base": "flex w-full items-center justify-between first:rounded-t-lg last:rounded-b-lg py-5 px-5 text-left font-medium text-black dark:text-gray-400",
            }}>
                <span className="flex items-center">
                    <SlGraph className="mr-1.5" /> Price History
                </span>
            </Accordion.Title>
            <Accordion.Content>
                Graph showing price changes :)
            </Accordion.Content>
        </Accordion.Panel>
    </Accordion>
}
```

When the component rendered, the component was still stuck with the default border.
