### ISSUE TITLE
Giving custom styles to Modal take effect on its complete area rather than the actual box in which content appears

### ISSUE THREAD

**Issue by R-Kazmi** [themesberg/flowbite-react#665]
**Describe the bug**
when adding custom styles to Modal it styles the area, the total area of the screen. instead, it should style the box of the modal.

**To Reproduce**

1. Insert Modal
2. Click on toggle
3. provide style to modal parent
4. style take effect on black area behind modal box

**Expected behavior**
there should be a way to style modal box

**System information:**

- Device: Hp
- OS: Windows
- Browser: Brave

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Comment by Ncookiez** [comment]
Use `theme={{ content: { inner: 'your_tailwind_css_here' } }}` to change the CSS on the modal.

Keep in mind this overwrites the [current content.inner theme](https://github.com/themesberg/flowbite-react/blob/main/src/lib/theme/default.ts#L512) which is `'relative rounded-lg bg-white shadow dark:bg-gray-700'`.
