### ISSUE TITLE
Problems in customizing child elements of components

### ISSUE THREAD

**Issue by lhdeveloper** [themesberg/flowbite-react#667]
I'm developing a project in SPFx using Tailwind and some flowbite-react components.

However, I'm having several problems customizing the components. An example is the ListGroup. I would like to remove the bg-hover that is deployed by default, in addition to customizing some other things like borders, hover etc.

Searching I found a workaround that would try to select the child elements through the className property of the component. example:

To remove gray background on link hover:
`<ListGroupItem className='[&>*a]:hover:bg-transparent'/>`

![Captura de Tela 2023-03-17 às 15 05 00](https://user-images.githubusercontent.com/15928104/225984017-271c39c7-abd6-453a-929a-dd4ab008c50f.png)

This works partially while I'm running my application this selector works, but after building my application it doesn't recognize this css selector.

Would it be possible to implement props for child elements like <a> or <button>? this happens in other components like Card where I needed to customize the image size inside the component, so I had to remove the imgSrc prop and add an img tag inside the component.

![Captura de Tela 2023-03-17 às 15 06 33](https://user-images.githubusercontent.com/15928104/225984271-b9f239be-15ce-4bd9-8b41-d87c0efe0265.png)

**Comment by tulup-conner** [comment]
You'll want to see https://github.com/themesberg/flowbite-react#customize-components. ListGroup.Item's theme is more complex than I would like, but you shouldn't have any issue achieving what you're looking to do here with a custom theme.

**Comment by lhdeveloper** [comment]
Hello my dear. I was able to do the customization I needed with tailwind-children.
With it I was able to access the child elements of flowbite-react components.

**Comment by rluders** [comment]
> Hello my dear. I was able to do the customization I needed with tailwind-children. With it I was able to access the child elements of flowbite-react components.

Cara, `tailwind-children` está `deprecated`. Até onde sei. De qualquer format, dê uma olhada aqui: https://flowbite-react.com/theme
