### ISSUE TITLE
Chore: Simplify pre-commit logic

### ISSUE THREAD

**Issue by JackRobards** [themesberg/flowbite-react#671]
**Is your feature request related to a problem? Please describe.**
Right now the project runs this command on pre-commit: `yarn prettier:fix && yarn lint && yarn test run && yarn build`. This performs:
- Prettier on the whole project.
- Eslint on the whole project.
- Runs all of the tests.
- Fully re-builds the whole project.

There are ways to target just the changed files, like with the already installed `lint-staged` dependency. It would be nice to utilize this tool so that code can be committed more quickly. Especially as the project continues to grow, the pre-commit logic as-is will keep taking longer and longer.

**Describe the solution you'd like**
Make it faster and easier to commit changes to the project. `lint-staged` is a great solution for this, and is already installed but not properly configured. I think switching the `pre-commit` husky hook to use `lint-staged` would be a great and straightforward approach.

 I'm not personally attached to exactly what commands are run as part of the `pre-commit` hook, but think it makes sense to try and avoid building the whole project for each commit, and try to stick to commands that can target only the relevant files. Ultimately, what command are run are up to you all though :).

**Describe alternatives you've considered**
The pre-commit hook could be left as-is, removed, or simplified to only run the linter and prettier. The pull requests are already set up to run full builds, and all of the tests I believe, so every commit does not necessarily need to do all of that checking as well.

I think `lint-staged` is easy enough to set up though, so it's worth spending a bit of time to do it. Giving quick direct feedback on issues while trying to commit can be quite helpful!

**Additional context**
I'm happy to work on this and at least create an initial PR! Feel free to give any feedback on exactly what commands you all would like as part of the lint-staged config, or if you'd prefer a different approach than lint-staged.

**Comment by tulup-conner** [comment]
See my response at #672
