### ISSUE TITLE
TableHead adds `<tr>` wrapper.

### ISSUE THREAD

**Issue by ex-oleh** [themesberg/flowbite-react#676]
Is there any particular reason that `TableHead` implementation adds additional `tr` wrapper around the `children`?
```
export const TableHead: FC<TableHeadProps> = ({ children, className, theme: customTheme = {}, ...props }) => {
  const theme = mergeDeep(useTheme().theme.table, customTheme);

  return (
    <thead className={classNames(theme.head.base, className)} {...props}>
      <tr>{children}</tr>
    </thead>
  );
};
```

When using table components with headless tables implementation the row makes makes all the cells to be treated as one cell.

**Comment by ex-oleh** [comment]
semantically correct, yes. easy to forget - is quite opinionated statement. Table components are building blocks. And there's no need to bake them together for one specific case.
Also this approach simply make cases with multi row headers impossible. And it gives you no way to target  header's row specifically with the TW classes.

**Comment by tulup-conner** [comment]
Feel free to submit a PR! This seems like an easy enough task.

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
