### ISSUE TITLE
dropdown not working

### ISSUE THREAD

**Issue by cesarcarmona** [themesberg/flowbite-react#687]
Dropdown and toggle sidebar button doesn't work if not until page refresh, I have to manually start initDrawers(), but it makes backdrop not work properly.

![image](https://user-images.githubusercontent.com/25070114/230232643-043e1b5b-4bfb-4ffa-a922-c69c608a584d.png)

Thanks!!

**Comment by rluders** [comment]
Not sure. Can you provide more information? Some code? Your package.json info...
We have a template for bugs that asks some questions, I don't know why ppl ignore it.

**Comment by tulup-conner** [comment]
Feel free to reopen this issue once you've followed the issue template. This makes things better for everyone involved.
