### ISSUE TITLE
how to change tab item default active class.

### ISSUE THREAD

**Issue by Isaac-chip** [themesberg/flowbite-react#689]
i want to change tab item default active ,but it is no work.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/42114454/230392200-0debf460-38ec-47eb-bc16-c9412bd21575.png">

**Project information:**

 "dependencies": {
    "classnames": "^2.3.2",
    "flowbite": "^1.6.4",
    "flowbite-react": "^0.4.2",
    "lodash": "^4.17.21",
    "next": "13.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sass": "^1.60.0",
    "swiper": "^9.2.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.1"
  }
**Additional context**

**Comment by rluders** [comment]
Please, check your `theme=` properties, it seems wrong. You don't need to pass`theme={{theme: {}}}`

**Comment by rluders** [comment]
Check: https://github.com/themesberg/flowbite-react/blob/a4f39f5608a46f6c0d4661fa383e70583ab7d592/src/lib/components/Tab/Tabs.tsx#L11

**Comment by Isaac-chip** [comment]
thanks! it works now.
