### ISSUE TITLE
pagination default activity background color is not work.

### ISSUE THREAD

**Issue by Isaac-chip** [themesberg/flowbite-react#690]
i copy the code from https://flowbite-react.com/pagination and ui show the pagination is miss default activity style.
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/42114454/230554840-c7cfd680-92a0-4cd4-b519-db2de43b16bb.png">

**Comment by rluders** [comment]
@Isaac-chip which version are you using? We do have a template for reporting bugs, next time, please, use it.

**Comment by Isaac-chip** [comment]
@rluders  ok.
