### ISSUE TITLE
Accordion Theme not apply

### ISSUE THREAD

**Issue by jaggervlad** [themesberg/flowbite-react#692]
![accordion](https://user-images.githubusercontent.com/45018754/230959582-3c7ee0bb-0e45-4305-a4a5-8aaf5b91689d.png)

Custom theming not working

**Comment by rluders** [comment]
@jaggervlad please, use the bug report template. I don't know which version are u using...

**Comment by tulup-conner** [comment]
Feel free to resumbit after following the standard procedure if you are still having an issue.

**Comment by bonesoul** [comment]
same issue here.

**Comment by Mnehaal2000** [comment]
did we find a solution?
