### ISSUE TITLE
Navbar hamburger icon appear on scroll

### ISSUE THREAD

**Issue by abbeydoyle** [themesberg/flowbite-react#693]
Instead of making the entire header sticky, can there be a feature for the nav to turn into the collapse hamburger icon upon scroll? (The one that appears for small screens)

**Comment by goswamianshuman** [comment]
> Instead of making the entire header sticky, can there be a feature for the nav to turn into the collapse hamburger icon upon scroll? (The one that appears for small screens)

Hello, It must be done from the client side, if it occurs in the template and someone does not want it in their application, this would be a bad option for them. 

You can use the functions of react like state management and use effect which can help you to do so.

**Comment by rluders** [comment]
Thank you for reporting this issue. However, we regret to inform you that we won't be able to address it for the following reasons:

- The reported issue refers to an unsupported old version of our project.
- Our team was unable to reproduce the problem with the information provided.
- Insufficient information was provided to conduct a thorough investigation.

We recommend upgrading to the latest version and submitting a new issue if the problem persists. Thank you for your understanding.
