### ISSUE TITLE
Modal with controlled form input loses focus on keyup

### ISSUE THREAD

**Issue by haron68** [themesberg/flowbite-react#701]
**Describe the bug**
When using state controlled form input in modal the inputs lose focus on each keystroke forcing the user to refocus by clicking on the input in order to continue typing.

**To Reproduce**

1. Create a modal with state controlled form input
2. Click on input
3. Start typing normally

**Expected behavior**
Should not interrupt user while typing

**Screenshots**

https://user-images.githubusercontent.com/27697689/232196777-015f23e4-1e2e-40b2-a5a1-0c2c72c2abdb.mov

**System information:**

- Device: Macbook Pro M1 2020
- Resolution: 13 inch
- OS: Ventura 13.0.1
- Browser: Brave (Chrome-like)
- Version: 1.48.164

**Project information:**

- Tailwind: 3.1.6
- Flowbite: 1.5.5
- Flowbite React: 0.4.2
- Type: CRA/Laravel

**Additional context**

Here's the code to reproduce the issue locally.

```
const ModalPage: FC = () => {

  const [firstName, setFirstName] = useState('');

  return (
     <Modal show={openModal === 'form-elements'} size="md" popup onClose={() => setOpenModal(undefined)}>
        <Modal.Header />
        <Modal.Body>
          <div className="space-y-6 px-6 pb-4 sm:pb-6 lg:px-8 xl:pb-8">
            <h3 className="text-xl font-medium text-gray-900 dark:text-white">Sign in to our platform</h3>
            <div>
              <div className="mb-2 block">
                <Label htmlFor="first_name" value="First Name" />
              </div>
              <TextInput
                id="first_name" 
                name="first_name"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                placeholder="First Name" 
                required 
              />
           </div>
        </Modal.Body>
       </Modal>
  )
};
```

**Comment by haron68** [comment]
This seems like a good workaround for now 
https://stackoverflow.com/a/69544093/7776336

**Comment by grbull** [comment]
I'm having the same issue. A work around is to use uncontrolled inputs until this is resolved.

**Comment by rgwebcode** [comment]
I ran into the same issue, this took me a couple of hours to figure out the cause.
I ended up recreating the <Modal> element using the generated HTML, only changing a part of the `className` (from `hidden` to `flex`) and the `aria-hidden` property from `true` to `false` when opening the modal. This seems to work fine.
The workaround mentioned above also works for the relevant input field, but had other implications which messed with my code.

Of course this is no universal solution either. Maybe #568 will take care of this as well?

**Comment by grbull** [comment]
If you set the root prop on the Modal component, the controlled inputs seem to work as expected. 

For example:

```ts
const ModalPage = () => {
  const rootRef = useRef<HTMLDivElement>(null);

  return (
    <div ref={rootRef}>
      <Modal root={rootRef.current ?? undefined}>
        <Modal.Header />
        <Modal.Body>{/* ... */}</Modal.Body>
      </Modal>
    </div>
  );
};
```

**Comment by rgwebcode** [comment]
> If you set the root prop on the Modal component, the controlled inputs seem to work as expected.
> 
> For example:
> 
> ```ts
> const ModalPage = () => {
>   const rootRef = useRef<HTMLDivElement>(null);
> 
>   return (
>     <div ref={rootRef}>
>       <Modal root={rootRef.current ?? undefined}>
>         <Modal.Header />
>         <Modal.Body>{/* ... */}</Modal.Body>
>       </Modal>
>     </div>
>   );
> };
> ```

This seems to work fine! The example above creates a second wrapper div though.

If you want to avoid this, at least in Next.Js with the new /app directory you can also use 
```<Modal root={document.body}>```
For regular React I haven't tried, but with with the new /app directory, there's no "root div" element anymore, and the Modal div is placed directly as a child of the document body, so the reference to it as the root element works.
Otherwise you might have to define the reference to your root element where it's created and then pass it down the props waterfall.

**Comment by rgwebcode** [comment]
I noticed that my code above, directly referencing `document.root`, actually threw an error, even though the component was defined with `"use client"`. But it worked nonetheless, which is a bit awkward.
Anyway, this is what I now do instead:

```js
const documentBodyRef = useRef(null);

useEffect(() => {
    documentBodyRef.current = document.body;
}, [])


return (
    <Modal
        root={documentBodyRef.current}
        [...]
```

**Comment by AndrejGajdos** [comment]
@grbull thanks for the fix! I have been doing React development for a long time and haven't seen an issue like this.

**Comment by rluders** [comment]
Is it something that we can fix? Is this really a bug? Just documenting it solves the issue?

**Comment by haron68** [comment]
@rluders this seems like a bug to me. There's no reason why inputs should lose focus in the default use case of the modal

**Comment by techgokdeniz** [comment]
> Modal bileşeninde root desteğini ayarlarsanız, kontrol edilen girişler beklendiği gibi çalışır.
> 
> Örneğin:
> 
> ```ts
> const ModalPage = () => {
>   const rootRef = useRef<HTMLDivElement>(null);
> 
>   return (
>     <div ref={rootRef}>
>       <Modal root={rootRef.current ?? undefined}>
>         <Modal.Header />
>         <Modal.Body>{/* ... */}</Modal.Body>
>       </Modal>
>     </div>
>   );
> };
> ```

year may 2023 still this error persists in the library, thank you for the solution

**Comment by IuriPires** [comment]
Also I notice (I can be wrong) the test `should automatically focus the `TextInput` inside the `Modal` when its opened` seems to be a false positive. There's a line `waitFor(() => expect(input).toHaveFocus());` that is not using `await`. When you do so, the test fails. Also I checked that the element on focus is the button that toggles the Modal. I think maybe the person who could potentially check this issue is @myasteiner due his #495 

I saw that in that merge, the Modal guts had changed a bit.

**Comment by suryafn** [comment]
Hi, I faced the same problem. But I'm using class component. what can I do to fix this problem? kinda confuse. Thank you

**Comment by generic-glitch** [comment]
> It occurs because appendChild adds the element new to the DOM.
> 
> Thus it is no longer the same container, thus it is no longer the same `createPortal(...)`. This results in the content being 1:1 the same as in the render before, but the actual identity is different. For uncontrolled inputs this is not a problem, since React does a DOM diffing the content is the same, no changes are made to the DOM.
> 
> The condition `containerRef.current.parentNode !== root` will always be true because root is not set per default. I guess this PR changed the `if`: [3ab9108](https://github.com/themesberg/flowbite-react/commit/3ab91081f5d1f982709d76f9c0fc9772c1541230)
> 
> I will create a PR for this.

I thought this was a problem with the way the model component works.

I researched this for the past few hours, and the issue that I thought occurs here is that my state variables for the input are in the actual export default function component() function, while the input that changes that state is a child for <modal> and then <modal.body> and then so on. Thus, when onChange is triggered, it rerenders everything, and there being several inputs, causes the input to lose focus. That's at least what I **thought** was the issue.

I was not aware this was the problem though. Thank you for the PR.

**Comment by heyimcarlos** [comment]
For the people using Nextjs pages directory, this worked for me:
```typescript
type Props = Omit<ComponentProps<typeof FModal>, "root">;
export default function Modal({ children, ...passThrough }: Props) {
  if (typeof window === "undefined") {
    return null;
  }

  return (
    <FModal root={document.body} {...passThrough}>
      {children}
    </FModal>
  );
}
```
Maybe we want a portal component that handles this? ```Modal.Portal```?

**Comment by loayjah** [comment]
I faced the same bug. The above-mentioned workaround did not directly work for me. The input field once again loses focus when I type the first character, but it doesn't lose focus in any subsequent characters. Here is how I solved it

```
import { Modal } from 'flowbite-react';
import { useEffect, useState, useRef } from 'react';

const CourseEnrollment = () => {
  const [searchContent, setSearchContent] = useState('');
  const rootRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    inputRef?.current?.focus();
  }, [inputRef.current]);

  return (
    <div ref={rootRef}>
      <Modal dismissible show={true} root={rootRef.current ?? undefined}>
        <input
          ref={inputRef}
          type="text"
          placeholder="Search"
          required
          onChange={(e) => {
            setSearchContent(e.target.value);
          }}
        />
      </Modal>
    </div>
  );
};
```

**Comment by pranav-develop** [comment]
I was facing the same issue and finally found a workaround for the same.

Instead of Directly Placing the HTML in <Modal> component. Make a new component with all the logic and call that inside the <Modal>. This should resolve the issue.

The Modal component will then look like:

```
<Modal position="top-center" dismissible show={isOpen} onClose={handleClose} size="2xl">
    <SearchItemComponent handleClose={handleClose} />
</Modal>
```


And the SearchItemComponent will be:

```
function SearchItemComponent() {
    const [inputVal, setInputVal] = useState<string>("");
    return (
        <div>
            {/* Other Component logic */}
            <input value={inputVal} onChange={(e) => setInputVal(e.target.value)} placeholder="Some input" />
            {/* Other Component Logic */}
        </div>
    );
}
```

**Comment by gurleensethi** [comment]
This works the best,

```ts
const ref = useRef(null);

useEffect(() => {
    ref.current = document.body;
}, [])


return (
    <Modal root={ref.current || undefined}
```

Why has this not been resolved yet though 🤷 ?

**Comment by rluders** [comment]
If anyone that has a practical use case for reproducing the issue would like to contribute to fixing this one, we do have [this PR](https://github.com/themesberg/flowbite-react/pull/748) that needs some ❤️ . If someone is interested to work on it, just fork the project, get the changes from that PR, resolve the conflicts, do the required changes from the existing code review, and create a new PR.
