### ISSUE TITLE
为什么sideBar的范例算左对齐，但是实例右对齐呢？

### ISSUE THREAD

**Issue by Tim1nG** [themesberg/flowbite-react#702]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

**Comment by rluders** [comment]
@Tim1nG fica complicado de responder se você não passar nenhuma informação e não escrever em inglês. Eu fiz um esforço aqui e entendi que é alguma coisa relacionado ao alinhamento de itens da sidebar. Por favor, inclua mais informações, o template para reportar bugs está aí para isto.

**Comment by rluders** [comment]
No worries. :)
