### ISSUE TITLE
Use NextJS image optimization

### ISSUE THREAD

**Issue by levino** [themesberg/flowbite-react#706]
**Is your feature request related to a problem? Please describe.**
When I use the `Card` with an image, the rendered html contains a plain old `img` tag. Since I am using `tailwind-react` in a `NextJS` project, it should however use the `Image` component from `next` to benefit from image optimization.

**Describe the solution you'd like**
I suggest to be able to provide a `tag` property to `Card` which defaults to `img`. Then one can overwrite it in `NextJS`-apps with `Image`.

**Describe alternatives you've considered**
Would also possible to make a `flowbyte-nextjs` package or something, but I think above solution is leaner.

**Comment by levino** [comment]
Since I come from [`reactstrap`](https://reactstrap.github.io/?path=/docs/components-card--card#props) I would like `tag` better. We also need to keep in mind that `Image` from `next` needs `width` and `height`. So maybe we need `imageComponent` and `additionalImageProps` which starts to get quite verbose... One could partially apply the `width` and `height` to the `imageComponent` oneself but that is also a little verbose:
```typescript
<Card imageCompontent={(props) => <Image {...props} height={500} width={500} />} ...>...</Card>
```

**Comment by tulup-conner** [comment]
Does `<Card as={(props) => <Image {...props} />} />` work instead? We have been using `as={}` in a lot of components as the universal way to cast a component as another tag so I'd like to keep that convention. Love the idea.

**Comment by levino** [comment]
Of course. Please link a or a couple of examples from the docs if you can. I could make a PR if you want.

**Comment by rluders** [comment]
Do not forget that we are going to need some "magic" to inject the theme into the Image component.

https://github.com/themesberg/flowbite-react/blob/54fc3c2046f45698542bb14fb95af467eafffa99/src/lib/components/Card/Card.tsx#L64
