### ISSUE TITLE
Avatar cannot be customized to justify-[place].] (Always justify-center)

### ISSUE THREAD

**Issue by pippinmole** [themesberg/flowbite-react#708]
**Describe the bug**

**To Reproduce**

1. Use the avatar element
2. Attempt to use justify-left/justify-right

**Expected behavior**
Should be able to use justify-start and align it to the left

**Screenshots**
<img width="908" alt="Screenshot 2023-04-20 at 16 35 49" src="https://user-images.githubusercontent.com/40035529/233416378-29225824-54bc-4ccd-bede-2995c48102cc.png">

The image above shows how the <Avatar> default justify-center overrides my custom justify-start.

If I remove the justify-center, it works as indended:
<img width="912" alt="Screenshot 2023-04-20 at 16 36 57" src="https://user-images.githubusercontent.com/40035529/233416676-7e9e5105-9303-4e51-a099-ffd421b8b8a2.png">

**Project information:*

- Tailwind: ^3.3.1
- Flowbite: ^1.6.5
- Flowbite React: ^0.4.3
- Type: (Not sure what this is)

**Comment by rluders** [comment]
I'm assuming that you are using `className` to pass the `justify-start`, right? So, try to make it important: `!justify-start` (https://flowbite-react.com/theme)

**Comment by pippinmole** [comment]
Oh you're right! Sorry, didn't realise `!` was a thing.
