### ISSUE TITLE
Bug with Pagination as current page selection is not visible.

### ISSUE THREAD

**Issue by adnankarim** [themesberg/flowbite-react#719]
**Describe the bug**

When using the Pagination component in Flowbite React with Tailwind CSS in a NextJS project, the background or interface change for the current page indicator does not appear to be working.

**Screenshots**
![image](https://user-images.githubusercontent.com/44997411/234305424-c722542a-903a-485d-b00a-8fcae80fe017.png)

**System information:**

- Device: Core i7
- Resolution: 1080p
- OS: Windows 11
- Browser: Chrome
- Version: latest

**Project information:**

- Tailwind: 3.3.1
- Flowbite: ^1.6.5
- Flowbite React: ^0.4.3
- Type: CRA

**Comment by tulup-conner** [comment]
It's working at https://flowbite-react.com/pagination - Try upgrading to v0.4.4? There were some changes to this component recently, but I don't know why you'd be having this issue regardless.

**Comment by adnankarim** [comment]
I have updated the component still it is not showing selected page UI interface.

**Comment by Timtendo12** [comment]
> It's working at https://flowbite-react.com/pagination - Try upgrading to v0.4.4? There were some changes to this component recently, but I don't know why you'd be having this issue regardless.

I have the same issue, It seems like the standard `bg-white` is overpowering the `bg-blue `
<img width="696" alt="image" src="https://user-images.githubusercontent.com/41442518/235329448-f05ad72f-18d1-4237-b3dc-ce977e636c32.png">

**Comment by adriangornypl** [comment]
Same problem here :) @Timtendo12 exactly as he described.

**Comment by IuriPires** [comment]
@adnankarim already opened a PR to resolve this issue: https://github.com/themesberg/flowbite-react/pull/725 waiting review.

**Comment by tcrz** [comment]
Still facing this same issue described by @Timtendo12

**Comment by tulup-conner** [comment]
> Still facing this same issue described by @Timtendo12

The flowbite-react.com documentation for Pagination is working correctly, so I'm not really sure what to tell you in this case. If you can provide a reproduction of the issue with more specific detail and possibly explore why it might be happening to you specifically please feel free to create a new issue for it.
