### ISSUE TITLE
Error on ToggleSwitch

### ISSUE THREAD

**Issue by lhdeveloper** [themesberg/flowbite-react#720]
Error when trying to use the ToggleSwitch component.
I just imported it, and when trying to run any function inside my component I get the following error:

caught TypeError: Object(...) is not a function at ToggleSwitch (ToggleSwitch.js:7:21)

**System information:**

- Macbook air M1:
- 1920x1080:
- Mac OS Ventura:
- Chrome:
- 112.0.5615.49 (Versão oficial) (arm64):

**Project information:**

- Sharepoint Framework SPFX v1.16
- Tailwind: 3.1.0
- Flowbite: 1.6.3
- Flowbite React: 0.4.2

**Comment by rluders** [comment]
I have no experience with SPFX. But, try to upgrade the flowbite-react, we are at `0.4.4` currently - and check if it is still happening.

**Comment by tulup-conner** [comment]
We will need to see more specifics on the error because what you've provided isn't super clear.

**Comment by tulup-conner** [comment]
Feel free to resubmit by following the full template with more specific info.
