### ISSUE TITLE
Add full "drawer" support to Sidebar component

### ISSUE THREAD

**Issue by wfsaxton** [themesberg/flowbite-react#721]
**Is your feature request related to a problem? Please describe.**
More functionality on the Sidebar would be useful, similar to that on the vanilla sidebar component.

**Describe the solution you'd like**
Like the vanilla component, I'm requesting the following:

- Support for a sidebar that stashes itself (data-drawer style) at a certain min-width and displays a hamburger menu button instead
- Clicking the hamburger menu button re-displays the sidebar and puts an opaque overlay (drawer-backdrop) over the remaining screen
- Clicking a menu item in the sidebar performs the menu item's function (ie loads a new page) and re-stashes away the sidebar 
- Clicking the opaque overlay re-stashes away the sidebar

**Describe alternatives you've considered**
I've tried using the vanilla component in my react app and it does not work.

**Additional context**
Vanilla sidebar component here: https://flowbite.com/docs/components/sidebar/

**Comment by goswamianshuman** [comment]
Hello, Can I Work with this feature I would love to do so!

**Comment by goswamianshuman** [comment]
@tulup-conner hello, I have created the feature can you please assign me Im unable to pull a request for this issue!

**Comment by rluders** [comment]
I'm closing this one, I think that we should work at the #340
