### ISSUE TITLE
Dropdown causing horitzontal scroll when vertical scroll bar present

### ISSUE THREAD

**Issue by daniel-milemarker** [themesberg/flowbite-react#723]
**Describe the bug**
When a dropdown is placed in the top right corner of a page that has a vertical scroll bar, this causes a horizontal scrollbar to appear when it is not necessary.

**To Reproduce**

1. Place dropdown in top right corner of a page. 
2. Create enough content for a vertical scroll bar.
3. Load page and horizontal scroll bar is shown.
4. Once you click the dropdown, the position is recalculated and the horizontal scroll bar goes away.

**Expected behavior**
The vertical scroll bar should be taken into account during the initial position calculation so the horizontal scroll bar is not shown.

**Screenshots**
On page load, the assumed location of the dropdown is under the vertical scroll bar. This causes the presence of the horizontal scroll bar.
![image](https://user-images.githubusercontent.com/98341433/235271369-bdb3dcf4-4de4-4515-9799-9f19184582f9.png)

After click on the dropdown, the calculated position moves, causing the horizontal scroll bar to go away.
![image](https://user-images.githubusercontent.com/98341433/235271445-cda883c1-456f-429a-9324-36f77a721e20.png)

**System information:**

- Device: Desktop
- Resolution: 4k
- OS:  Windows 10
- Browser: Chrome
- Version: Version 112.0.5615.138 (Official Build) (64-bit)

**Project information:**

- Tailwind: 3.1.6
- Flowbite: 1.6.5
- Flowbite React: 0.4.3
- Type: CRA

**Additional context**
n/a

**Comment by rluders** [comment]
Too old, and unreproducible.
