### ISSUE TITLE
Huge warning with Icons

### ISSUE THREAD

**Issue by Timtendo12** [themesberg/flowbite-react#724]
**Describe the bug**
When importing a Icon. I get a huge warning in my console. `The requested module 'xxx' contains conflicting star exports for the names`

**To Reproduce**

1. Use an Icon (I use: `import {HiClock, HiLockClosed, HiSparkles} from "react-icons/all"`);

**Expected behavior**
No Warnings

**Screenshots**
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/41442518/235330251-d632ace4-d654-4b62-9161-f48c4aa03e67.png">

**System information:**

- Device: Macbook Pro 13'inch 2022
- Resolution: 2560 x 1600
- OS: MacOS Catalina
- Browser: Arc Browser (Chromium)
- Version: Version 0.101.2 (38549) Chromium Engine Version 112.0.5615.137

**Project information:**

- Tailwind: 3.3.1
- Flowbite: 1.6.5
- Flowbite React: 0.4.4
- NextJS: 13.3.1
- Type: CRA

**Additional context**

**Comment by tulup-conner** [comment]
Why would you report an issue with react-icons on this repository? Regardless, I have no idea what the issue is.

**Comment by Timtendo12** [comment]
> Why would you report an issue with react-icons on this repository? Regardless, I have no idea what the issue is.

Is it not included in this repository?
