### ISSUE TITLE
ToggleSwitch not showing correctly

### ISSUE THREAD

**Issue by rgwebcode** [themesberg/flowbite-react#728]
The ToggleSwitch element doesn't appear correctly, the handle seems to be missing.

![image](https://user-images.githubusercontent.com/47830488/235729734-e63a212a-ce2c-407b-9cad-0a675b9dbef1.png)

```JSX
<div className="[&>*]:mb-3">
    <ToggleSwitch
        onChange={() => {}}
        label="Unchecked ToggleSwitch"
        checked={false}
    />
    <ToggleSwitch
        onChange={() => {}}
        label="Checked ToggleSwitch"
        checked={true}
    />
</div>
```

The toggle switch on https://flowbite-react.com/forms does look fine. The generated HTML code is also the same, but the `.toggle-bg:after` style seems to be missing (which generates the handle).

Windows 10
Chrome 112.0.5615.138 (& Firefox)

flowbite-react 0.4.4
flowbite 1.6.5
tailwindcss 3.3.2 (and 3.3.1)

**Comment by tulup-conner** [comment]
If the selector you mentioned is missing, you are probably forgetting to import flowbite as a plugin in your Tailwind CSS config.

Anyway, this isn't a bug, since as you mentioned, it works correctly on the live documentation site. I don't like the way this feature depends on the vanilla library's arbitrary CSS selectors, if someone wants to change it.

**Comment by rgwebcode** [comment]
The

> If the selector you mentioned is missing, you are probably forgetting to import flowbite as a plugin in your Tailwind CSS config.
> 
> Anyway, this isn't a bug, since as you mentioned, it works correctly on the live documentation site. I don't like the way this feature depends on the vanilla library's arbitrary CSS selectors, since they aren't documented anywhere and arbitrarily override the behavior of random components. It basically undoes the benefits of Tailwind CSS entirely. If someone wants to change it, I would love that.

Flowbite is imported correctly, `Modal`, `Button`, `RangeSlider`, and `TextInput` work fine on the same page, just `ToggleSwitch` doesn't.

I tried to create a test case on codesandbox.io, but haven't yet figured out how to properly import tailwind and flowbite there.
