### ISSUE TITLE
Prevent scrolling of body fails if there are multiple modals on a page

### ISSUE THREAD

**Issue by rgwebcode** [themesberg/flowbite-react#729]
The new code added in #700 fails if there are multiple modal on a page. The code is called for each modal on the page, and the overflow property is being set for each modal's `show` parameter, which most of the time results in `overflow: "auto"`, unless you happened to open the last modal in the queue.

**Comment by rgwebcode** [comment]
This modification seems to work, but I don't know if it's a good practice.
I've re-added and modified the `useEffect` code that was in the first commit of #700 and added an `isOpen` state that determines the value of the overflow property.

```JSX
const [isOpen, setIsOpen] = useState(false);

[...]

// Prevent scrolling of the root element when the modal is shown
useEffect(() => {
    if (root && show != isOpen) {
        root.style.overflow = show ? 'hidden' : 'auto';
    }

    setIsOpen(show);
}, [root, show, isOpen])
```

**Comment by tulup-conner** [comment]
This would be an excellent opportunity for someone to add a test case for multiple modals. It's a use case I hadn't personally considered before, either. I don't use them much.

**Comment by stuart-williams** [comment]
Possibly related to this issue, I'm seeing that overflow hidden is not removed from body on modal close so page scrolling is broken!

**Comment by rluders** [comment]
Probably dup with #829 - anyway, I'm closing this one since it is older.
