### ISSUE TITLE
Pressing Esc always toggles the onClose handler for modals, even if modal is hidden

### ISSUE THREAD

**Issue by rgwebcode** [themesberg/flowbite-react#732]
If your `onClose()` handler is something like `() => {setPopupOpen(!popupOpen)}`, pressing escape will actually show the modal when it is hidden, since there is no check in the `useKeyDown('Escape')` handler if the modal is visible or not.

It also does not stick to the current modal if there are multiple modals on a page, i.e. it will show a second modal when you press Escape with an already active modal instead of closing it.

Adding `show` to the check avoids this and will not open a modal when pressing Escape anymore.

```JSX
useKeyDown('Escape', () => {
    if (dismissible && onClose && show) {
        onClose();
    }
});
 ```
But it still doesn't work correctly if there are multiple _stacked_ modals. In this case it will close the underlying modal first, and only on the second press the top most modal (or I guess it depends on whichever modal was defined first).
 
 Maybe #568 could avoid all of this.

**Comment by rluders** [comment]
I'll assume that this isn't a problem anymore, since we merged some changes to the modal component.
