### ISSUE TITLE
ToggleSwitch color: Type 'string' is not assignable to type 'string & FlowbiteColors'.

### ISSUE THREAD

**Issue by seyeo** [themesberg/flowbite-react#736]
**Describe the bug**
ToggleSwitch color prop does not accept a string (Typescript)

**To Reproduce**

```
  <ToggleSwitch
                    color={'blue'}
                    checked={true}
                    label="Test" 
                />
```

**Expected behavior**
When compiling for production, it breaks and you get the error "Type 'string' is not assignable to type 'string & FlowbiteColors'."

**Screenshots**

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: CRA

**Additional context**

**Comment by IuriPires** [comment]
@seyeo  I think your problem is the Flowbite version. I tested the 0.4.4 and it's not happening anymore. Which lead us to understand it's already fixed.

**Comment by IuriPires** [comment]
https://github.com/themesberg/flowbite-react/assets/24615675/764d9b9d-8d64-4f2c-ad83-0aacb99c848f

Follow up the test I made. Note: before I upgraded to 0.4.4, I was in the 0.4.1 version and I was able to see the problem happening.

**Comment by IuriPires** [comment]
@rluders could you back me up on this. Just to have your words. As I said, seems to be fixed.

**Comment by IuriPires** [comment]
@seyeo sorry, I deleted my previous comments because I forgot to test the build. And yes, it's breaking when we try to build it.

**Comment by rluders** [comment]
I could also reproduce it.

**Comment by IuriPires** [comment]
@seyeo I opened a PR related to your issue. [PR 741](https://github.com/themesberg/flowbite-react/pull/741 ). Just waiting it to be reviewed.
