### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by IuriPires** [themesberg/flowbite-react#740]
**Describe the bug**
While trying to build the project, it fails due typescript interfaces mismatch.

**To Reproduce**
 1 - Clone the repo
 2 - Try to run `yarn build` or `yarn build:storybook` 
 3 - Report from terminal: **Interface 'FloatingProps' incorrectly extends interface 'PropsWithChildren<Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style">>'.
  Type 'FloatingProps' is not assignable to type 'Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style">'.
    Types of property 'content' are incompatible.
      Type 'ReactNode' is not assignable to type 'string | undefined'.
        Type 'null' is not assignable to type 'string | undefined'.**

**Expected behavior**
The project to be built correctly without any errors.

**Screenshots**

<img width="1512" alt="Captura de ecrã 2023-05-13, às 12 19 27" src="https://github.com/themesberg/flowbite-react/assets/24615675/d6115dd7-660d-4e2e-b757-b2657ca9bb4e">

**System information:**

- Device: Macbook Pro M1
- Resolution:
- OS: MacOS Ventura
- Browser:
- Version:

**Project information:**

- Tailwind: ^3.2.7
- Flowbite: ^1.6.3
- Flowbite React: 0.4.4
- Type: Flowbite-react own project

**Additional context**

**Comment by IuriPires** [comment]
Hey @rluders @tulup-conner  check this out.

**Comment by rluders** [comment]
I'm using MacOS as well. No issue to compile the project, also CI isn't failing to compete.

```sh
➜ node -v
v19.2.0
```

**Comment by IuriPires** [comment]
@rluders thank you! I removed node_modules and reinstalled it. Seems to be fine. Sorry about that. Gonna close the issue.
