### ISSUE TITLE
The theme prop of the Button component is not working

### ISSUE THREAD

**Issue by ductinhkzz** [themesberg/flowbite-react#745]
**Describe the bug**
when I prop theme in the Button component. it was not working

**To Reproduce**
```
<Button size='sm' color='success' theme={{ inner: { base: 'p-0' }}}>
      Test button
</Button>
```

**Expected behavior**

**Screenshots**

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.3.2
- Flowbite: 1.6.5
- Flowbite React: 0.4.4
- Type: nextjs

**Additional context**

**Comment by IuriPires** [comment]
Hi @ductinhkzz , seems that a related issue was already opened: https://github.com/themesberg/flowbite-react/issues/663

**Comment by ductinhkzz** [comment]
Duplicate (https://github.com/themesberg/flowbite-react/issues/663)
