### ISSUE TITLE
Navbar shadow not working !

### ISSUE THREAD

**Issue by Lekhrajk** [themesberg/flowbite-react#747]
**Describe the bug**
I am using sidebar with navbar but shadow style is not working with navbar it is working well with sidebar

**To Reproduce**
className = "shadow-[size]" should work

**Expected behavior**
Tailwind shadow property should reflect based on the classes.

**System information:**

- Device: Asus vivobook s14 
- Resolution: 1920*1080
- OS: Window 11
- Browser: Chrome
- Version: 113.0.5672.93

**Project information:**

- Tailwind: 3.3.2
- Flowbite: 1.6.5
- Flowbite React: 0.4.4
- Type: npx create-next-app@latest

**Comment by rluders** [comment]
`className="!shadow-[size]"`
