### ISSUE TITLE
Timeline with direction option

### ISSUE THREAD

**Issue by oriML** [themesberg/flowbite-react#749]
**Is your feature request related to a problem? Please describe.**
Timeline point is on the left to the content, because of position rule it cant be from the right.
I would like to have the option to set the point from the right and the content to the left by direction prop.
It's a great solution for rtl languages apps as Heb or Arab etc.

**Describe the solution you'd like**
To add a direction prop, by default as it now, value type is string (rtl | tlr).
change the style of <ol> to match the user's value.

**Describe alternatives you've considered**
add style.css with following definitions does do the work:
[data-testid="timeline-item"] [data-testid="timeline-point"] span {
    right: -0.75rem;
}

[data-testid="timeline-component"] {
    border-right: solid #E5E7EB 1px;
    border-left: 0;
}

**Additional context**
I want the content to be on the red section
![image](https://github.com/themesberg/flowbite-react/assets/74620764/a0a754e8-2623-42bd-99dd-6d283ea3144a)

**Comment by rluders** [comment]
@oriML this library is just an implementation of the standard components from flowbite to React, so normally, if there is no support for this kind of feature at the standard flowbite we don't implement it.

Anyway, @zoltanszogyenyi do we have this kind of implementation at the standard @flowbite library? Do we have plans to add support to it?

**Comment by tulup-conner** [comment]
Thank you for the idea - I can see why it's practical, but this isn't described in the upstream library at flowbite.com, so, we shouldn't have it.
