### ISSUE TITLE
Default modal in position:fixed element didn't cover full screen

### ISSUE THREAD

**Issue by emewjin** [themesberg/flowbite-react#75]
**Describe the bug**
Hi, I'm trying to use flowbite-react's modal component (I know it is still WIP) and found something odd.
I expected modal will be on top of all html layout, but as you can see in attached img, modal confined in area (the blue area in img) that where modal used. The blue area's css position was `fixed`
![image](https://user-images.githubusercontent.com/76927618/166182614-c72a547e-3cc0-4df4-8f81-07d56bbd536d.png)

Is it intended? or will be fixed in official release version?

**To Reproduce**

1. put flowbite-react modal in `fixed` div like below screenshot. I just copy Default modal example code from [your docs](https://flowbite-react.com/#/modal)
  
![image](https://user-images.githubusercontent.com/76927618/166182809-3007fe4b-5d13-444f-bbba-9dbe896308c4.png)

2. open modal

**Expected behavior**

What I expected was full cover modal like below screenshot
![image](https://user-images.githubusercontent.com/76927618/166182677-7d6eab42-9a15-425b-805d-467548d27c6f.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac os monterey 12.3.1
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 100.0.4896.127

**Additional context**

**Comment by tulup-conner** [comment]
Is there a chance you could provide a code sample? I created the following and it works: https://gist.github.com/tulup-conner/c944b464eebc39b77707513f153e2eda

**Comment by emewjin** [comment]
@tulup-conner sorry for confusing you, here is [sample](https://github.com/emewjin/flowbite-react-playground/blob/main/src/App.js). I think the cause of this problem is `translate`

**Comment by bacali95** [comment]
Hello @emewjin, thanks for reporting this issue, I understood what is the issue and I will take a look.
