### ISSUE TITLE
ScrollBar issue if we toggle it from bottom of the screen

### ISSUE THREAD

**Issue by Alreadywinner** [themesberg/flowbite-react#761]
**Description**
Flowbite modal removes the scroll bar forever if I toggle it from Flowbite footer component

**To Reproduce**

1. Go on bottom of the screen to the footer area
2. On footer press any button that toggle Modal
3. Close the Modal and you will see the main page scroll bar remains hidden

**Expected behavior**
If I open the Modal it should hide the main scrollbar smoothly as it is doing but on closing the Modal it should display the scrollbar again.

**Screenshots**
**Scroll to footer and Press on pressing terms and Condition button** :
![image](https://github.com/themesberg/flowbite-react/assets/53277768/d09c3351-38cf-4b83-8d1f-33168ca87ae1)

**Modal Appears and Scrollbar is hidden**:
![image](https://github.com/themesberg/flowbite-react/assets/53277768/43bda4a4-4690-43d3-9f07-ac0000244861)

**Now on pressing cross icon the scrollbar remains hidden**
![image](https://github.com/themesberg/flowbite-react/assets/53277768/95710b54-f6b7-421c-9925-04fd8d38fe1c)

**System information:**

- Device:
- Resolution:
- OS:
- Browser: Brave Browser
- Version:

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: Vite React 

**Additional context**
On Inspecting I found out that `overflow:hidden` property gets applied when I open up the modal, and on closing the modal the `<body />` tag have the property `overflow:auto` with it I think this should not happen

**Comment by tulup-conner** [comment]
Thank you. I can confirm this behavior and the cause is here: https://github.com/themesberg/flowbite-react/blob/main/src/components/Modal/Modal.tsx#L126

We have an open PR that will fix this in 1.0.0, but I would be happy to introduce this in an earlier release, since it's just a bug fix. If you're able to, it would be great if you could open a PR that literally just replaces that line by `'hidden' : ''`.

**Comment by Alreadywinner** [comment]
Yeah sure I would love to solve this issue one more thing how to set up the
library ? I mean should I clone it and then make a change ?

**Comment by tulup-conner** [comment]
Check out the contributing guide: https://www.flowbite-react.com/docs/getting-started/contributing

**Comment by Alreadywinner** [comment]
Thanks a lot I will do it today and let you know so that you can review the
code

**Comment by Alreadywinner** [comment]
@tulup-conner [pull request](https://github.com/themesberg/flowbite-react/pull/769) is made and ready for review

**Comment by Alreadywinner** [comment]
Fixed And Now it's working
