### ISSUE TITLE
`<DarkThemeToggle fillRule=".." />` Error

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#770]
### Discussed in https://github.com/themesberg/flowbite-react/discussions/750

<div type='discussions-op-text'>

<sup>Originally posted by **Jeremyjins** May 18, 2023</sup>
I'm using Remix framework.

I have tried many ways to remove fillRule error when I use DarkThemeToggle component.

Error message like this.
"Warning: Prop `fillRule` did not match. Server: "null" Client: "evenodd""

This error only occurred the first render and not happen afterward.
I guess this is hydration issue.

Any suggestion?</div>

**Comment by tulup-conner** [comment]
@Jeremyjins I'm aware of this issue, as it's happened to me as well, so I'm creating an issue out of your discussion. Thank you!

**Comment by SutuSebastian** [comment]
Fixed in version [0.7.0](https://www.npmjs.com/package/flowbite-react/v/0.7.0).
