### ISSUE TITLE
Option 2: Create a custom theme docs are incorrect

### ISSUE THREAD

**Issue by codeams** [themesberg/flowbite-react#773]
**Describe the bug**
Option 2 for theme customization doesn't work as [described here](https://www.flowbite-react.com/docs/customize/theme).
```jsx
{/* doesn't work */}
<Flowbite
  theme={customTheme}
>
```
```jsx
{/* works */}
<Flowbite
  theme={{
    theme: customTheme,
  }}
>
```

**To Reproduce**

1. Attempt to setup following [Option 2 in this docs page](https://www.flowbite-react.com/docs/customize/theme)
2. Get the following error: `The expected type comes from property 'theme' which is declared here on type 'IntrinsicAttributes & FlowbiteProps'`

**Expected behavior**
Documentation should work as expected. Either modify type definition or docs.

**Screenshots**

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.3.2
- Flowbite: 1.6.5
- Flowbite React: 0.4.6
- Type: Vite React-Typescript

**Comment by tulup-conner** [comment]
Oh man, that's embarrassing. Thank you for catching that, I'll hotfix this.

**Comment by tulup-conner** [comment]
Fixed in https://github.com/themesberg/flowbite-react/commit/b472d859c9c61d56f74e0312e1e86c072d8f5168, forgot to mention it, thank you!
