### ISSUE TITLE
Button className theme override not working

### ISSUE THREAD

**Issue by codeams** [themesberg/flowbite-react#774]
**Describe the bug**
Option 1 of theme customization [described here](https://www.flowbite-react.com/docs/customize/theme) will not work sometimes. The custom class is appended to the default class of the rendered `button`. This will work if the custom class is added to the DOM below the default class, and won't work if the class is in the DOM above the default class, given the "cascading" nature of CSS.

Example: bg-orange-500 will override default bg-cyan-500. But, bg-blue-500 won't override bg-cyan-500.

```jsx
{/* works, you get an orange button */}
<Button className="bg-orange-600">My button</Button>

{/* doesn't work, uses cyan (default) anyway */}
<Button className="bg-blue-600">My button</Button>
```

**To Reproduce**

1. Attempt to override button background with any color where the first name is sorted before "cyan" – for example, blue.
2. Run your project and inspect in browser.
3. You will see your custom className attached at the end of the rendered class attribute of the native button.
4. Go to computed tab of dev tools, look for background-color, you will see cyan is being used.
5. Attempt again with a color appended after cyan – for example, orange.
6. Build, inspect, and you will again see orange at the end.
7. This second time, the browser decides to use orange instead of cyan. Ignoring order inside the class attribute, and using some other order.
8. When using something like Vite hot reload, if you change the color for bg-blue-700 for example, you will see it appear. I believe because hot-reload is injecting this style at the end of the <head> element of the DOM. This is, being below in the "cascade" and therefore being the one used by the browser.

**Expected behavior**
All overrides should work, regardless of compiling/minimizing/rendering/etc.

**Screenshots**
–

**System information:**

- Device: Macbook Pro
- Browser: Edge (should be independent of browser).

**Project information:**

- Tailwind: 3.3.2
- Flowbite: 1.6.5
- Flowbite React: 0.4.6
- Type: Vite React-Typescript

**Additional context**
I did not test this with other components, but might as well apply there too.
Also, let me know if this is intended behavior. We might need to clarify that in the docs.

Edit: Rewrite with my most recent understanding of why this isn't working.

**Comment by codeams** [comment]
To summarize the above:

Inline override as [described here in Option 1](https://www.flowbite-react.com/docs/customize/theme) will not work sometimes.

It will depend on wether or not the custom class used is injected in the DOM above or below the default one. Highly dependent on the stack used to compile/minimize styles.

**Comment by codeams** [comment]
Forgot to mention a workaround I've been using:
- Make custom classes more specific to force preference. For example using `sm:bg-blue-600` will achieve the same result, but since it's inside a media query, has higher precedence and therefore guaranteeing the overwrite will work.

**Comment by rluders** [comment]
@codeams the best thing here is to use `!` whenever you want to overwrite an already existing style. But, it seems that the documentation doesn't leave it explicit. @zoltanszogyenyi

**Comment by rluders** [comment]
@codeams Another option is to create your own theme color for the buttons. So you will be adding a new color, and you can use something like:

```jsx
<Button color="my-color">My button</Button>
```

**Comment by rluders** [comment]
BTW, since we introduce the `twMerge` this is not an issue anymore.
