### ISSUE TITLE
Docs(Modal): placement doesn't update

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#780]
**Describe the bug**

When going to the modal docs page (https://www.flowbite-react.com/docs/components/modal) and browse to the placement options after updating the position the modal preview doesn't reflect this.

**To Reproduce**

1. Go to https://www.flowbite-react.com/docs/components/modal
2. Scroll down to modal placement
3. Click on one of the positions
4. The position is always centered

**Expected behavior**

The appropiate modal positions should be reflected.

**Screenshots**

Selected "bottom center" but the modal is still just centered without being on the bottom.

<img width="1109" alt="Screenshot 2023-05-30 at 10 49 18" src="https://github.com/themesberg/flowbite-react/assets/8052108/b38fab48-0bda-48a8-8eb1-7516705edd77">

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

None.

**Comment by tulup-conner** [comment]
This is no longer an issue.
