### ISSUE TITLE
Div around my react components.

### ISSUE THREAD

**Issue by JagGunawardana** [themesberg/flowbite-react#786]
I'm using flowbite-react in a ClojureScript project. It is working ok with a small problem. I want some components to be inline e.g. tooltip, dropdown etc. Every component is wrapped in a div like so:

<div class="w-fit" ...> Drop down/tooltip is here </div>

I can't see a way of getting rid of this div that is wrapping things. Anyone else seen this?

I'm using the latest versions of Tailwindcss and flowbite-react.

**Comment by rluders** [comment]
Closing this issue. Please, create it again using the template.
