### ISSUE TITLE
Bug - Table img version compatibility issue (no longer works above v0.3.8) 

### ISSUE THREAD

**Issue by suaterken** [themesberg/flowbite-react#792]
Hello,

We are using flow bite-react tables in the Remix project, [link to the repo](https://github.com/vendure-ecommerce/storefront-remix-starter).
I have tried to upgrade flowbite-react version but suddenly Table component started adding a mask above the image. I couldn't find any reported issue for this.  The issue is reproducible on both Windows & Mac. Please see the attachments;

Code block Table usage;

return (
        <div className='container mx-auto'>
            <Table>
                <Table.Head style={{ backgroundColor: '#f7f7f7' }}>
                    <Table.HeadCell>
                        Image
                    </Table.HeadCell>
                    <Table.HeadCell>
                        Product Name
                    </Table.HeadCell>
                    <Table.HeadCell>
                        Quantity
                    </Table.HeadCell>
                    <Table.HeadCell>
                        Price
                    </Table.HeadCell>
                </Table.Head>
                <Table.Body className="divide-y">
                    {(orderLines ?? []).map((line) => (
                        <>
                            <Table.Row className="bg-white">
                                <Table.Cell className="whitespace-nowrap font-medium text-gray-900">
                                    <img
                                        width={"80"}
                                        height={"80"}
                                        src={
                                            line.featuredAsset?.preview +
                                            '?preset=thumb'
                                        }
                                        alt={line.productVariant.name}
                                        className="object-center object-cover"
                                    />
                                </Table.Cell>
                                <Table.Cell>
                                    <div className="flex justify-between text-base font-medium text-gray-900">
                                        <h3>
                                            <Link
                                                to={`/products/${line.productVariant.product.slug}/`}
                                            >
                                                {line.productVariant.name}
                                            </Link>
                                        </h3>
                                    </div>
                                </Table.Cell>

                                <Table.Cell>
                                    {editable ? (
                                        <Form>
                                            <select
                                                disabled={!isEditable}
                                                id={`quantity-${line.id}`}
                                                name={`quantity-${line.id}`}
                                                value={line.quantity}
                                                onChange={(e) =>
                                                    adjustOrderLine &&
                                                    adjustOrderLine(
                                                        line.id,
                                                        +e.target.value,
                                                    )
                                                }
                                                className="max-w-full rounded-md border border-gray-300 py-1.5 text-base leading-5 font-medium text-gray-700 text-left shadow-sm focus:outline-none focus:ring-1 focus:ring-primary-500 focus:border-primary-500 sm:text-sm"
                                            >
                                                <option value={1}>1</option>
                                                <option value={2}>2</option>
                                                <option value={3}>3</option>
                                                <option value={4}>4</option>
                                                <option value={5}>5</option>
                                                <option value={6}>6</option>
                                                <option value={7}>7</option>
                                                <option value={8}>8</option>
                                            </select>
                                        </Form>
                                    ) : (
                                        <div className="text-gray-800">
                                            <span className="mr-1">Quantity</span>
                                            <span className="font-medium">
                                                {line.quantity}
                                            </span>
                                        </div>
                                    )}
                                </Table.Cell>
                                <Table.Cell>
                                    <p className="ml-4">
                                        <Price
                                            priceWithTax={line.linePriceWithTax}
                                            currencyCode={currencyCode}
                                        ></Price>
                                    </p>
                                </Table.Cell>
                            </Table.Row>
                        </>
                    ))}
                </Table.Body>
            </Table>

        </div>
    );

v0.3.8
![image](https://github.com/themesberg/flowbite-react/assets/7967939/469ca98d-da68-449d-b898-935b5af146f6)

any version above v0.3.8
![image](https://github.com/themesberg/flowbite-react/assets/7967939/314dc8f1-12e6-40da-a94f-390fc79b3f44)
![image](https://github.com/themesberg/flowbite-react/assets/7967939/3e63e105-f487-4078-9749-865313ab5df9)

Thanks
Suat

**Comment by rluders** [comment]
Can't confirm, and `0.3.x` is unsupported now.
