### ISSUE TITLE
Last "full width tab" wraps

### ISSUE THREAD

**Issue by gsterndale** [themesberg/flowbite-react#813]
**Describe the bug**
The last tab in a tab group that has the style="fullwidth" prop wraps below the preceding tabs.

**To Reproduce**

1. Go to [Tab Component Documentation](https://www.flowbite-react.com/docs/components/tabs)
2. Scroll down to 'Full width tabs'
3. See the "Disabled" tab below the others.

**Expected behavior**
I expect to see all tabs in one row.

**Screenshots**
![image](https://github.com/themesberg/flowbite-react/assets/16003/9104b3ff-d629-4c02-9055-c90797b8f3d7)

**System information:**

- OS: MacOS Ventura 13.3.1
- Browser: Chrome
- Version: 112.0.5615.137

**Comment by tulup-conner** [comment]
I think this is fixed now! We'll have it in the next release.

**Comment by gsterndale** [comment]
Awesome sauce! Thank you.

**Comment by tulup-conner** [comment]
Hey @gsterndale you can find this in the new version, v0.4.8. Thank you!
