### ISSUE TITLE
Double sided range slider

### ISSUE THREAD

**Issue by haron68** [themesberg/flowbite-react#814]
**Is your feature request related to a problem? Please describe.**
I want to implement a double range slider that allows for a min/max values to be selected
https://codepen.io/predragdavidovic/pen/mdpMoWo

**Describe the solution you'd like**
I would like RangeSlider to support this usecase

**Describe alternatives you've considered**
I've considered implementing this manually

**Additional context**
<img width="1274" alt="image" src="https://github.com/themesberg/flowbite-react/assets/27697689/3f534db6-d8c1-4908-9edd-bddc429828c4">

**Comment by haron68** [comment]
@rluders I can submit a solution for this if you see it as valid. Seems like a common usecase I've seen it being used on Airbnb, Swimply

**Airbnb**
<img width="763" alt="image" src="https://github.com/themesberg/flowbite-react/assets/27697689/9b79efce-a637-485a-b02b-17f694b1c0c9">

**Swimply**
<img width="305" alt="image" src="https://github.com/themesberg/flowbite-react/assets/27697689/58c72e1d-086d-4c69-b783-daa9dfba58bb">

**Comment by rluders** [comment]
Typically new features come from the standard flowbite library and it is implemented for flowbite-react. Let me include @zoltanszogyenyi in this discussion.

Do we need a design on Figma for this component before implementing it? Can we first implement it for flowbite-react?

**Comment by haron68** [comment]
Good questions 
1. Yes would be good to have a figma mock up 
2. Yes I think a working first pass solution can be written up rather quickly for React implementation

**Comment by tulup-conner** [comment]
Let's defer the issue here until that gets done, but I personally love the idea of this. We just can't really make executive decisions to add new components/features outside of the main library.
