### ISSUE TITLE
After changing classNames to twMerge in version 0.4.8, some necessary values may have been ignored in the result.

### ISSUE THREAD

**Issue by boeto** [themesberg/flowbite-react#820]
**Describe the bug**
After changing classNames to twMerge in version 0.4.8, some necessary values may have been ignored in the result. For example, the spacing between the input text and the icon in this case would be ignored, even though this spacing is needed. You can try the two different results below:

```
# Current 0.4.8 version's computational logic and results:
const twMergeResult = twMerge('pl-10', 'p-2.5');
console.log('twMergeResult:::', twMergeResult);
>>twMergeResult::: p-2.5

# The expected result with twMerge:
const twMergeResult = twMerge('p-2.5','pl-10');
console.log('twMergeResult:::', twMergeResult);
>>twMergeResult::: pl-10 p-2.5
```

```
# The expected result with classNames.
const classNamesResult = classNames('pl-10', 'p-2.5');
console.log('classNamesResult:::', classNamesResult);
>>classNamesResult::: pl-10 p-2.5
```

This result implies that the setting of pl-10 in the default theme is invalid. This is just one example, but there may be many similar values that are ignored.

[https://github.com/themesberg/flowbite-react/pull/816/files#diff-18d423d9a3349dc92dd4889c04f04a615672a31f22047eed084c7a30a4db2147R87](https://github.com/themesberg/flowbite-react/pull/816/files#diff-18d423d9a3349dc92dd4889c04f04a615672a31f22047eed084c7a30a4db2147R87)

**Expected behavior**
Of course, I can override it by providing custom values, but it would be better if it is not necessary to do so.

**Screenshots**
![Snipaste_2023-06-22_18-01-59.png](https://dsc.cloud/b6ff69/Snipaste_2023-06-22_18-01-59.png)
![Snipaste_2023-06-22_18-02-44.png](https://dsc.cloud/b6ff69/Snipaste_2023-06-22_18-02-44.png)

**System information:**

- Device:Macos 13.3.1
- Browser:chrome
- Version:114.0.5735.133

**Project information:**

- Tailwind: 3.3.2
- Flowbite: 1.6.6
- Flowbite React: 0.4.8,
- Type: Nextjs13

**Additional context**

**Comment by rluders** [comment]
Hey @boeto, great catch! Fixing this should be a breeze. Simply reversing the order of the classes should give us the desired outcome.

On a different note, it just occurred to me... Do you think it would be beneficial for us to create an issue/task for implementing a unit test? This test could validate the component styles against the styles already present in the standard flowbite library.

**Comment by rluders** [comment]
Also, let me include @tulup-conner on this one.

**Comment by boeto** [comment]
> Hey @boeto, great catch! Fixing this should be a breeze. Simply reversing the order of the classes should give us the desired outcome.
> 
> On a different note, it just occurred to me... Do you think it would be beneficial for us to create an issue/task for implementing a unit test? This test could validate the component styles against the styles already present in the standard flowbite library.

Implementing a unit test can effectively verify our expected result, which would be a great start!

**Comment by rluders** [comment]
I'm closing this one since some of the issues here have already been fixed, and we have a follow-up task to verify the styling.
