### ISSUE TITLE
Implement Unit Tests for flowbite-react component styles verification

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#821]
**Is your feature request related to a problem? Please describe.**
I have noticed that there is currently no automated process to verify if the CSS classes used in the components of the `flowbite-react` library match with the corresponding classes from the standard `flowbite` library. This can lead to inconsistencies and styling issues when integrating `flowbite-react` components into projects.

**Describe the solution you'd like**
I would like to implement unit tests for all the components of the `flowbite-react` library to ensure that the CSS classes used in the components align with the ones from the standard `flowbite` library. These unit tests will validate that the expected CSS classes are present in the rendered components and help maintain consistency in styling across the library.

**Describe alternatives you've considered**
One alternative would be to manually inspect and compare the CSS classes in each component against the standard `flowbite` library. However, this approach is time-consuming, error-prone, and not scalable as the library evolves. By implementing automated unit tests, we can ensure consistent styling and streamline the validation process for future updates.

**Additional context**
As `flowbite-react` is widely used in various projects, it is crucial to maintain consistency and compatibility with the standard `flowbite` library. These unit tests will provide an added layer of confidence in the integrity of the components' styling and assist developers in identifying any discrepancies or unintended changes in the CSS classes.

**Components**

- [x] #822
- [x] #823
- [x] #824
- [ ] Badge
- [ ] Breadcrumb
- [ ] Button
- [ ] Button group
- [ ] Card
- [ ] Carousel
- [ ] Dropdown
- [ ] Footer
- [ ] Forms
- [ ] List group
- [ ] Modal
- [ ] Navbar
- [ ] Pagination
- [ ] Progress bar
- [ ] Rating
- [ ] Sidebar
- [ ] Spinner
- [ ] Table
- [ ] Tabs
- [ ] Timeline
- [ ] Toast
- [ ] Tooltip

**Is your feature request related to a problem? Please describe.**
I have noticed that there is currently no automated process to verify if the CSS classes used in the components of the `flowbite-react` library match with the corresponding classes from the standard `flowbite` library. This can lead to inconsistencies and styling issues when integrating `flowbite-react` components into projects.

**Describe the solution you'd like**
I would like to implement unit tests for all the components of the `flowbite-react` library to ensure that the CSS classes used in the components align with the ones from the standard `flowbite` library. These unit tests will validate that the expected CSS classes are present in the rendered components and help maintain consistency in styling across the library.

**Describe alternatives you've considered**
One alternative would be to manually inspect and compare the CSS classes in each component against the standard `flowbite` library. However, this approach is time-consuming, error-prone, and not scalable as the library evolves. By implementing automated unit tests, we can ensure consistent styling and streamline the validation process for future updates.

**Additional context**
As `flowbite-react` is widely used in various projects, it is crucial to maintain consistency and compatibility with the standard `flowbite` library. These unit tests will provide an added layer of confidence in the integrity of the components' styling and assist developers in identifying any discrepancies or unintended changes in the

**Comment by rluders** [comment]
This is related to #820. I don't expect to see one single PR that will cover all the issues, for this reason, I'm creating issues for every item on the checklist, this task is used just to track the progress.

**Comment by tulup-conner** [comment]
I like this idea but I don't think it would be feasible to maintain something like this. It seems like it would be a huge task to setup.
