### ISSUE TITLE
Button disabled hover state

### ISSUE THREAD

**Issue by nigellima** [themesberg/flowbite-react#827]
**Describe the bug**
Some button colors still have a hover state color change when is disabled. Is this intended? Checking the flowbite.com website, the only example of disabled button there the hover state is completely static. 

**To Reproduce**

1. Add disabled={true} prop to Button component
2. Check all possible colors
3. Hover button

**Expected behavior**
All buttons should not change any text/bg colors when hovering in disabled mode

**Screenshots**

![button-disabled](https://github.com/themesberg/flowbite-react/assets/14295280/5a314c4c-319a-4ec7-a9e4-b9d2266d565e)

**System information:**

- Device:
- Resolution:
- OS:
- Browser:
- Version:

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.4.9 (edited by repo-owner)
- Type: CRA

**Comment by rluders** [comment]
@nigellima you are really using `flowbite-react 0.1.2`? If so, please, update it... It seems that this issue isn't happening in the current version anymore - at least it isn't visible in the documentation.

I'm closing this one as "won't fix", 'cause we don't support previous versions of the library.
