### ISSUE TITLE
Body is left unscrollable when a modal is closed

### ISSUE THREAD

**Issue by utkarshpant** [themesberg/flowbite-react#829]
**Describe the bug**
While using flowbite-react in a private project, we encountered #818 and followed the solution to update the package to v0.4.9. Now, however, we a encountering a new issue with Modals. When _any_ modal is closed, the body is left un-scrollable due to an `overflow: hidden` added to the body's style. I suspect this overflow is not removed once the modal closes, so the page can't be scrolled.

**To Reproduce**
[Apologies, I don't have a minimal reproduction of the issue yet. Shall update when I can make one]. The steps to reproduce are to essentially add a modal to a component, and then open + close it. The page cannot be scrolled.

**Expected behavior**
The restriction on scroll that is added when the modal opens, should be removed, and the page should be scrollable again.

**Screenshots**
NA.

**System information:**

- Device: MacBook Pro 15-inch, 2016
- Resolution: 
- OS:  macOS Monterey 12.6.7
- Browser: Google Chrome
- Version:  114.0.5735.133 (Official Build) (x86_64)

**Project information:**

- Tailwind: ^3.2.7
- Flowbite: ^1.5.0
- Flowbite React: ^0.4.9
- Type: Remix

**Additional context**
NA

**Comment by rluders** [comment]
@utkarshpant can you see the issue also happening [here](https://www.flowbite-react.com/docs/components/modal)?

**Comment by normandanielmq** [comment]
I was able to reproduce it. Had to downgrade.

**Comment by rluders** [comment]
> I was able to reproduce it. Had to downgrade.

Can you share how you did it?

**Comment by normandanielmq** [comment]
![image](https://github.com/themesberg/flowbite-react/assets/3768947/b6aba586-23b2-48ca-9f98-ce2443250b34)
It also has added the issue of showing elements outside the modal when it does not fit in the screen.

**Comment by rluders** [comment]
I submitted a PR to fix some other issue that I found, but folks, TBH, I have no idea how to reproduce any of the issues listed here.

So... if you folks could provide some repository with minimal reproducible code for the problem it would be nice. Also, I think that the problem that @normandanielmq found is different from the one that @utkarshpant found, IMHO.

**Comment by utkarshpant** [comment]
Hi @rluders! My apologies. I've not gotten any time to create a reproduction for this issue. As for your question, the issue I reported is not occurring in the documentation. However, in the docs, when I open a modal, the body is not modified, so I'm not sure of the cause of what I'm seeing.

I'll try and share a reproduction pronto.

**Comment by andersonba** [comment]
This occurred to me and, from my understanding, it retains the overflow when the component is removed from the tree without altering the "show" property (Where I presume there's a _useEffect_ that removes the overflow attribute from the body).

For example:

```tsx
{showModal && <MyComponentWithModal />}
```

Being that, internally `MyComponentWithModal` has the "show" prop fixed as _true_.

**Comment by SutuSebastian** [comment]
@andersonba do u still encounter this issue?

**Comment by tulup-conner** [comment]
I don't have this issue as of today, so I'm going to close since we haven't heard back from OP. Definitely feel free to open a new one if you do still have this happen, but I couldn't reproduce it

**Comment by zyewamed** [comment]
Just encountered this issue myself (flowbite^1.7.0; flowbite-react^0.4.11). Anderson's solution didn't work for me, unfortunately. I instead manually restore scroll on close. E.g. in my case:
```tsx
<Modal onClose={() => {
  // ...
  document.body.style.overflowY = 'scroll'
}} />
```
Hope this helps others in the future.
