### ISSUE TITLE
NextJS 13 Tailwind 3.3.2 : Navbar hamburger icon vanishes 

### ISSUE THREAD

**Issue by ttsoares** [themesberg/flowbite-react#831]
**Describe the bug**
Is the hamburger icon is clicked the menu do appear but the icon itself vanishes, so it is impossible to close the menu without choose a menu option.

**To Reproduce**
Install NextJS latest, Tailwind and Flowbite as explained in the documentation.

`<Navbar fluid={true} rounded={true} className="w-full">
     <Navbar.Brand href="https://flowbite.com/">
       <Image className="h-8 mr-3" src={logo} alt="Logo" />
     </Navbar.Brand>
     <Navbar.Toggle />
     <Navbar.Collapse>
       <Navbar.Link href="/news_home" active={true}>
         Home
       </Navbar.Link>
       <Navbar.Link href="/news_home">Home</Navbar.Link>
       ...
     </Navbar.Collapse>
</Navbar>`
At 'sm' size the hamburger icon do appear but if clicked it is impossible to close the menu as there is no other (like X) icon is offered in the UI. 

Tested in a Linux Mint with Firefox 114.0.2. 

**Project information:**
- Tailwind: 3.3.2
- Flowbite: 1.6.6
- Flowbite React: 0.4.9
- Type: CRA

**Additional context**
This navbar menu do not work ![burger](https://github.com/themesberg/flowbite-react/assets/42324195/a11160b0-1a81-47be-b19a-f6ec198d6131) with Version 114.0.5735.133 or Brave Version 1.52.126

**Comment by ibrahimtuksal** [comment]
i am having the same problem

**Comment by ttsoares** [comment]
The solution I adopted was migrate to :
https://www.material-tailwind.com/

**Comment by rluders** [comment]
It was probably fixed already. I'll release a new version today.

**Comment by rluders** [comment]
@ibrahimtuksal could you check if the latest version `0.4.10` solves the issue? It should.

**Comment by ibrahimtuksal** [comment]
@rluders  Yes, problem solved. Thanks

**Comment by rluders** [comment]
Thank you. Closing the issue.
