### ISSUE TITLE
The border color of the sidebar flickers during the theme switching process.

### ISSUE THREAD

**Issue by boeto** [themesberg/flowbite-react#838]
**Describe the bug**

During the process of switching themes, there is a delay in the color change of the sidebar border. When switching to the dark theme, there will be a white edge left behind, and when switching to the light theme, there will be a black edge left behind. Although these residual edges will disappear quickly, the visible flicker will give users a bad experience.

Here is a demo site for flowbite-react:
[react-admin-dashboard-pro/preview](https://flowbite.com/react-admin-dashboard-pro/preview/)

Here is the custom theme style code:
```ts
import { CustomFlowbiteTheme } from "flowbite-react";

const sidebarCustomTheme: CustomFlowbiteTheme["sidebar"] = {
  root: {
    base: "flex fixed top-0 left-0 z-20 flex-col flex-shrink-0 pt-16 h-full duration-75 border-r border-gray-200 lg:flex transition-width dark:border-gray-700",
  },
};

export { sidebarCustomTheme };
```

**Expected behavior**
Do not let the border color of the sidebar flicker during the theme switching process. For example, the border color of the navigation bar works very well.

**Screenshots**
<img width="1065" alt="Snipaste_2023-07-03_14-13-45" src="https://github.com/themesberg/flowbite-react/assets/34640489/e1f438b6-6c0f-403a-a72d-517d58bf894f">
<img width="1059" alt="Snipaste_2023-07-03_14-13-09" src="https://github.com/themesberg/flowbite-react/assets/34640489/81c07b3f-a70e-4b37-9eb7-1b65c5fbec9a">

https://github.com/themesberg/flowbite-react/assets/34640489/de136b66-2f9b-4b52-8d51-45b7b5739da8

**Comment by tulup-conner** [comment]
Interesting. I can confirm I see this on Firefox, Brave and Edge on Linux and Windows. I don't see it on Safari.

It seems like this is probably happening across the page but is only noticeable in certain rendering edge cases? Like maybe this is a bit harder for the browser to render efficiently for some reason I don't understand. I could also definitely imagine that the fact we are using React context to control this state might slow things down.

I don't think we can do much to fix this, realistically, but I definitely welcome someone to look into it.

**Comment by konantovich** [comment]
Alternatively, remove duration-75

**Comment by tulup-conner** [comment]
The React Admin Dashboard hasn't been updated to the latest flowbite-react, which loads the dark theme immediately, and resolves this issue. So this shouldn't be a problem anymore.
