### ISSUE TITLE
Using `setState` in a Modal loses input focus

### ISSUE THREAD

**Issue by nathguen** [themesberg/flowbite-react#841]
**Describe the bug**
Whenever I set the state for an input in a modal, the input loses focus. If I use a `ref` instead, it works fine. If the input is used outside of the modal, the `useState` doesn't make the input lose focus.

**To Reproduce**

1. Copy the base example of a "Modal with form elements" found on the [modals page](https://www.flowbite-react.com/docs/components/modal)
2. Add a `useState` hook to the `onChange` event of either input
3. Observe that the focus is lost

**Expected behavior**
The input should not blur on each new added character.

**System information:**

- Device: Macbook Pro
- Resolution: 
- OS: Ventura 13.4.1
- Browser: Chrome
- Version: 

**Project information:**

- tailwindcss: 3.3.2
- Flowbite: 1.7.0
- Flowbite React: 0.4.10
- Type: Next.js w/ React

**Additional context**

**Comment by rluders** [comment]
Maybe this is a dup? #701
