### ISSUE TITLE
Disabled dropdown still opens the dropdown items list

### ISSUE THREAD

**Issue by victorfunes** [themesberg/flowbite-react#844]
**Describe the bug**
Disabling a dropdown changes the button status and the cursor pointer, but if you click on the button, the dropdown items list is still opening.

**To Reproduce**
1. Create a dropdown with a dropdown list
2. Disable the component       <Dropdown disabled={true} ...> <Dropdown.Item ...> 
3. Click on the disabled button and the dropdown list will appear.

**Expected behavior**
Disabled dropdowns shouldn't open the dropdown items list.

**Screenshots**
<img width="130" alt="Screenshot 2023-07-07 at 18 11 00" src="https://github.com/themesberg/flowbite-react/assets/108006690/cb5224f1-def5-4964-abc9-2c59a9c93681">

**System information:**

- OS: Mac OS
- Browser: Chrome
- Version: 114.0.5735.198

**Project information:**

- Tailwind: 3.2.4
- Flowbite: 1.6.5
- Flowbite React: 0.4.10
- Type: CRA

**Comment by rluders** [comment]
#840 was merged yesterday but has not been released yet. It should fix this issue.

**Comment by victorfunes** [comment]
Thank you!
