### ISSUE TITLE
Documentation showing broken code for Dropdown example

### ISSUE THREAD

**Issue by rluders** [themesberg/flowbite-react#846]
**Describe the bug**

The `renderTrigger` code from the documentation example isn't rendered as expected.

**To Reproduce**

1. Go to https://www.flowbite-react.com/docs/components/dropdown
2. Scroll to `Custom trigger` example
3. See error

**Expected behavior**

I was hoping to see the correct code:

```jsx
<CodePreview title="Custom trigger dropdown">
  <Dropdown dismissOnClick={false} renderTrigger={() => <span>My custom trigger</span>}>
    <Dropdown.Item>Dashboard</Dropdown.Item>
    <Dropdown.Item>Settings</Dropdown.Item>
    <Dropdown.Item>Earnings</Dropdown.Item>
    <Dropdown.Item>Sign out</Dropdown.Item>
  </Dropdown>
</CodePreview>
```

**Screenshots**

![image](https://github.com/themesberg/flowbite-react/assets/191027/519a0e65-5538-4ad4-9f85-214cfe14975e)

**System information:**

Not relevant.

**Project information:**

- Flowbite React: 0.4.10

**Additional context**

None.

**Comment by tulup-conner** [comment]
Yep, this is a limitation of the library we're using for code previews that is outside the scope of what I can fix.

In this case, we should just manually insert the code as a string via `<CodePreview code="">..</CodePreview>`. Yes, I know, it makes me sad, too. I'll make this change as part of my deliverable this week.

**Comment by tulup-conner** [comment]
BTW, I don't think we should tag this bug since it isn't an issue with the library
