### ISSUE TITLE
Sidebar.Collapse and other components fails to accept heroicons/react

### ISSUE THREAD

**Issue by victorfunes** [themesberg/flowbite-react#847]
**Describe the bug**
I have just upgraded to 0.4.11 and the ts compiler fails when using `icon` property in `Dropdown.Item` and `Sidebar.Collapse` with `@heroicons/react`. The error message:

```
Type 'ForwardRefExoticComponent<Omit<SVGProps<SVGSVGElement>, "ref"> & { title?: string | undefined; titleId?: string | undefined; } & RefAttributes<SVGSVGElement>>' is not assignable to type 'FunctionComponent<SVGProps<SVGSVGElement>>'
```

**To Reproduce**

1. Create a CRA.
2. Install `flowbite-react` following the docs.
3. Install `@heroicons/react`.
4. Use the sidebar code, but with `heroicons`' icons. Sample code:

```jsx
import {Cog6ToothIcon, BuildingOffice2Icon} from "@heroicons/react/24/outline";
// ...
<Sidebar>
  <Sidebar.Collapse icon={Cog6ToothIcon} label="Configuration" open={false}>
    <Sidebar.Item icon={BuildingOffice2Icon}>
      Corporation
    </Sidebar.Item>
  </Sidebar.Collapse>
</Sidebar>
```

> **Note**
> The same problem was confirmed for `Dropdown`, `TextInput`... It is possible that other components are also affected.

**Expected behavior**
It should compile without issues.

**System information:**

- OS: MacOS

**Project information:**

- Typescript: 5.1.6
- Tailwind: 3.3.2
- Flowbite: 1.7.0
- Flowbite React: 0.4.11
- Heroicons: 2.0.18
- Type: Vite

**Additional context**
I have updated all the libraries and ts compiler, as well as migrated to vite. Maybe I did something wrong that affected to this behaviour.

**Comment by rluders** [comment]
@victorfunes could you do me a favor and also test if the issue happens for the `TextInput` component with an icon?

**Comment by victorfunes** [comment]
@rluders yes, you are right, it also shows the error in this case:

`<TextInput type="text" rightIcon={ArrowRightOnRectangleIcon}/>`

**Comment by rluders** [comment]
All right, thank you.

I think that we need to replace this:

https://github.com/themesberg/flowbite-react/blob/5acb61263bfeb0805a50a73b005673227482c5c0/src/components/Sidebar/SidebarItem.tsx#L35

with this:

```jsx
icon?: React.ComponentType<React.SVGProps<SVGSVGElement>>
```

Of course, that it will be necessary to be replaced in all places where we are using `FC<ComponentProps<'svg'>>`... And, it would be necessary to test it first, but this is the basic idea and the reason for the issue. Also it is worth to test if it will not be a problem when using `react-icons` instead just the `heroicons` package.

**Comment by victorfunes** [comment]
Thank you!

**Comment by tulup-conner** [comment]
Your code works for me when I add Hero Icons to the flowbite-react.com Next.js site. So I am confused, to be honest, about what is going wrong on your end.

Can you try the following?

```js
<Sidebar.Collapse icon={() => <Cog6ToothIcon />} label="E-commerce">
```

That works for me, also.

**Comment by victorfunes** [comment]
@tulup-conner 
Confirmed: if I use the function it works (it compiles without errors), but the size of the icon is not correct by default (see screen capture of sidebar).

`<Sidebar.Collapse icon={() => <Cog6ToothIcon />} label="E-commerce">`

<img width="254" alt="image" src="https://github.com/themesberg/flowbite-react/assets/108006690/b8fbb302-3e30-46e5-bedc-2c722c7973da">

**Comment by rluders** [comment]
Well, the problem with using the function is that it will not get the theme properties to change the size of it. So... You could probably get the theme context and apply the theme to the icon, but... I don't think that it would be nice.

I'll try to reproduce the reported scenario today to see if I can get more details about it.

**Comment by victorfunes** [comment]
Maybe it can help you to have my tsconfig.json

`{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "declaration": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "composite": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src", "src/**/*.ts*", "**/*.ts", "**/*.tsx", "i18n-resources.bckp", "i18n-resources.bckp", "**/*.json"],
  "exclude": ["node_modules", "dist", "lib"]
}`

**Comment by rluders** [comment]
I wasn't able to reproduce the issue, it seems to work as expected. 

I imported:
```ts
import { Cog6ToothIcon, BuildingOffice2Icon } from '@heroicons/react/24/outline';
```

Using the multi-level dropdown example:
```jsx
<Sidebar aria-label="Sidebar with multi-level dropdown example">
  <Sidebar.Items>
    <Sidebar.ItemGroup>
      <Sidebar.Item href="#" icon={HiChartPie}>
        Dashboard
      </Sidebar.Item>
      <Sidebar.Collapse icon={Cog6ToothIcon} label="E-commerce">
        <Sidebar.Item icon={BuildingOffice2Icon} href="#">
          Products
        </Sidebar.Item>
        <Sidebar.Item href="#">Sales</Sidebar.Item>
        <Sidebar.Item href="#">Refunds</Sidebar.Item>
        <Sidebar.Item href="#">Shipping</Sidebar.Item>
      </Sidebar.Collapse>
      <Sidebar.Item href="#" icon={HiInbox}>
        Inbox
      </Sidebar.Item>
      <Sidebar.Item href="#" icon={HiUser}>
        Users
      </Sidebar.Item>
      <Sidebar.Item href="#" icon={HiShoppingBag}>
        Products
      </Sidebar.Item>
      <Sidebar.Item href="#" icon={HiArrowSmRight}>
        Sign In
      </Sidebar.Item>
      <Sidebar.Item href="#" icon={HiTable}>
        Sign Up
      </Sidebar.Item>
    </Sidebar.ItemGroup>
  </Sidebar.Items>
</Sidebar>
```

The result:
![image](https://github.com/themesberg/flowbite-react/assets/191027/dcec9af4-9a01-413c-a22c-30315bf61feb)

**Comment by victorfunes** [comment]
Maybe it's my mistake in something in my project. Apologies as I am newbie with this technology and learning by myself.

![image](https://github.com/themesberg/flowbite-react/assets/108006690/c7dc3856-a482-4431-83ee-2bb1316a7934)

**Comment by rluders** [comment]
All right, now I was able to reproduce the error. I just created a new CRA application and I'm getting the same error, but it only happens for the `Sidebar.Collapse`, it doesn't happen for the `Sidebar.Item`.

**Comment by rluders** [comment]
I can also confirm that the issue is happening for `TextInput` as reported by @victorfunes. So, I'll keep my statement that it can be affecting other components that also use the `icon` property.

**Comment by victorfunes** [comment]
> All right, now I was able to reproduce the error. I just created a new CRA application and I'm getting the same error, but it only happens for the `Sidebar.Collapse`, it doesn't happen for the `Sidebar.Item`.
> 
> PS: For some reason that I don't know, it doesn't happen if you test directly with our NextJS Documentation application.

Correct: it doesn't happen for the Sidebar.Item

**Comment by rluders** [comment]
https://github.com/tailwindlabs/heroicons/discussions/981

**Comment by rluders** [comment]
It means that you will have to hack:

```ts
type IconSVGProps = React.PropsWithoutRef<React.SVGProps<SVGSVGElement>> & React.RefAttributes<SVGSVGElement>
type IconProps = IconSVGProps & {
  title?: string
  titleId?: string
}

type HeroIcon = FC<Omit<SVGProps<SVGSVGElement>, 'ref'>> & IconProps;

let MyBuildingOffice2Icon: HeroIcon = BuildingOffice2Icon;
```

With that you can use `MyBuildingOffice2Icon` as the value passed to `icon={MyBuildingOffice2Icon}`.

**Comment by victorfunes** [comment]
Thank you! I am not sure if you are speaking how to fix it internally or speaking with me.
I have just tested with react-icons/hi and I have the same problem.
To see if it is inherited from hero icons I have tested with other libraries from react-icons such as md and the same error arises.
Will you close then this issue? Should I go for the workaround?

**Comment by victorfunes** [comment]
@rluders if the final solution is taking time, as this is not happening only with heroicons, I would suggest to add your workaround as a type temporarily in flowbite react to simplify the workaround:

```
import { FC, SVGProps } from "react";

export type IconSVGProps = React.PropsWithoutRef<React.SVGProps<SVGSVGElement>> & React.RefAttributes<SVGSVGElement>;
export type FlowbiteIconProps = IconSVGProps & {
  title?: string;
  titleId?: string;
};

export type FlowbiteIcon = FC<Omit<SVGProps<SVGSVGElement>, "ref">> & FlowbiteIconProps;
```

This will enable the developers to use easily any icon just by doing the cast:

```
  const Cog6ToothIconWorkaround: FlowbiteIcon = Cog6ToothIcon;
  const UserGroupIconWorkaround: FlowbiteIcon = UserGroupIcon;
  const FilmIconWorkaround: FlowbiteIcon = FilmIcon;
```

**Comment by rluders** [comment]
I don't want to push "workaround" to the codebase. I think that any possible "workaround" should be handled outside of the codebase unless we decide that we want to include this `FlowbiteIcon` or something similar to the library as a real thing.
