### ISSUE TITLE
Stateless Toast 

### ISSUE THREAD

**Issue by nigellima** [themesberg/flowbite-react#848]
Using the Toast component in real apps is kinda hard.
- The `isRemoved` does not remove the toast from the DOM, just applies a `hidden` class 
- Animation existis on the remove, which conflicts with the use of toast handlers like `react-toastfy` or `react-host-toast`.

**Describe the solution you'd like**
Toast could have a stateless option which would make easy to integrate with external tools.

**Comment by nigellima** [comment]
@rluders @tulup-conner So I have a proposal for this:

It could be added a prop to the `<Toast />` called `onClose: () => void`. If the developer passes this prop, then the `<Toast />` component becomes stateless and then they will be able to handle the dismiss as they prefer. It would also keep the current behaviour without any breaking changes.
 What do you think?

**Comment by rluders** [comment]
Having an `onClose` or `onDismiss` handler for the `Toast` component seems like a reasonable addition. However, I am uncertain whether it is desirable to keep the `Toast` component in the DOM after it has been dismissed or closed. If I were to speculate, likely, we do not want to keep it in the DOM.

Considering the library is still in the beta phase, it is acceptable for us to introduce breaking changes. Therefore, in this case, I propose making a breaking change by default, which involves completely removing the `Toast` component from the DOM once it has been dismissed or closed.

**Comment by nigellima** [comment]
> Having an `onClose` or `onDismiss` handler for the `Toast` component seems like a reasonable addition. However, I am uncertain whether it is desirable to keep the `Toast` component in the DOM after it has been dismissed or closed. If I were to speculate, likely, we do not want to keep it in the DOM.
> 
> 
> 
> Considering the library is still in the beta phase, it is acceptable for us to introduce breaking changes. Therefore, in this case, I propose making a breaking change by default, which involves completely removing the `Toast` component from the DOM once it has been dismissed or closed.

Makes sense. Sounds great. I would like to work on that, please
