### ISSUE TITLE
Pagination buttons still have hover styles when disabled 

### ISSUE THREAD

**Issue by nigellima** [themesberg/flowbite-react#849]
**Describe the bug**
When hovering the navigation buttons in the Pagination component, they still have hover styles being applied

![pagination-disabled](https://github.com/themesberg/flowbite-react/assets/14295280/46a2e825-8bc5-4923-9a0b-e6a292454bc1)

**To Reproduce**

1. Go to Documentation website
2. Hover the disabled navigation buttons

**Expected behavior**
Disabled buttons should not have any effect

**Project information:**

- Flowbite React: v0.4.11

**Comment by kharbandaashu** [comment]
@rluders / @nigellima I would like to work on this issue. please assign to me.
