### ISSUE TITLE
"Expand Code" broken on docs?

### ISSUE THREAD

**Issue by mikeknapp** [themesberg/flowbite-react#852]
**Describe the bug**
When I visit the docs and click "Expand code", nothing happens. 

**To Reproduce**

1. Go to any docs page, i.e. https://www.flowbite-react.com/docs/components/alert
2. Click on 'Expand Code'
3. Notice nothing happens.

**Expected behavior**
The code should be expanded.

**Screenshots**
<img width="1001" alt="Screenshot 2023-07-13 at 3 30 52 pm" src="https://github.com/themesberg/flowbite-react/assets/103593/d451dcd0-6cd3-45c5-9002-6c0eb68fc361">

**System information:**

- Device: Laptop
- OS: Mac
- Browser: Chrome

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

**Comment by tulup-conner** [comment]
Thank you! Fix on the way for this now.

**Comment by tulup-conner** [comment]
Resolved with c9a7161e3d148f54f716d1f7f219949a68e8e14c
