### ISSUE TITLE
`As` prop in button component is not working for href with basePath of Link next component

### ISSUE THREAD

**Issue by Rubens10010** [themesberg/flowbite-react#865]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Set basePath in next.config.js
2. Create a Dropdown with Dropdown.Item component
3. Set `as` prop to nextjs Link component
4. Set `href` prop in Dropdown.Item component
5. npm run dev / build

## Current behavior

Url is rendered without considering basePath

## Expected behavior

Url should render basePath + href as in Navbar.Link component

## Context

I need this feature because is expected when using Link in nextjs and my production build is deployed inside a subfolder of the domain server.

**Comment by tulup-conner** [comment]
Thank you, that makes sense! Upon first seeing this I'm not sure whether or not we can resolve this issue on our end. [The Next.js docs on this subject](https://nextjs.org/docs/app/api-reference/next-config-js/basePath) state that the base path is inlined inside of Next.js bundled code... Not a good sign.

**Comment by nigellima** [comment]
> Thank you, that makes sense! Upon first seeing this I'm not sure whether or not we can resolve this issue on our end. [The Next.js docs on this subject](https://nextjs.org/docs/app/api-reference/next-config-js/basePath) state that the base path is inlined inside of Next.js bundled code... Not a good sign.

Actually I might know what is wrong here:

When I created the `BaseButton.tsx` component I kept a condition that existed before which was if `href` exists then the Button becomes an anchor tag. This condition is probably making the Next `as={Link} href="/path"` to render an anchor tag instead of the Next Link component, as the Next Link also uses `href`

https://github.com/themesberg/flowbite-react/blob/ecc3f6ef0156533f2eeb337aad913e0a8182b58d/src/components/Button/ButtonBase.tsx#L12

So we could either change the condition to `const BaseComponent = href && !Component? 'a' : Component ?? 'button';` or make a breaking change that if the user passes an `href` they need to pass the `as` prop too.

**Comment by tulup-conner** [comment]
Oooooooooooooooooooooooooooo yeah that would make sense. And so would your solution!

**Comment by nigellima** [comment]
> Oooooooooooooooooooooooooooo yeah that would make sense. And so would your solution!

You mean the breaking change or the `href && !Component` condition?

**Comment by tulup-conner** [comment]
I think the conditional is definitely preferable here. It's just hard to read, which isn't great.

**Comment by ogheneovo12** [comment]
isn't it better to just ensure that if the as  Component is provided (deliberate intention) it should just render the as Component , if not then internal deliberation can begin

```
export const ButtonBase = forwardRef<HTMLButtonElement | HTMLAnchorElement, Props>(
  ({ children, as, href, ...props }, ref) => {
    const BaseComponent = as || (href ? 'a' : 'button');
    const type = BaseComponent === 'button' ? 'button' : undefined;

    return createElement(BaseComponent, { ref, href, type, ...props }, children);
  },
);
```

**Comment by nigellima** [comment]
> isn't it better to just ensure that if the as Component is provided (deliberate intention) it should just render the as Component , if not then internal deliberation can begin
> 
> ```
> export const ButtonBase = forwardRef<HTMLButtonElement | HTMLAnchorElement, Props>(
>   ({ children, as, href, ...props }, ref) => {
>     const BaseComponent = as || (href ? 'a' : 'button');
>     const type = BaseComponent === 'button' ? 'button' : undefined;
> 
>     return createElement(BaseComponent, { ref, href, type, ...props }, children);
>   },
> );
> ```

Yeaph, that sounds as a good solution. I have a local work on that already. I will submit a PR soon (probably tomorrow)
