### ISSUE TITLE
Logic issue with BaseButton `as` Property

### ISSUE THREAD

**Issue by ogheneovo12** [themesberg/flowbite-react#881]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Steps to reproduce
In a nextjs Application Pass in Link from next/link as the value of the Button `as`  Props, also pass an href property, a normal anchor elements is  still being used, and the custom component (Link) is  ignored

## Current behavior
the custom component (Link) is  ignored

Describe what is currently happening and why it's a problem.
after going through the BaseButton Code, i noticed that a custom component like Link from next/link will be ignored due to their common href props, where the existence of the href props, determines(prioritize), the rendering of a normal anchor tag.

https://github.com/themesberg/flowbite-react/blob/7e7a101ce9e99daa93f9b3f9f5dde52dd3827548/src/components/Button/ButtonBase.tsx#L11C1-L15C82

## Expected behavior
Custom Component Should Take More Priority over any internally determined Component

Describe what you expected to happen.
The Link Component Passed to the `as`  prop  should be the wrapper.

## Context
Only occurs when using custom component that share similar as property

**Comment by rluders** [comment]
Dup  #865?

**Comment by ogheneovo12** [comment]
oh k, thanks will close this and follow up from #865
