### ISSUE TITLE
feature request - component like mui data-grid or shadcn/ui data table

### ISSUE THREAD

**Issue by AmitShashi** [themesberg/flowbite-react#889]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Summary
react tables is not user-friendly and take a lot of time to implement especially if someone wants features like filter,pagination,selection etc

## Context
react table for displaying data in efficient way

**Comment by rluders** [comment]
@AmitShashi I'll need more details for this one. Can you add some examples? Maybe some proposal? Screenshot? Videos? Whatever could help to expand your enhancement suggestion. Just my "not user-friendly" is hard to identify your pain.

**Comment by rluders** [comment]
Closing, not enough information to proceed with this task.
