### ISSUE TITLE
Dropdown docs should display `<Dropdown.Item>`, not `<Item>`

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#894]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to https://www.flowbite-react.com/docs/components/dropdown
2. Observe incorrect example code

**Comment by SutuSebastian** [comment]
Fixed by the new docs engine.
