### ISSUE TITLE
Customizing of Table not fully functioning (reusable component)

### ISSUE THREAD

**Issue by gtonussi** [themesberg/flowbite-react#896]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Import and add table exactly as example with checkboxes: https://www.flowbite-react.com/docs/components/table#table-with-checkboxes
2. Copy the customization object according to documentation, and add it to the theme prop of Table. I used example from Option 3 from https://www.flowbite-react.com/docs/customize/theme
3. Change the classes from "root" and then from "head"

## Current behavior

Only the classes from "root" will be rendered, and the ones from "head" will still be the default, as if nothing was changed on custom object.

## Expected behavior

thead component should inherit the classes passed on "head" property from custom object.

## Context

I'm trying to accomplish a customized Table, styling it with theme prop. It happens on any browser (tested on Safari, Chrome and Firefox), using MacOS Monterey.

Reproduction:
https://codesandbox.io/p/sandbox/unruffled-morning-kpq7r3

On this reproduction, it is possible to customize classes for root, but not for head.

IMPORTANT:
I have tested the Flowbite wrapper approach and it works, so this problem seems to be only occurring with reusable custom component approach.

**Comment by gtonussi** [comment]
After using the <Flowbite> approach, I've found another issue.
Even though it changes the classes, it seems to not apply the property.

You can reproduce it by customizing the Table wrapping it on a Flowbite component, and then applying the theme to that wrapper. After that, you can go to head > cell and change the background-color for example. It will render the component with the new class but not apply it. It will act as no bg was informed at all. The same for "group-first/head:first:rounded-tl-", if you change it to 2xl it will render with class "group-first/head:first:rounded-tl-2xl" but header will have no border on left side.

**Comment by SutuSebastian** [comment]
This issue is fixed by https://github.com/themesberg/flowbite-react/pull/1104, which is present in [0.7.0](https://www.npmjs.com/package/flowbite-react/v/0.7.0) release.
