### ISSUE TITLE
Why is the react implementation of ListGroup using buttons as wrapper by default

### ISSUE THREAD

**Issue by ogheneovo12** [themesberg/flowbite-react#898]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Current behavior

Rather than using buttons by default as the wrapper, a normal list item (ul/ol) should be the default, as list extends just beyond menu list, and let the developer decide when to use buttons.

## Expected behavior

Describe what you expected to happen.

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?
If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by rluders** [comment]
Well, actually it is a `ul > li` element, and inside of it you can have a `button` or `a` tag.

**Comment by ogheneovo12** [comment]
just encountered an hydration error in nextjs while using 
![Screenshot (1003)](https://github.com/themesberg/flowbite-react/assets/49083654/7cfb36d6-8546-49d6-9765-a51c88863742)


will just replicate the styles in the meantime in a custom component without the button wrapper

**Comment by rluders** [comment]
> what i wanted was to avoid using `button` as the wrapper due to accessibility ( a normal list item that are not actionable), the `a` wrapper is ok, as long as it's determined by the provision of the `href `props.

What would happen in the case of non-passing a `href` it should be just the `li` item. I'm trying to understand the goal here, 'cause if you pass the `href=` to the `ListGroup.Item` it will render an `a` inside the `li`, if not, it will render a `button`. 

So, what is the goal here?

> PS: Not sure about the hydration error, if it is related somehow... Our documentation uses NextJS, so... for that, probably need more details and it is probably another issue.

**Comment by rluders** [comment]
Also, please, update the issue template properly. It helps a lot.

**Comment by ogheneovo12** [comment]
> > what i wanted was to avoid using `button` as the wrapper due to accessibility ( a normal list item that are not actionable), the `a` wrapper is ok, as long as it's determined by the provision of the `href `props.
> 
> What would happen in the case of non-passing a `href` it should be just the `li` item. I'm trying to understand the goal here, 'cause if you pass the `href=` to the `ListGroup.Item` it will render an `a` inside the `li`, if not, it will render a `button`.
> 
> So, what is the goal here?
> 
> PS: Not sure about the hydration error, if it is related somehow... Our documentation uses NextJS, and I don't see the error there, I'll need more details... so... for that, probably need more details and it is probably another issue.

there can be a fallback to maybe a span, or  an option to pass in a custom component via a `as` props,
with the button wrapper, having another button as a child, react throws the validateDomString error, button cannot be a descendant of button.

**Comment by ogheneovo12** [comment]
![Screenshot (1005)](https://github.com/themesberg/flowbite-react/assets/49083654/177adf9e-680c-45b6-87db-b1bde481882a)

**Comment by ogheneovo12** [comment]
i  copied the styles from the theme to replicate the above, and extra logic for keyboard navigation (which was a provided out of the box by buttons though)

**Comment by rluders** [comment]
> ![Screenshot (1005)](https://user-images.githubusercontent.com/49083654/258164483-177adf9e-680c-45b6-87db-b1bde481882a.png)

I'm wondering if the list group should be used for this...  but I don't have any good arguments to say that it was not. 😆

**Comment by m1daz** [comment]
Don't know if it applies here but there are hydration errors on sidebar aswell. For example data-testid is added on server but not client, theme label styles are applied on server but if sidebar is closed (which is known by server due to the status of the sidebar being saved in cookies), it will still render classnames as opened sidebar.

**Comment by tulup-conner** [comment]
This component is designed to function as an `<a href="">` when `href` is provided: https://github.com/themesberg/flowbite-react/blob/main/src/components/ListGroup/ListGroupItem.tsx#L42
