### ISSUE TITLE
Custom Select Theme `rounded` class ignored and overridden by Global Theme

### ISSUE THREAD

**Issue by ogheneovo12** [themesberg/flowbite-react#899]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Steps to reproduce
create a custom theme and apply any of tailwind round class, 

## Current behavior
custom theme round class is being ignored

Describe what is currently happening and why it's a problem.
i created a custom theme config for reusable select component, on inspection the `rounded-lg` class from the global theme is always applied and overwrites what's specified in the custom theme

## Expected behavior
custom theme specification should take precedence over the global theme 

Describe what you expected to happen.
custom theme specification should take precedence over the global theme 

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?
nope

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.
![Screenshot (1006)](https://github.com/themesberg/flowbite-react/assets/49083654/1414cc20-1c71-4609-8053-a65322739674)

on inspection
![Screenshot (1007)](https://github.com/themesberg/flowbite-react/assets/49083654/a8a9ff40-799f-4fdb-9b04-4d4d2bb9cacc)

**Comment by rluders** [comment]
The order of the classes really matters for the `twMerge`. If you are including a `rounded-[100px]` to the `base` and some other part of the code will include a `rounded` or any other property that is considered a big weight class (the ones without `-`) it will be replaced. In this case, the best approach is to make it `!rounded-[100px]`.

**Comment by tulup-conner** [comment]
This isn't a bug. Keep in mind that `twMerge` works left-to-right (literally) inside the `class` attribute. Rightmost takes precedent. That works for parts of the theme, too; in this case, that means `twMerge` keeps the `rounded-X` here https://github.com/themesberg/flowbite-react/blob/main/src/components/Select/theme.ts#L21 and overrides your attempt inside `base`.
