### ISSUE TITLE
Build Sidebar component

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-react#9]
Reference: https://flowbite.com/docs/components/sidebar/

**Comment by tulup-conner** [comment]
I'll take this

**Comment by tulup-conner** [comment]
Should the CTA button on Sidebars really have ARIA `role=alert`? That pulls focus immediately on screen readers, which is aggressive. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role

**Comment by rluders** [comment]
> Should the CTA button on Sidebars really have ARIA `role=alert`? That pulls focus immediately on screen readers, which is aggressive. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role

Can't we make it optional? :)

**Comment by tulup-conner** [comment]
Sounds good to me! I'm just referring to the defaults on flowbite.com. I don't want to make any decisions on behalf.

**Comment by tulup-conner** [comment]
@rluders Could you close this one as well, thank you!
