### ISSUE TITLE
Certain links in docs cannot be clicked due to before psuedo element on h2/h3 tags

### ISSUE THREAD

**Issue by AlexMNet** [themesberg/flowbite-react#901]
- [x ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ x] I have tested the latest version

## Steps to reproduce

1. Go to [Next.js Getting Started](https://www.flowbite-react.com/docs/getting-started/nextjs)
2. Try to click on the 'GitHub Repo' or 'Demo' link under the Flowbite Next.js Starter header

## Current behavior

These links, among other links in the docs as well are not clickable. Upon inspecting the page in chrome dev tools I noticed a before pseudo element which is preventing from these links being clicked. Removing the before selectors in the useMDXComponents for the h2 fixes this issue. 

mdx-components.tsx
```jsx
export const useMDXComponents: (components: MDXComponents) => MDXComponents = (components) => {
  return {
    h2: (props) => (
      <h2
        className="group relative z-20 text-2xl font-bold text-gray-900 before:invisible before:-mt-20 before:block before:h-20 before:content-[''] before:dark:text-white"
        {...props}
      >
        {props.children}
        <a
          aria-label={`Link to this section: ${props.children}`}
          href={`#${props.id}`}
          className="ml-2 text-primary-700 opacity-0 transition-opacity group-hover:opacity-100 dark:text-primary-500"
        >
          #
        </a>
      </h2>
    ),
    h3: (props) => (
      <h3
        className="group relative z-10 text-2xl font-bold text-gray-900 before:invisible before:-mt-20 before:block before:h-20 before:content-[''] before:dark:text-white"
        {...props}
      >
        {props.children}
        <a
          aria-label={`Link to this section: ${props.children}`}
          href={`#${props.id}`}
          className="ml-2 text-primary-700 opacity-0 transition-opacity group-hover:opacity-100 dark:text-primary-500"
        >
          #
        </a>
      </h3>
    ),
    ...components,
  };
};
```

## Expected behavior

I expect to be able to click links without surrounding elements preventing this. 

## Context

Unless there is a good reason for having the before pseudo elements on these h2/h3 tags I propose removing them in the file above to fix the issue. If this is the proper route, I can submit a PR. Thanks!

**Comment by rluders** [comment]
Apparently it was fixed already.
