### ISSUE TITLE
Dropdown width cannot be customized

### ISSUE THREAD

**Issue by victorfunes** [themesberg/flowbite-react#905]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

1. Create a dropdown with several items having long and short texts.
2. Select a short text item
3. Select a long text item

## Current behavior

The component width varies based on the selected option.

<img width="149" alt="image" src="https://github.com/themesberg/flowbite-react/assets/108006690/bf957b5d-46a5-4449-936c-4c2857d8d414">

<img width="131" alt="image" src="https://github.com/themesberg/flowbite-react/assets/108006690/4fcd1a1e-cba9-4882-bbd2-80206c5391a3">

```
        <Dropdown label={selectedDate} color="light">
          <Dropdown.Item onPointerDown={filterLastYear}>Last year</Dropdown.Item>
          <Dropdown.Item onPointerDown={filterLastMonth}>Last 30 days</Dropdown.Item>
          <Dropdown.Item onPointerDown={filterLastWeek}>Last 7 days</Dropdown.Item>
          <Dropdown.Item onPointerDown={filterAlways}>Always</Dropdown.Item>
        </Dropdown>
```

## Expected behavior

Define my own width for the component.
In my case 
```<Dropdown label={selectedDate} color="light" className="w-full">``` 
is not working.

**Comment by victorfunes** [comment]
Workaround customizing theme here: https://github.com/themesberg/flowbite-react/issues/911

**Comment by tulup-conner** [comment]
see discussion at #934
