### ISSUE TITLE
Accordion.Panel's isOpen is not working when populating them with a state object

### ISSUE THREAD

**Issue by emre88tosun** [themesberg/flowbite-react#907]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Current behavior

I've an array of strings and using those for populating accordion panels. Even though the Accordion's collapseAll is false and alwaysOpen is true, and even though the mapped Accordion.Panels' isOpen is set true, when I add a new string to my array, newly populated Accordion.Panel doesn't come as open.

## Expected behavior

Describe what you expected to happen.

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by rluders** [comment]
It would be nice to have more information, screenshots, videos, code examples, and steps to reproduce... otherwise, it would be not easy to test it.

**Comment by tulup-conner** [comment]
Feel free to create an issue if you are still having this problem, but I can't reproduce it.
