### ISSUE TITLE
<p> tag in <p> tag on some pages in flowbite-react.com 

### ISSUE THREAD

**Issue by tulup-conner** [themesberg/flowbite-react#912]
### Discussed in https://github.com/themesberg/flowbite-react/discussions/887

<div type='discussions-op-text'>

<sup>Originally posted by **khylpe** July 28, 2023</sup>
Hi, I noticed an issue in the documentation related to the following structure:

```
<p className="mb-2 text-gray-500 dark:text-gray-400">
  <p>
    Flowbite is an open-source library of interactive components built on top of Tailwind CSS including buttons,
    dropdowns, modals, navbars, and more.
  </p>
</p>
```
This structure creates an error, which seems to be expected due to the HTML standards: 

![image](https://github.com/themesberg/flowbite-react/assets/83074639/34f90ad6-fd31-4d9b-a57a-8869f1fd6546)

I wanted to ask whether this is an error in the documentation, or if it is intentionally designed this way?

</div>

**Comment by SutuSebastian** [comment]
After a bit of digging, the https://mdxjs.com/ library wraps an extra `<p>` html tag when it detects plain text content.

**Comment by MateoWartelle** [comment]
I don't think this is an issue anymore. I couldn't find any example since it was moved to mdx.

**Comment by SutuSebastian** [comment]
It got fixed by the new docs engine.
