### ISSUE TITLE
DarkTheme Toggle does not detect OS or browser dark / light mode

### ISSUE THREAD

**Issue by augustosamame** [themesberg/flowbite-react#914]
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

implement the DarkThemeToggle as indicated in the docs:

```
<Flowbite>
  <DarkThemeToggle />
  ...
</Flowbite>
```

## Current behavior

DarkTheme Toggle does not detect current OS or browser dark / light mode.

## Expected behavior

DarkTheme Toggle should detect current OS or browser dark / light mode as a default

## Context

The current best practice is for initial dark / light themes to inherit from the OS or browser current light / dark mode setting. The DarkThemeToggle doesn't appear to do this. If this is not a bug, is there any way for the component to read from the environment and set the dark / light mode appropriately?

**Comment by augustosamame** [comment]
I can detect the mode using this: 

let initialMode = window.matchMedia('(prefers-color-scheme: dark)').matches ? "dark" : "light")

but how to pass this to DarkThemeToggle (via useEffect ? ) so it will take it as the initial default value?

**Comment by tulup-conner** [comment]
You should be able to provide dark mode by default by providing your `initialMode` to 

```
<Flowbite theme={{ dark: initialMode }}>
```

**Comment by rluders** [comment]
Closing. It isn't a bug, you need to implement it by yourself.
