### ISSUE TITLE
Can't  Override focus  (ring) behaviour of Button 

### ISSUE THREAD

**Issue by ogheneovo12** [themesberg/flowbite-react#930]
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Current behavior
Buttons still maintain focus:ring-2 even after being omitted from global flowbite custom theme

Describe what is currently happening and why it's a problem.
At the global flowbite theme level, i had overwritten the default  focus ring specification for both gray, dark and blue color for buttons, button upon inspection it still maintains focus:ring-2, regardless of the color props specified in the button
```
{
...,
 button: {
   ...,
    color: {
      gray: "bg-primary-blue  enabled:hover:bg-primary-blue2   dark:bg-transparent dark:text-gray-400 dark:border-gray-600 dark:enabled:hover:text-white dark:enabled:hover:bg-gray-700",
      blue: "bg-primary-blue enabled:hover:bg-opacity-90 hover:bg-opacity-90 text-white",
      dark: "text-primary-blue bg-transparent border border-primary-blue enabled:hover:bg-primary-blue dark:text-white  enabled:hover:text-white dark:bg-nav-dark dark:enabled:hover:bg-gray-700  dark:border-gray-700",
    },
    ...
}
```
## Expected behavior
all focus ring behaviour should be gone, 

Describe what you expected to happen.
flowbite should enforce the global theme configuration and most especially if a color prop is specified for the Button Component

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.
![Screenshot (1057)](https://github.com/themesberg/flowbite-react/assets/49083654/257d3dc5-65fe-4fb2-916a-ea6a8c8aa994)
![Screenshot (1058)](https://github.com/themesberg/flowbite-react/assets/49083654/70a1e4d9-a064-44bd-abb1-35e84069c844)

**Comment by DavideFrancescon** [comment]
I resolved this adding `focus:!ring-0`, you can add this to the base if you don't want any button to have the ring or only where you need it (haven't tested but should work).
