### ISSUE TITLE
Inconsistent focus ring

### ISSUE THREAD

**Issue by nigellima** [themesberg/flowbite-react#933]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

1. Go to [Flowbite Storybook](https://storybook.flowbite-react.com/?path=/story/components-textinput--default)
2. Click on the Input
3. See the OS outline being applied to the input instead of flowbite's

## Current behavior

Inconsistent focus ring on components

## Expected behavior

Consistent ring on input/button components

## Context

Weirdly there are cases where some of the components are getting highlighted with the System's default outline. I'm currently using MacOS Monterey 12.3.1.

But it's not always. For example, the form inputs in the lib documentation website have a consistent ring being applied on focus, on the other hand I can see my OS outline in the lib's storybook

Storybook
![image](https://github.com/themesberg/flowbite-react/assets/14295280/8cf84ee8-64b8-45cb-96ce-c7e1def41b0f)

Docs
![image](https://github.com/themesberg/flowbite-react/assets/14295280/608a2ecd-7228-49d2-b7fe-f9630b5e820b)

Docs
![image](https://github.com/themesberg/flowbite-react/assets/14295280/dd177af6-68c1-4ea6-939a-4736c44b5047)

**Comment by DavideFrancescon** [comment]
Looking at the applied css it seems like it's the wanted result. Maybe I missed something but to me it all looks okay. Let me know if i missed something, maybe attach the css of the element under the screenshot so I can compare the two.

**Comment by nigellima** [comment]
> Looking at the applied css it seems like it's the wanted result. Maybe I missed something but to me it all looks okay. Let me know if i missed something, maybe attach the css of the element under the screenshot so I can compare the two.

You mean the wanted result is to always displays the CSS focus `focus:ring-cyan-500` that is applied to the Input, correct?
But in some places the System's outline is overriding this class. Sometimes in the same page, like this section here in the [documentation](https://www.flowbite-react.com/docs/components/forms)

![focus](https://github.com/themesberg/flowbite-react/assets/14295280/aa700374-bf19-4b98-bae0-978e60a25d6c)

**Comment by nigellima** [comment]
Ok I think I found out the issue and it comes from the core library:

[This style](https://github.com/themesberg/flowbite/blob/0e6dcd02aadb77c9a5649c8a0e2d3d3ba38a2624/plugin.js#L187) is applied to a set of input fields. When the `type="text"` the `appearance: none` style is being applied correctly. But once we instantiate a blank text input `<TextInput />` without passing the type, the `appearance: none` is not applied therefore the issue.

Do you think I should open an issue in the core library @zoltanszogyenyi ? Or would be a better fix to default internally the component to `type="text"`?

**Comment by tulup-conner** [comment]
Thank you for tracking that down!

**Comment by tulup-conner** [comment]
Resolved by #1206
