### ISSUE TITLE
Height of the button changes depending on the content

### ISSUE THREAD

**Issue by victorfunes** [themesberg/flowbite-react#937]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

Define the same button twice, one with small icon and text, and the other only with the small icon:
```
      <Button size="sm">
        <CheckIcon className={`h-4 w-4 stroke-2 mr-2 self-center`} />
        <span className="hidden sm:block">Save</span>}
      </Button>
      <Button size="sm">
        <CheckIcon className={`h-4 w-4 stroke-2 self-center`} />
      </Button>
```
## Current behavior

Now the height changes when the button does not have text:

![image](https://github.com/themesberg/flowbite-react/assets/108006690/0d886bc1-9823-4831-8dc0-4ced465376b4)

## Expected behavior

The button should keep the same height.
My solution is to add to the application button theme in the size sm ```min-h-[32px]``` or in the button ```className="min-h-[36px]"``` and it works.

## Context

I am creating standard buttons for my application hidding the text when the screen is mobile, but the size changes depending on the icon size.

**Comment by rluders** [comment]
I guess this problem was fixed. I used the given code to test it at `0.6.0` and it didn't happen.
