### ISSUE TITLE
ToggleSwitch checked={true} disabled={true} not visible

### ISSUE THREAD

**Issue by victorfunes** [themesberg/flowbite-react#986]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

1. Create a toggle switch and set checked={true} and disabled={true}

## Current behavior

- cheked and disabled
![image](https://github.com/themesberg/flowbite-react/assets/108006690/d024e1e5-8887-4053-8645-67cb21e6e98a)

- not checked and disabled:
![image](https://github.com/themesberg/flowbite-react/assets/108006690/01000843-9944-44cc-a51e-5bc1a4eb13ed)

## Expected behavior

It should be visible showing its status as checked.

**Comment by victorfunes** [comment]
@rluders I have downloaded and tested 0.6.1 and the behaviour is still the same: the component is almost not visible when disabled and checked.

**Comment by rluders** [comment]
🤔 this is weird... If I changed it at the docs what I get is:

![image](https://github.com/themesberg/flowbite-react/assets/191027/d1a88244-9826-4f20-846d-7f4955d3e958)

**Comment by rluders** [comment]
@victorfunes are you using `color="light"` by any chance?

**Comment by victorfunes** [comment]
I am using my own theme, but testing with other colors the behaviour is the same.

My theme:
```
  toggleSwitch: {
    toggle: {
      base: "toggle-bg h-6 w-11 rounded-full border group-focus:ring-4 group-focus:ring-primary-500/25",
      checked: {
        color: {
          primary: "bg-primary-600 border-primary-600",
        },
      },
    },
  }
```

My code:

```
          <ToggleSwitch
            id={id}
            label={""}
            color="primary"
            checked={checked}
            disabled={disabled}
            onChange={onChange ?? emptyDummyFunction}
          />
```

**Comment by victorfunes** [comment]
> > In addition: could I ask to make optional the onChange callback property? Thank you!
> 
> Yes, you can... Open a new issue. :)

It was #925 and it seems to be closed.

**Comment by rluders** [comment]
> I am using my own theme, but testing with other colors the behaviour is the same.
> 
> My theme:
> 
> ```
>   toggleSwitch: {
>     toggle: {
>       base: "toggle-bg h-6 w-11 rounded-full border group-focus:ring-4 group-focus:ring-primary-500/25",
>       checked: {
>         color: {
>           primary: "bg-primary-600 border-primary-600",
>         },
>       },
>     },
>   }
> ```
> 
> My code:
> 
> ```
>           <ToggleSwitch
>             id={id}
>             label={""}
>             color="primary"
>             checked={checked}
>             disabled={disabled}
>             onChange={onChange ?? emptyDummyFunction}
>           />
> ```

I'm trying to replicate this, but it still working for me. 🤔 
Of course, I didn't use the `Flowbite` component to apply the theme, but used the `ToggleSwitch`'s `theme` property to overwrite the style.

**Comment by rluders** [comment]
I'm reopening this one, just to remember that would be nice to have someone else testing it.
