### ISSUE TITLE
docs: contributing yarn format

### ISSUE THREAD

**Issue by MateoWartelle** [themesberg/flowbite-react#991]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

[contributing](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md) - indicates yarn format

## Current behavior

Describe what is currently happening and why it's a problem.

error Command "format" not found.

## Expected behavior

Describe what you expected to happen.

maybe a format command needs to be create or remove this yarn format &&

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by MateoWartelle** [comment]
so should they be removed?

Make sure your changes work and don't break anything else:

**yarn format** && yarn lint && yarn test && yarn build

**Comment by rluders** [comment]
I'm pretty sure that format should be replaced with `prettier:fix`

https://github.com/themesberg/flowbite-react/blob/ce55df1fc4b7a4c20a12957b052d8f359e8234a7/package.json#L39
