### ISSUE TITLE
flowbite-react sidebar dark & < 1023px

### ISSUE THREAD

**Issue by MateoWartelle** [themesberg/flowbite-react#992]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

1. Go to https://www.flowbite-react.com/
2. Click Dark Mode Toggle. Click on Sidebar
3. Change screen size to less than 1023

## Current behavior

Describe what is currently happening and why it's a problem.
![1023](https://github.com/themesberg/flowbite-react/assets/27743176/1f5ecbd4-ae8c-4da1-816c-dfac4cd2e632)

dark:hover:bg-transparent

## Expected behavior

Describe what you expected to happen.

should it be Solid Background even on hover?

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.

**Comment by rluders** [comment]
Yep, I'm wondering how we didn't notice it before. Nice catch, @MateoWartelle.
