### ISSUE TITLE
CodePreview Mode Toggle

### ISSUE THREAD

**Issue by MateoWartelle** [themesberg/flowbite-react#993]
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Summary

Describe how it should work, and provide examples of the solution, which might include screenshots or code snippets.

The three buttons from Flowbite added to codePreview on flowbite react

<img width="1681" alt="flowbite-react-toggle-modes" src="https://github.com/themesberg/flowbite-react/assets/27743176/80b1f515-669a-4b0d-a8f8-6de8a18fb244">

<img width="1726" alt="flowbite-react-toggle-modes-dark" src="https://github.com/themesberg/flowbite-react/assets/27743176/861a4222-f7b5-47ce-bd79-2da1140172d4">

## Context

What are you trying to accomplish? How is your use case affected by not having this feature?

To match existing flowbite & other flowbite integrations.

**Comment by rluders** [comment]
@MateoWartelle could you please add more info about the issue?

**Comment by MateoWartelle** [comment]
Flowbite has these three buttons to toggle between modes (full, tablet, mobile) I think I or someone can add to the flowbite-react codepreview. 

<img width="194" alt="flowbite-toggle-modes" src="https://github.com/themesberg/flowbite-react/assets/27743176/b04386ec-4ea6-4294-baff-25f80390933c">

**Comment by rluders** [comment]
Gotcha!

**Comment by SutuSebastian** [comment]
This is actually implemented in #1264.

**Comment by MateoWartelle** [comment]
> This is actually implemented in #1264.

Yes I saw you added that is why I closed.
